createLocalizationString({
	readable = "[icon:Expansion_DF] Mount Modifications",
	constant = "MOUNTMODS_CHECKBOX",
	icon = [[~_.asset("Expansion_DF")]],
	export = true,
	text = {
		en = "Mount Modifications",
		-- de = "",
		es = "Modificaciones de montura",
		es = "Modificaciones de montura",
		mx = "Modificaciones de montura",
		-- fr = "",
		-- it = "",
		-- ko = "",
		-- pt = "",
		ru = "Модификации транспорта",
		-- ko = "",
		cn = "坐骑定制",
		-- tw = "",
	},
})
