local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[464213] = {
		readable = "Jumping Spider",
		model = 1513627,
		text = {
			en = "Jumping Spider",
			de = "Springspinne",
			es = "Araña saltarina",
			fr = "Araignée sauteuse",
			it = "Ragno Salterino",
			mx = "Araña saltarina",
			pt = "Aranha Saltadeira",
			ru = "Прыгучий паук",
			ko = "뜀뛰는 거미",
			cn = "跳蛛",
			tw = "跳躍小蜘蛛",
		},
	},
	[464218] = {
		readable = "Summit Kid",
		model = 576021,
		text = {
			en = "Summit Kid",
			de = "Gipfelzicklein",
			es = "Chico de la cima",
			fr = "Chevreau du sommet",
			it = "Capretto del Picco",
			mx = "Chivo de la cima",
			pt = "Cabrito do Cume",
			ru = "Высокогорный козел",
			ko = "봉우리 꼬마염소",
			cn = "高山小羊",
			tw = "峰頂小羊",
		},
	},
	[477139] = {
		readable = "Lost & Found",
		model = 196982,
		text = {
			en = "Lost & Found",
			es = "Objetos perdidos",
			de = "Fundbüro",
			fr = "Objets trouvés",
			it = "Oggetti Smarriti",
			mx = "Objetos perdidos",
			pt = "Achados & Perdidos",
			ru = "Бюро находок",
			ko = "유실물",
			cn = "失物招领",
			tw = "失物招領",
		},
	},
})
do ObjectDB[objectID] = objectData; end
