local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[473920] = {
		readable = "Void-infused Shard",
		text = {
			en = "Void-infused Shard",
			es = "Void-infused Shard",
			mx = "Void-infused Shard",
			de = "Void-infused Shard",
			fr = "Void-infused Shard",
			it = "Void-infused Shard",
			pt = "Void-infused Shard",
			ru = "Void-infused Shard",
			ko = "Void-infused Shard",
			cn = "Void-infused Shard",
			tw = "Void-infused Shard",
		},
	},
	[502448] = {
		readable = "Void Presence",
		text = {
			en = "Void Presence",
			es = "Void Presence",
			mx = "Void Presence",
			de = "Void Presence",
			fr = "Void Presence",
			it = "Void Presence",
			pt = "Void Presence",
			ru = "Void Presence",
			ko = "Void Presence",
			cn = "Void Presence",
			tw = "Void Presence",
		},
	},
	[503220] = {
		readable = "Weapon Rack",
		text = {
			en = "Weapon Rack",
			es = "Weapon Rack",
			mx = "Weapon Rack",
			de = "Weapon Rack",
			fr = "Weapon Rack",
			it = "Weapon Rack",
			pt = "Weapon Rack",
			ru = "Weapon Rack",
			ko = "Weapon Rack",
			cn = "Weapon Rack",
			tw = "Weapon Rack",
		},
	},
	[507470] = {
		readable = "Tool Rack",
		text = {
			en = "Tool Rack",
			es = "Tool Rack",
			mx = "Tool Rack",
			de = "Tool Rack",
			fr = "Tool Rack",
			it = "Tool Rack",
			pt = "Tool Rack",
			ru = "Tool Rack",
			ko = "Tool Rack",
			cn = "Tool Rack",
			tw = "Tool Rack",
		},
	},
	[523491] = {
		readable = "K'areshi Ore",
		text = {
			en = "K'areshi Ore",
			es = "K'areshi Ore",
			mx = "K'areshi Ore",
			de = "K'areshi Ore",
			fr = "K'areshi Ore",
			it = "K'areshi Ore",
			pt = "K'areshi Ore",
			ru = "K'areshi Ore",
			ko = "K'areshi Ore",
			cn = "K'areshi Ore",
			tw = "K'areshi Ore",
		},
	},
	[523512] = {
		readable = "Rich K'areshi Ore",
		text = {
			en = "Rich K'areshi Ore",
			es = "Rich K'areshi Ore",
			mx = "Rich K'areshi Ore",
			de = "Rich K'areshi Ore",
			fr = "Rich K'areshi Ore",
			it = "Rich K'areshi Ore",
			pt = "Rich K'areshi Ore",
			ru = "Rich K'areshi Ore",
			ko = "Rich K'areshi Ore",
			cn = "Rich K'areshi Ore",
			tw = "Rich K'areshi Ore",
		},
	},
	[527488] = {
		readable = "Phantom Bloom",
		text = {
			en = "Phantom Bloom",
			es = "Phantom Bloom",
			mx = "Phantom Bloom",
			de = "Phantom Bloom",
			fr = "Phantom Bloom",
			it = "Phantom Bloom",
			pt = "Phantom Bloom",
			ru = "Phantom Bloom",
			ko = "Phantom Bloom",
			cn = "Phantom Bloom",
			tw = "Phantom Bloom",
		},
	},
	[527489] = {
		readable = "Lush Phantom Bloom",
		text = {
			en = "Lush Phantom Bloom",
			es = "Lush Phantom Bloom",
			mx = "Lush Phantom Bloom",
			de = "Lush Phantom Bloom",
			fr = "Lush Phantom Bloom",
			it = "Lush Phantom Bloom",
			pt = "Lush Phantom Bloom",
			ru = "Lush Phantom Bloom",
			ko = "Lush Phantom Bloom",
			cn = "Lush Phantom Bloom",
			tw = "Lush Phantom Bloom",
		},
	},
})
do ObjectDB[objectID] = objectData; end
