local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[499022] = {
		readable = "Corrupted Chest",
		model = 3048900,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[499026] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[499028] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[499029] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[499031] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[499954] = {
		readable = "Corrupted Chest",
		model = 3048900,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[524391] = {
		readable = "Prize Chest",
		model = 5788112,
		text = {
			en = "Prize Chest",
			de = "Preistruhe",
			es = "Cofre de premios",
			mx = "Cofre de premios",
			fr = "Coffre de récompense",
			it = "Cassa di Premi",
			pt = "Baú de Prêmios",
			ru = "Призовой сундук",
			ko = "경품 상자",
			cn = "奖品宝箱",
			tw = "獎賞箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end
