local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454707] = {
		readable = "Bag of Stolen Goods",
		model = 1254955,
		text = {
			en = "Bag of Stolen Goods",
			de = "Tasche mit gestohlenen Waren",
			es = "Bolsa de bienes robados",
			fr = "Sac de marchandises volées",
			it = "Borsa di Merci Rubate",
			mx = "Bolsa de bienes robados",
			pt = "Bolsa de Mercadorias Roubadas",
			ru = "Сумка с украденными вещами",
			ko = "도난당한 물품 가방",
			cn = "一袋失窃的货物",
			tw = "一袋被偷的貨物",
		},
	},
	[456665] = {
		readable = "Ore Sample",
		model = 5306874,
		text = {
			en = "Ore Sample",
			de = "Erzprobe",
			es = "Muestra de menas",
			fr = "Échantillon de minerai",
			it = "Campione di Minerale",
			mx = "Muestra de menas",
			pt = "Amostra de Minério",
			ru = "Образец руды",
			ko = "광석 표본",
			cn = "矿石样品",
			tw = "礦石樣本",
		},
	},
	[457143] = {
		readable = "Kaja'Cola Can",
		model = 331512,
		text = {
			en = "Kaja'Cola Can",
			de = "Kaja'Cola-Dose",
			es = "Lata de Kaja'Cola",
			fr = "Canette de Kaja’Cola",
			it = "Lattina di Kaja'Cola",
			mx = "Lata de Kaja'Cola",
			pt = "Lata de Jaka'Cola",
			ru = "Банка \"Каджа-Колы\"",
			ko = "카자콜라 깡통",
			cn = "卡亚可乐罐",
			tw = "卡迦可樂罐",
		},
	},
	[463539] = {
		readable = "Pilfered Earthen Chest",
		model = 5128194,
		text = {
			en = "Pilfered Earthen Chest",
			de = "Geplünderte Kiste der Irdenen",
			es = "Cofre terráneo afanado",
			fr = "Coffre terrestre pillé",
			it = "Forziere dei Terrigeni Rubato",
			mx = "Cofre terráneo saqueado",
			pt = "Baú Terrano Furtado",
			ru = "Украденный сундук земельников",
			ko = "도난당한 토석인 보관함",
			cn = "掠夺的土灵宝箱",
			tw = "失竊的土靈箱子",
		},
	},
	[464233] = {
		readable = "Bilge Rat Supply Chest",
		model = 1806321,
		text = {
			en = "Bilge Rat Supply Chest",
			de = "Vorratstruhe der Bilgeratten",
			es = "Cofre de suministros de las Ratas de Pantoque",
			fr = "Coffre de fournitures des Soutaillons",
			it = "Cassa di Rifornimenti dei Ratti di Sentina",
			mx = "Cofre de suministros de rata de sentina",
			pt = "Baú de Suprimentos do Rato de Porão",
			ru = "Сундук с припасами братства Трюмных Крыс",
			ko = "항만의 시궁쥐단 보급품 보관함",
			cn = "水鼠帮补给箱",
			tw = "污鼠會補給箱",
		},
	},
	[465208] = {
		readable = "Crystal Chunk",
		model = 5869303,
		text = {
			en = "Crystal Chunk",
			de = "Kristallbrocken",
			es = "Trozo de cristal",
			fr = "Morceau de cristal",
			it = "Pezzo di Cristallo",
			mx = "Trozo de cristal",
			pt = "Pedaço de Cristal",
			ru = "Кристальная глыба",
			ko = "수정 덩어리",
			cn = "水晶块",
			tw = "水晶碎塊",
		},
	},
	[465272] = {
		readable = "Empty Kaja'Cola Can",
		model = 331512,
		text = {
			en = "Empty Kaja'Cola Can",
			de = "Leere Kaja'Cola-Dose",
			es = "Lata de Kaja'Cola vacía",
			fr = "Canette de Kaja’Cola vide",
			it = "Lattina Vuota di Kaja'Cola",
			mx = "Lata de Kaja'Cola vacía",
			pt = "Lata Vazia de Jaka'Cola",
			ru = "Пустая банка из-под \"Каджа-Колы\"",
			ko = "빈 카자콜라 깡통",
			cn = "空卡亚可乐罐",
			tw = "卡迦可樂空罐",
		},
	},
	[465294] = {
		readable = "Antonidas' Introduction to Arcane Magic",
		model = 985165,
		text = {
			en = "Antonidas' Introduction to Arcane Magic",
			de = "Antonidas' Einführung zu arkaner Magie",
			es = "Introducción a la magia Arcana de Antonidas",
			fr = "Introduction à la magie des arcanes, par Antonidas",
			it = "Introduzione alla Magia Arcana di Antonidas",
			mx = "Introducción de Antonidas a la magia arcana",
			pt = "Introdução à Magia Arcana de Antônidas",
			ru = "\"Введение в искусство магии\" Антонидаса",
			ko = "안토니다스의 비전 마법 개론서",
			cn = "安东尼达斯的奥术魔法导论",
			tw = "安東尼達斯的秘法魔法初解",
		},
	},
	[465295] = {
		readable = "Medivh's Karazhan Schematics",
		model = 4198213,
		text = {
			en = "Medivh's Karazhan Schematics",
			de = "Medivhs Baupläne von Karazhan",
			es = "Esquemas de Karazhan de Medivh",
			fr = "Plans de Karazhan, par Medivh",
			it = "Schemi di Karazhan di Medivh",
			mx = "Esquema de Karazhan de Medivh",
			pt = "Diagrama de Karazhan de Medivh",
			ru = "\"Чертежи Каражана\" Медива",
			ko = "메디브의 카라잔 청사진",
			cn = "麦迪文的卡拉赞示意图",
			tw = "麥迪文的卡拉贊結構圖",
		},
	},
	[465300] = {
		readable = "Thalen Songweaver's Notes",
		model = 1005457,
		text = {
			en = "Thalen Songweaver's Notes",
			de = "Thalen Sangwebers Notizen",
			es = "Notas de Thalen Tejecanto",
			fr = "Notes de Thalen Tissechant",
			it = "Appunti di Thalen Tessicanto",
			mx = "Notas de Thalen Tejecanto",
			pt = "Anotações de Thalen Tececanto",
			ru = "Записи Талена Созвучие Песни",
			ko = "탈렌 송위버의 기록",
			cn = "萨伦·织歌者的笔记",
			tw = "塔倫‧織歌者的筆記",
		},
	},
	[475284] = {
		readable = "Earthen Prototype",
		model = 5205857,
		text = {
			en = "Earthen Prototype",
			de = "Irdener Prototyp",
			es = "Prototipo terráneo",
			fr = "Prototype terrestre",
			it = "Prototipo dei Terrigeni",
			mx = "Prototipo terráneo",
			pt = "Protótipo Terrano",
			ru = "Прототип земельника",
			ko = "토석인 시제품",
			cn = "土灵原型装置",
			tw = "土靈原型機",
		},
	},
	[475286] = {
		readable = "Overcharged Battery",
		model = 2736566,
		text = {
			en = "Overcharged Battery",
			de = "Überladene Batterie",
			es = "Batería sobrecargada",
			fr = "Batterie surchargée",
			it = "Batteria Sovraccarica",
			mx = "Batería sobrecargada",
			pt = "Bateria Sobrecarregada",
			ru = "Перегруженная батарея",
			ko = "과충전된 전지",
			cn = "超充能电池",
			tw = "超載的電池",
		},
	},
	[487825] = {
		readable = "Ruffled Pages",
		model = 936429,
		text = {
			en = "Ruffled Pages",
			de = "Zerknitterte Seiten",
			es = "Páginas arrugadas",
			fr = "Pages froissées",
			it = "Pagine Accartocciate",
			mx = "Páginas arrugadas",
			pt = "Páginas Amarrotadas",
			ru = "Помятые страницы",
			ko = "주름진 종이",
			cn = "起皱的纸页",
			tw = "弄皺的書頁",
		},
	},
	[493375] = {
		readable = "Rune-Sealed Coffer",
		model = 1402270,
		text = {
			en = "Rune-Sealed Coffer",
			de = "Runenversiegelte Kassette",
			es = "Arca sellada con runas",
			fr = "Coffre scellé par des runes",
			it = "Scrigno con Sigillo Runico",
			mx = "Cofre sellado con runas",
			pt = "Cofre Selado com Runas",
			ru = "Запечатанный рунами ящик",
			ko = "룬봉인 궤짝",
			cn = "符文封印的宝匣",
			tw = "符文封印寶庫",
		},
	},
	[494923] = {
		readable = "Tattered Journal",
		model = 4337371,
		text = {
			en = "Tattered Journal",
			de = "Zerlumptes Tagebuch",
			es = "Diario ajado",
			fr = "Journal en lambeaux",
			it = "Diario Lacero",
			mx = "Diario andrajoso",
			pt = "Diário em Frangalhos",
			ru = "Изорванный дневник",
			ko = "너덜너덜한 일지",
			cn = "破烂的日志",
			tw = "殘破的日記",
		},
	},
	[499127] = {
		readable = "Runemarked Coffer",
		model = 1402264,
		text = {
			en = "Runemarked Coffer",
			de = "Runenmarkierte Kassette",
			es = "Cofre marcado con runas",
			fr = "Coffre marqué de runes",
			it = "Scrigno con Marchi Runici",
			mx = "Arca con marcas rúnicas",
			pt = "Cofre Marcado com Runas",
			ru = "Покрытый рунами ящик",
			ko = "룬표식 궤짝",
			cn = "符文标记宝匣",
			tw = "紋刻寶庫",
		},
	},
	[499443] = {
		readable = "Faded Journal Page",
		model = 3978479,
		text = {
			en = "Faded Journal Page",
			de = "Verblasste Tagebuchseite",
			es = "Página de diario borrosa",
			fr = "Page de journal estompée",
			it = "Pagina di Diario Sbiadita",
			mx = "Página de diario desgastada",
			pt = "Página de Diário Esmaecida",
			ru = "Выцветшая страница с записями",
			ko = "색 바랜 일지 책장",
			cn = "褪色的日志书页",
			tw = "褪色的日記書頁",
		},
	},
	[499620] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			de = "Runenverzierte Sturmtruhe",
			es = "Alijo de tormenta con runas",
			fr = "Cache de la tempête runique",
			it = "Cassa della Tempesta Runica",
			mx = "Alijo tormentoso rúnico",
			pt = "Baú da Tempestade Rúnico",
			ru = "Рунный сундук бурь",
			ko = "룬새김 폭풍 보관함",
			cn = "符文风暴宝箱",
			tw = "符文風暴儲藏箱",
		},
	},
	[499862] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			de = "Runenverzierte Sturmtruhe",
			es = "Alijo de tormenta con runas",
			fr = "Cache de la tempête runique",
			it = "Cassa della Tempesta Runica",
			mx = "Alijo tormentoso rúnico",
			pt = "Baú da Tempestade Rúnico",
			ru = "Рунный сундук бурь",
			ko = "룬새김 폭풍 보관함",
			cn = "符文风暴宝箱",
			tw = "符文風暴儲藏箱",
		},
	},
	[499863] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			de = "Runenverzierte Sturmtruhe",
			es = "Alijo de tormenta con runas",
			fr = "Cache de la tempête runique",
			it = "Cassa della Tempesta Runica",
			mx = "Alijo tormentoso rúnico",
			pt = "Baú da Tempestade Rúnico",
			ru = "Рунный сундук бурь",
			ko = "룬새김 폭풍 보관함",
			cn = "符文风暴宝箱",
			tw = "符文風暴儲藏箱",
		},
	},
	[500407] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			de = "Runenverzierte Sturmtruhe",
			es = "Alijo de tormenta con runas",
			fr = "Cache de la tempête runique",
			it = "Cassa della Tempesta Runica",
			mx = "Alijo tormentoso rúnico",
			pt = "Baú da Tempestade Rúnico",
			ru = "Рунный сундук бурь",
			ko = "룬새김 폭풍 보관함",
			cn = "符文风暴宝箱",
			tw = "符文風暴儲藏箱",
		},
	},
	[500688] = {
		readable = "Seafarer's Cache",
		model = 2123117,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			mx = "Alijo de navegante",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
	[500689] = {
		readable = "Seafarer's Cache",
		model = 219372,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			mx = "Alijo de navegante",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
	[500690] = {
		readable = "Seafarer's Cache",
		model = 446671,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			mx = "Alijo de navegante",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
	[505503] = {
		readable = "Ashvane Issued Workboots",
		model = 3718225,
		text = {
			en = "Ashvane Issued Workboots",
			de = "Arbeitsstiefel nach Aschenwindauftrag",
			es = "Botas de trabajo reglamentarias de Gobernalle",
			fr = "Bottes de travail réglementaires corsandres",
			it = "Stivali da Lavoro dei Bracescura",
			mx = "Botas de trabajo de calidad Aspafresno",
			pt = "Coturnos Lançados pela Grimpagris",
			ru = "Эшвейнские рабочие сапоги",
			ko = "애쉬베인 제식 작업화",
			cn = "艾什凡工作靴",
			tw = "艾胥凡分發的工作靴",
		},
	},
})
do ObjectDB[objectID] = objectData; end
