local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[429765] = {
		readable = "Forgotten Chest", --This object appears to have not been released outside the PTR and has no language translation or items linked to it, please test.
		model = 2123117,
		text = {
			en = "Forgotten Chest",
			es = "Forgotten Chest",
			de = "Forgotten Chest",
			fr = "Forgotten Chest",
			it = "Forgotten Chest",
			pt = "Forgotten Chest",
			ru = "Forgotten Chest",
			ko = "Forgotten Chest",
			cn = "Forgotten Chest",
		},
	},
	[430341] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			es = "Remanente radiante",
			mx = "Remanente radiante",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
			tw = "輻光殘骸",
		},
	},
	[434285] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			es = "Remanente radiante",
			mx = "Remanente radiante",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
			tw = "輻光殘骸",
		},
	},
	[434924] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			es = "Remanente radiante",
			mx = "Remanente radiante",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
			tw = "輻光殘骸",
		},
	},
	[454021] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			es = "Remanente radiante",
			mx = "Remanente radiante",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
			tw = "輻光殘骸",
		},
	},
	[454023] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			es = "Remanente radiante",
			mx = "Remanente radiante",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
			tw = "輻光殘骸",
		},
	},
	[454024] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			es = "Remanente radiante",
			mx = "Remanente radiante",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
			tw = "輻光殘骸",
		},
	},
})
do ObjectDB[objectID] = objectData; end
