local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[411744] = {
		readable = "Barrel of Wine",
		model = 4220170,
		text = {
			en = "Barrel of Wine",
			es = "Barrel of Wine",
			de = "Barrel of Wine",
			fr = "Barrel of Wine",
			it = "Barrel of Wine",
			pt = "Barrel of Wine",
			ru = "Barrel of Wine",
			ko = "Barrel of Wine",
			cn = "Barrel of Wine",
		},
	},
	[465646] = {
		readable = "Draconic Trophy",
		text = {
			en = "Draconic Trophy",
			es = "Draconic Trophy",
			de = "Draconic Trophy",
			fr = "Draconic Trophy",
			it = "Draconic Trophy",
			pt = "Draconic Trophy",
			ru = "Draconic Trophy",
			ko = "Draconic Trophy",
			cn = "Draconic Trophy",
		},
	},
	[465672] = {
		readable = "Gleaming Stonehead's Dented Armor",
		model = 5890942,
		text = {
			en = "Gleaming Stonehead's Dented Armor",
			es = "Gleaming Stonehead's Dented Armor",
			de = "Gleaming Stonehead's Dented Armor",
			fr = "Gleaming Stonehead's Dented Armor",
			it = "Gleaming Stonehead's Dented Armor",
			pt = "Gleaming Stonehead's Dented Armor",
			ru = "Gleaming Stonehead's Dented Armor",
			ko = "Gleaming Stonehead's Dented Armor",
			cn = "Gleaming Stonehead's Dented Armor",
		},
	},
	[465675] = {
		readable = "Rusting Clanker",
		model = 893080,
		text = {
			en = "Rusting Clanker",
			es = "Rusting Clanker",
			de = "Rusting Clanker",
			fr = "Rusting Clanker",
			it = "Rusting Clanker",
			pt = "Rusting Clanker",
			ru = "Rusting Clanker",
			ko = "Rusting Clanker",
			cn = "Rusting Clanker",
		},
	},
	[465679] = {
		readable = "Questing Beast's Skull",
		text = {
			en = "Questing Beast's Skull",
			es = "Questing Beast's Skull",
			de = "Questing Beast's Skull",
			fr = "Questing Beast's Skull",
			it = "Questing Beast's Skull",
			pt = "Questing Beast's Skull",
			ru = "Questing Beast's Skull",
			ko = "Questing Beast's Skull",
			cn = "Questing Beast's Skull",
		},
	},
	[504669] = {
		readable = "Mouthwash Bottle",
		text = {
			en = "Mouthwash Bottle",
			es = "Mouthwash Bottle",
			de = "Mouthwash Bottle",
			fr = "Mouthwash Bottle",
			it = "Mouthwash Bottle",
			pt = "Mouthwash Bottle",
			ru = "Mouthwash Bottle",
			ko = "Mouthwash Bottle",
			cn = "Mouthwash Bottle",
		},
	},
	[504670] = {
		readable = "Leftover Food",
		text = {
			en = "Leftover Food",
			es = "Leftover Food",
			de = "Leftover Food",
			fr = "Leftover Food",
			it = "Leftover Food",
			pt = "Leftover Food",
			ru = "Leftover Food",
			ko = "Leftover Food",
			cn = "Leftover Food",
		},
	},
})
do ObjectDB[objectID] = objectData; end