local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[474102] = {
		readable = "Ellie",
		model = 903883,
		text = {
			en = "Ellie",
			es = "Ellie",
			mx = "Ellie",
			de = "Ellie",
			fr = "Ellie",
			it = "Ellie",
			pt = "Ellie",
			ru = "Ellie",
			ko = "Ellie",
			cn = "Ellie",
			tw = "Ellie",
		},
	},
	[474113] = {
		readable = "Barrel of Tar",
		model = 4198210,
		text = {
			en = "Barrel of Tar",
			es = "Barrel of Tar",
			mx = "Barrel of Tar",
			de = "Barrel of Tar",
			fr = "Barrel of Tar",
			it = "Barrel of Tar",
			pt = "Barrel of Tar",
			ru = "Barrel of Tar",
			ko = "Barrel of Tar",
			cn = "Barrel of Tar",
			tw = "Barrel of Tar",
		},
	},
	[475190] = {
		readable = "Supply Crate",
		model = 2261922,
		text = {
			en = "Supply Crate",
			es = "Supply Crate",
			mx = "Supply Crate",
			de = "Supply Crate",
			fr = "Supply Crate",
			it = "Supply Crate",
			pt = "Supply Crate",
			ru = "Supply Crate",
			ko = "Supply Crate",
			cn = "Supply Crate",
			tw = "Supply Crate",
		},
	},
	[477880] = {
		readable = "Suspicious Dirt",
		model = 4370753,
		text = {
			en = "Suspicious Dirt",
			es = "Suspicious Dirt",
			mx = "Suspicious Dirt",
			de = "Suspicious Dirt",
			fr = "Suspicious Dirt",
			it = "Suspicious Dirt",
			pt = "Suspicious Dirt",
			ru = "Suspicious Dirt",
			ko = "Suspicious Dirt",
			cn = "Suspicious Dirt",
			tw = "Suspicious Dirt",
		},
	},
	[477883] = {
		readable = "Orcish Axe",
		text = {
			en = "Orcish Axe",
			es = "Orcish Axe",
			mx = "Orcish Axe",
			de = "Orcish Axe",
			fr = "Orcish Axe",
			it = "Orcish Axe",
			pt = "Orcish Axe",
			ru = "Orcish Axe",
			ko = "Orcish Axe",
			cn = "Orcish Axe",
			tw = "Orcish Axe",
		},
	},
	[478195] = {
		readable = "Red Dawn Oaths of Loyalty",
		model = 2026834,
		text = {
			en = "Red Dawn Oaths of Loyalty",
			es = "Red Dawn Oaths of Loyalty",
			mx = "Red Dawn Oaths of Loyalty",
			de = "Red Dawn Oaths of Loyalty",
			fr = "Red Dawn Oaths of Loyalty",
			it = "Red Dawn Oaths of Loyalty",
			pt = "Red Dawn Oaths of Loyalty",
			ru = "Red Dawn Oaths of Loyalty",
			ko = "Red Dawn Oaths of Loyalty",
			cn = "Red Dawn Oaths of Loyalty",
			tw = "Red Dawn Oaths of Loyalty",
		},
	},
	[478198] = {
		readable = "Red Dawn Propaganda",
		model = 5334703,
		text = {
			en = "Red Dawn Propaganda",
			es = "Red Dawn Propaganda",
			mx = "Red Dawn Propaganda",
			de = "Red Dawn Propaganda",
			fr = "Red Dawn Propaganda",
			it = "Red Dawn Propaganda",
			pt = "Red Dawn Propaganda",
			ru = "Red Dawn Propaganda",
			ko = "Red Dawn Propaganda",
			cn = "Red Dawn Propaganda",
			tw = "Red Dawn Propaganda",
		},
	},
	[478199] = {
		readable = "Red Dawn Propaganda",
		model = 5334703,
		text = {
			en = "Red Dawn Propaganda",
			es = "Red Dawn Propaganda",
			mx = "Red Dawn Propaganda",
			de = "Red Dawn Propaganda",
			fr = "Red Dawn Propaganda",
			it = "Red Dawn Propaganda",
			pt = "Red Dawn Propaganda",
			ru = "Red Dawn Propaganda",
			ko = "Red Dawn Propaganda",
			cn = "Red Dawn Propaganda",
			tw = "Red Dawn Propaganda",
		},
	},
	[478202] = {
		readable = "Red Dawn Propaganda",
		model = 5334703,
		text = {
			en = "Red Dawn Propaganda",
			es = "Red Dawn Propaganda",
			mx = "Red Dawn Propaganda",
			de = "Red Dawn Propaganda",
			fr = "Red Dawn Propaganda",
			it = "Red Dawn Propaganda",
			pt = "Red Dawn Propaganda",
			ru = "Red Dawn Propaganda",
			ko = "Red Dawn Propaganda",
			cn = "Red Dawn Propaganda",
			tw = "Red Dawn Propaganda",
		},
	},
	[478203] = {
		readable = "Barracks Prison Key",
		model = 970206,
		text = {
			en = "Barracks Prison Key",
			es = "Barracks Prison Key",
			mx = "Barracks Prison Key",
			de = "Barracks Prison Key",
			fr = "Barracks Prison Key",
			it = "Barracks Prison Key",
			pt = "Barracks Prison Key",
			ru = "Barracks Prison Key",
			ko = "Barracks Prison Key",
			cn = "Barracks Prison Key",
			tw = "Barracks Prison Key",
		},
	},
	[503465] = {
		readable = "Barrels of Tar",
		model = 4198210,
		text = {
			en = "Barrels of Tar",
			es = "Barrels of Tar",
			mx = "Barrels of Tar",
			de = "Barrels of Tar",
			fr = "Barrels of Tar",
			it = "Barrels of Tar",
			pt = "Barrels of Tar",
			ru = "Barrels of Tar",
			ko = "Barrels of Tar",
			cn = "Barrels of Tar",
			tw = "Barrels of Tar",
		},
	},
})
do ObjectDB[objectID] = objectData; end