local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[421150] = {
		readable = "Carved Eye",
		model = 204046,
		text = {
			en = "Carved Eye",
			de = "Geschnitztes Auge",
			es = "Ojo tallado",
			mx = "Ojo tallado",
			fr = "Œil gravé",
			it = "Occhio Intagliato",
			pt = "Olho Entalhado",
			ru = "Резной глаз",
			ko = "도려낸 눈알",
			cn = "凿刻之眼",
			tw = "雕刻之眼",
		},
	},
	[421151] = {
		readable = "Carved Eye",
		model = 204043,
		text = {
			en = "Carved Eye",
			de = "Geschnitztes Auge",
			es = "Ojo tallado",
			mx = "Ojo tallado",
			fr = "Œil gravé",
			it = "Occhio Intagliato",
			pt = "Olho Entalhado",
			ru = "Резной глаз",
			ko = "도려낸 눈알",
			cn = "凿刻之眼",
			tw = "雕刻之眼",
		},
	},
	[421152] = {
		readable = "Carved Eye",
		model = 204053,
		text = {
			en = "Carved Eye",
			de = "Geschnitztes Auge",
			es = "Ojo tallado",
			mx = "Ojo tallado",
			fr = "Œil gravé",
			it = "Occhio Intagliato",
			pt = "Olho Entalhado",
			ru = "Резной глаз",
			ko = "도려낸 눈알",
			cn = "凿刻之眼",
			tw = "雕刻之眼",
		},
	},
	[421153] = {
		readable = "Carved Eye",
		model = 204053,
		text = {
			en = "Carved Eye",
			de = "Geschnitztes Auge",
			es = "Ojo tallado",
			mx = "Ojo tallado",
			fr = "Œil gravé",
			it = "Occhio Intagliato",
			pt = "Olho Entalhado",
			ru = "Резной глаз",
			ko = "도려낸 눈알",
			cn = "凿刻之眼",
			tw = "雕刻之眼",
		},
	},
})
do ObjectDB[objectID] = objectData; end
