local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[474822] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			de = "Runenverzierte Sturmtruhe",
			es = "Alijo de tormenta con runas",
			mx = "Alijo tormentoso rúnico",
			fr = "Cache de la tempête runique",
			it = "Cassa della Tempesta Runica",
			pt = "Baú da Tempestade Rúnico",
			ru = "Рунный сундук бурь",
			ko = "룬새김 폭풍 보관함",
			cn = "符文风暴宝箱",
			tw = "符文風暴儲藏箱",
		},
	},
	[494499] = {
		readable = "Seafarer's Cache",
		model = 2123117,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			mx = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
	[500682] = {
		readable = "Seafarer's Cache",
		model = 219372,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			mx = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
	[500683] = {
		readable = "Seafarer's Cache",
		model = 446671,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			mx = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
	[500684] = {
		readable = "Seafarer's Cache",
		model = 446673,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			mx = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
	[500685] = {
		readable = "Seafarer's Cache",
		model = 1706189,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			mx = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
	[500686] = {
		readable = "Seafarer's Cache",
		model = 5771275,
		text = {
			en = "Seafarer's Cache",
			de = "Schatz des Seefahrers",
			es = "Alijo de navegante",
			mx = "Alijo de navegante",
			fr = "Cache de marin",
			it = "Cassa del Marinaio",
			pt = "Baú do Marinheiro",
			ru = "Сундук мореплавателя",
			ko = "뱃사람의 보관함",
			cn = "海员的箱子",
			tw = "水手的儲物箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end
