local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[182030] = {
		readable = "Inert Peculiar Key",
		model = 970204,
		text = {
			en = "Inert Peculiar Key",
			de = "Inaktiver seltsamer Schlüssel",
			es = "Llave peculiar inerte",
			fr = "Clé étrange inerte",
			it = "Chiave Peculiare Inerte",
			mx = "Llave peculiar inerte",
			pt = "Chave Peculiar Inerte",
			ru = "Необычный инертный ключ",
			ko = "비활성화된 특이한 열쇠",
			cn = "失能奇异钥匙",
			tw = "惰性奇特鑰匙",
		},
	},
	[455310] = {
		readable = "Hear Historic Tales at the Storyteller Stage!",
		model = 936419,
		text = {
			en = "Hear Historic Tales at the Storyteller Stage!",
			de = "Lauscht historischen Geschichten bei der Geschichtenbühne!",
			es = "¡Escucha cuentos históricos en el escenario del narrador!",
			fr = "Écoutez des récits historiques à la scène du Conteur !",
			it = "Ascoltate le Storie sul Palco del Cantastorie!",
			mx = "¡Escucha relatos históricos en el escenario del narrador!",
			pt = "Ouça Contos Históricos no Palco das Histórias!",
			ru = "Послушайте исторические рассказы у \"Сцены сказителя\"!",
			ko = "이야기꾼 무대에서 역사 이야기를 들어보세요!",
			cn = "快来说书人大舞台，听说书人讲述历史故事！",
			tw = "在說書人舞台聽歷史故事！",
		},
	},
	[455761] = {
		readable = "Gerald",
		model = 196999,
		text = {
			en = "Gerald",
			es = "Gerald",
			de = "Gerald",
			fr = "Gérald",
			it = "Gerald",
			mx = "Gerald",
			pt = "Geraldo",
			ru = "Джеральд",
			ko = "제럴드",
			cn = "吉拉德",
			tw = "格拉德",
		},
	},
	[455768] = {
		readable = "Soggy Celebration Crate",
		model = 5282318,
		text = {
			en = "Soggy Celebration Crate",
			de = "Triefende Feierkiste",
			es = "Cajón de celebración empapado",
			fr = "Caisse d’anniversaire trempée",
			it = "Soggy Celebration Crate",
			mx = "Cajón de festejo mojado",
			pt = "Caixote de Celebração Encharcado",
			ru = "Мокрый ящик с праздника",
			ko = "축축한 기념 상자",
			cn = "泡烂的庆典箱子",
			tw = "濕透的節慶木箱",
		},
	},
	[456767] = {
		readable = "Red Hair",
		model = 970251,
		text = {
			en = "Red Hair",
			de = "Rotes Haar",
			es = "Pelo rojo",
			fr = "Cheveux roux",
			it = "Pelo Rosso",
			mx = "Pelo rojo",
			pt = "Cabelo Ruivo",
			ru = "Рыжие волосы",
			ko = "붉은색 털",
			cn = "红色毛发",
			tw = "紅色毛髮",
		},
	},
	[456820] = {
		readable = "Strange Torch",
		model = 167130,
		text = {
			en = "Strange Torch",
			de = "Merkwürdige Fackel",
			es = "Antorcha extraña",
			fr = "Torche étrange",
			it = "Strana Torcia",
			mx = "Antorcha extraña",
			pt = "Tocha Estranha",
			ru = "Странный факел",
			ko = "이상한 횃불",
			cn = "奇特火把",
			tw = "怪異火炬",
		},
	},
	[457025] = {
		readable = "Pre-Calibrated Goblin Transport Vessel",
		model = 315765,
		text = {
			en = "Pre-Calibrated Goblin Transport Vessel",
			de = "Vorkalibriertes Goblintransportschiff",
			es = "Transportador goblin precalibrado",
			fr = "Vaisseau de transport gobelin précalibré",
			it = "Pre-Calibrated Goblin Transport Vessel",
			mx = "Nave de transporte goblin precalibrada",
			pt = "Pre-Calibrated Goblin Transport Vessel",
			ru = "Откалиброванный транспортный корабль гоблинов",
			ko = "사전 보정된 고블린 수송선",
			cn = "提前校准的地精运输船",
			tw = "預先校準的哥布林運輸船",
		},
	},
	[457156] = {
		readable = "Torn Note",
		model = 936413,
		text = {
			en = "Torn Note",
			de = "Zerrissene Notiz",
			es = "Nota rota",
			fr = "Note déchirée",
			it = "Nota Strappata",
			mx = "Nota rota",
			pt = "Bilhete Rasgado",
			ru = "Порванная записка",
			ko = "찢어진 쪽지",
			cn = "撕碎的笔记",
			tw = "破損的便箋",
		},
	},
	[457160] = {
		readable = "Torn Note",
		model = 936413,
		text = {
			en = "Torn Note",
			de = "Zerrissene Notiz",
			es = "Nota rota",
			fr = "Note déchirée",
			it = "Nota Strappata",
			mx = "Nota rota",
			pt = "Bilhete Rasgado",
			ru = "Порванная записка",
			ko = "찢어진 쪽지",
			cn = "撕碎的笔记",
			tw = "破損的便箋",
		},
	},
	[457161] = {
		readable = "Torn Note",
		model = 936413,
		text = {
			en = "Torn Note",
			de = "Zerrissene Notiz",
			es = "Nota rota",
			fr = "Note déchirée",
			it = "Nota Strappata",
			mx = "Nota rota",
			pt = "Bilhete Rasgado",
			ru = "Порванная записка",
			ko = "찢어진 쪽지",
			cn = "撕碎的笔记",
			tw = "破損的便箋",
		},
	},
	[457197] = {
		readable = "Mounted Spyglass",
		model = 4496829,
		text = {
			en = "Mounted Spyglass",
			de = "Montiertes Fernglas",
			es = "Catalejo montado",
			fr = "Longue-vue montée",
			it = "Cannocchiale Montato",
			mx = "Catalejo con montura",
			pt = "Luneta Montada",
			ru = "Закрепленная подзорная труба",
			ko = "거치식 망원경",
			cn = "架设的望远镜",
			tw = "架設好的望遠鏡",
		},
	},
	[459333] = {
		readable = "Jeweled Eye",
		model = 244062,
		text = {
			en = "Jeweled Eye",
			de = "Juwelenbesetztes Auge",
			es = "Ojo enjoyado",
			fr = "Œil orné de joyaux",
			it = "Occhio Ingioiellato",
			mx = "Ojo enjoyado",
			pt = "Olho Cravejado",
			ru = "Алмазный глаз",
			ko = "보석 박힌 눈",
			cn = "宝石之眼",
			tw = "寶石之眼",
		},
	},
	[459368] = {
		readable = "Half-Buried Chest",
		model = 4323481,
		text = {
			en = "Half-Buried Chest",
			de = "Halb vergrabene Truhe",
			es = "Cofre semienterrado",
			fr = "Coffre partiellement enterré",
			it = "Cassa Mezza Sepolta",
			mx = "Cofre medio enterrado",
			pt = "Baú Semienterrado",
			ru = "Полузакопанный сундук",
			ko = "반쯤 묻힌 상자",
			cn = "半埋的宝箱",
			tw = "半埋的箱子",
		},
	},
	[463653] = {
		readable = "Dirt-Caked Celebration Crate",
		model = 5282318,
		text = {
			en = "Dirt-Caked Celebration Crate",
			de = "Dreckverkrustete Feierkiste",
			es = "Cajón de celebración cubierto de tierra",
			fr = "Caisse d’anniversaire couverte de poussière",
			it = "Dirt-Caked Celebration Crate",
			mx = "Cajón de festejo cubierto de tierra",
			pt = "Dirt-Caked Celebration Crate",
			ru = "Грязный ящик с праздника",
			ko = "Dirt-Caked Celebration Crate",
			cn = "沾满泥土的庆典箱子",
			tw = "沾滿泥土的節慶木箱",
		},
	},
	[465161] = {
		readable = "Water-Resistant Receipt of Sale",
		model = 936411,
		text = {
			en = "Water-Resistant Receipt of Sale",
			de = "Wasserfester Verkaufsbeleg",
			es = "Recibo impermeable",
			fr = "Récépissé de vente imperméable",
			it = "Water-Resistant Receipt of Sale",
			mx = "Recibo de venta resistente al agua",
			pt = "Water-Resistant Receipt of Sale",
			ru = "Водонепроницаемый товарный чек",
			ko = "방수 판매 영수증",
			cn = "防水的销售收据",
			tw = "防水售貨收據",
		},
	},
})
do ObjectDB[objectID] = objectData; end
