local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[527398] = {
		readable = "Suspicious Document",
		model = 5502807,
		text = {
			en = "Suspicious Document",
			es = "[Suspicious Document]",
			mx = "[Suspicious Document]",
			de = "[Suspicious Document]",
			fr = "[Suspicious Document]",
			it = "[Suspicious Document]",
			pt = "[Suspicious Document]",
			ru = "[Suspicious Document]",
			ko = "[Suspicious Document]",
			cn = "[Suspicious Document]",
			tw = "[Suspicious Document]",
		},
	},
	[527409] = {
		readable = "Suspicious Document",
		model = 5007027,
		text = {
			en = "Suspicious Document",
			es = "[Suspicious Document]",
			mx = "[Suspicious Document]",
			de = "[Suspicious Document]",
			fr = "[Suspicious Document]",
			it = "[Suspicious Document]",
			pt = "[Suspicious Document]",
			ru = "[Suspicious Document]",
			ko = "[Suspicious Document]",
			cn = "[Suspicious Document]",
			tw = "[Suspicious Document]",
		},
	},
	[527413] = {
		readable = "Suspicious Document",
		model = 5502807,
		text = {
			en = "Suspicious Document",
			es = "[Suspicious Document]",
			mx = "[Suspicious Document]",
			de = "[Suspicious Document]",
			fr = "[Suspicious Document]",
			it = "[Suspicious Document]",
			pt = "[Suspicious Document]",
			ru = "[Suspicious Document]",
			ko = "[Suspicious Document]",
			cn = "[Suspicious Document]",
			tw = "[Suspicious Document]",
		},
	},
	[527415] = {
		readable = "Suspicious Document",
		model = 5502807,
		text = {
			en = "Suspicious Document",
			es = "[Suspicious Document]",
			mx = "[Suspicious Document]",
			de = "[Suspicious Document]",
			fr = "[Suspicious Document]",
			it = "[Suspicious Document]",
			pt = "[Suspicious Document]",
			ru = "[Suspicious Document]",
			ko = "[Suspicious Document]",
			cn = "[Suspicious Document]",
			tw = "[Suspicious Document]",
		},
	},
	[527416] = {
		readable = "Suspicious Document",
		model = 5007027,
		text = {
			en = "Suspicious Document",
			es = "[Suspicious Document]",
			mx = "[Suspicious Document]",
			de = "[Suspicious Document]",
			fr = "[Suspicious Document]",
			it = "[Suspicious Document]",
			pt = "[Suspicious Document]",
			ru = "[Suspicious Document]",
			ko = "[Suspicious Document]",
			cn = "[Suspicious Document]",
			tw = "[Suspicious Document]",
		},
	},
})
do ObjectDB[objectID] = objectData; end