local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[467522] = {
		readable = "Nether Reader",
		model = 4094671,
		text = {
			en = "Nether Reader",
			es = "Nether Reader",
			mx = "Nether Reader",
			de = "Nether Reader",
			fr = "Nether Reader",
			it = "Nether Reader",
			pt = "Nether Reader",
			ru = "Nether Reader",
			ko = "Nether Reader",
			cn = "Nether Reader",
			tw = "Nether Reader",
		},
	},
	[500744] = {
		readable = "Rak-ush Mushroom",
		model = 5456613,
		text = {
			en = "Rak-ush Mushroom",
			es = "Rak-ush Mushroom",
			mx = "Rak-ush Mushroom",
			de = "Rak-ush Mushroom",
			fr = "Rak-ush Mushroom",
			it = "Rak-ush Mushroom",
			pt = "Rak-ush Mushroom",
			ru = "Rak-ush Mushroom",
			ko = "Rak-ush Mushroom",
			cn = "Rak-ush Mushroom",
			tw = "Rak-ush Mushroom",
		},
	},
	[500779] = {
		readable = "Voshshroom",
		text = {
			en = "Voshshroom",
			es = "Voshshroom",
			mx = "Voshshroom",
			de = "Voshshroom",
			fr = "Voshshroom",
			it = "Voshshroom",
			pt = "Voshshroom",
			ru = "Voshshroom",
			ko = "Voshshroom",
			cn = "Voshshroom",
			tw = "Voshshroom",
		},
	},
	[502399] = {
		readable = "Pile of Bones",
		model = 4525136,
		text = {
			en = "Pile of Bones",
			es = "Pile of Bones",
			mx = "Pile of Bones",
			de = "Pile of Bones",
			fr = "Pile of Bones",
			it = "Pile of Bones",
			pt = "Pile of Bones",
			ru = "Pile of Bones",
			ko = "Pile of Bones",
			cn = "Pile of Bones",
			tw = "Pile of Bones",
		},
	},
	[504075] = {
		readable = "Nether Reader",
		model = 4094671,
		text = {
			en = "Nether Reader",
			es = "Nether Reader",
			mx = "Nether Reader",
			de = "Nether Reader",
			fr = "Nether Reader",
			it = "Nether Reader",
			pt = "Nether Reader",
			ru = "Nether Reader",
			ko = "Nether Reader",
			cn = "Nether Reader",
			tw = "Nether Reader",
		},
	},
	[504181] = {
		readable = "Fallen Log",
		model = 5009014,
		text = {
			en = "Fallen Log",
			es = "Fallen Log",
			mx = "Fallen Log",
			de = "Fallen Log",
			fr = "Fallen Log",
			it = "Fallen Log",
			pt = "Fallen Log",
			ru = "Fallen Log",
			ko = "Fallen Log",
			cn = "Fallen Log",
			tw = "Fallen Log",
		},
	},
	[504191] = {
		readable = "Pile of Meat",
		model = 337607,
		text = {
			en = "Pile of Meat",
			es = "Pile of Meat",
			mx = "Pile of Meat",
			de = "Pile of Meat",
			fr = "Pile of Meat",
			it = "Pile of Meat",
			pt = "Pile of Meat",
			ru = "Pile of Meat",
			ko = "Pile of Meat",
			cn = "Pile of Meat",
			tw = "Pile of Meat",
		},
	},
	[517389] = {
		readable = "Zo'kita Fruit",
		model = 4495231,
		text = {
			en = "Zo'kita Fruit",
			es = "Zo'kita Fruit",
			mx = "Zo'kita Fruit",
			de = "Zo'kita Fruit",
			fr = "Zo'kita Fruit",
			it = "Zo'kita Fruit",
			pt = "Zo'kita Fruit",
			ru = "Zo'kita Fruit",
			ko = "Zo'kita Fruit",
			cn = "Zo'kita Fruit",
			tw = "Zo'kita Fruit",
		},
	},
	[517405] = {
		readable = "Tazavesh Trash",
		model = 3930675,
		text = {
			en = "Tazavesh Trash",
			es = "Tazavesh Trash",
			mx = "Tazavesh Trash",
			de = "Tazavesh Trash",
			fr = "Tazavesh Trash",
			it = "Tazavesh Trash",
			pt = "Tazavesh Trash",
			ru = "Tazavesh Trash",
			ko = "Tazavesh Trash",
			cn = "Tazavesh Trash",
			tw = "Tazavesh Trash",
		},
	},
	[517407] = {
		readable = "Tazavesh Trash",
		model = 3525443,
		text = {
			en = "Tazavesh Trash",
			es = "Tazavesh Trash",
			mx = "Tazavesh Trash",
			de = "Tazavesh Trash",
			fr = "Tazavesh Trash",
			it = "Tazavesh Trash",
			pt = "Tazavesh Trash",
			ru = "Tazavesh Trash",
			ko = "Tazavesh Trash",
			cn = "Tazavesh Trash",
			tw = "Tazavesh Trash",
		},
	},
	[517410] = {
		readable = "Tazavesh Trash",
		model = 3454694,
		text = {
			en = "Tazavesh Trash",
			es = "Tazavesh Trash",
			mx = "Tazavesh Trash",
			de = "Tazavesh Trash",
			fr = "Tazavesh Trash",
			it = "Tazavesh Trash",
			pt = "Tazavesh Trash",
			ru = "Tazavesh Trash",
			ko = "Tazavesh Trash",
			cn = "Tazavesh Trash",
			tw = "Tazavesh Trash",
		},
	},
	[519856] = {
		readable = "Stolen Veilshard",
		model = 244062,
		text = {
			en = "Stolen Veilshard",
			es = "Stolen Veilshard",
			mx = "Stolen Veilshard",
			de = "Stolen Veilshard",
			fr = "Stolen Veilshard",
			it = "Stolen Veilshard",
			pt = "Stolen Veilshard",
			ru = "Stolen Veilshard",
			ko = "Stolen Veilshard",
			cn = "Stolen Veilshard",
			tw = "Stolen Veilshard",
		},
	},
	[532317] = {
		readable = "Shadowtrade Imports",
		model = 5599766,
		text = {
			en = "Shadowtrade Imports",
			es = "Shadowtrade Imports",
			mx = "Shadowtrade Imports",
			de = "Shadowtrade Imports",
			fr = "Shadowtrade Imports",
			it = "Shadowtrade Imports",
			pt = "Shadowtrade Imports",
			ru = "Shadowtrade Imports",
			ko = "Shadowtrade Imports",
			cn = "Shadowtrade Imports",
			tw = "Shadowtrade Imports",
		},
	},
	[532318] = {
		readable = "Shadowtrade Imports",
		model = 4891997,
		text = {
			en = "Shadowtrade Imports",
			es = "Shadowtrade Imports",
			mx = "Shadowtrade Imports",
			de = "Shadowtrade Imports",
			fr = "Shadowtrade Imports",
			it = "Shadowtrade Imports",
			pt = "Shadowtrade Imports",
			ru = "Shadowtrade Imports",
			ko = "Shadowtrade Imports",
			cn = "Shadowtrade Imports",
			tw = "Shadowtrade Imports",
		},
	},
	[532321] = {
		readable = "Shadowtrade Imports",
		model = 3565798,
		text = {
			en = "Shadowtrade Imports",
			es = "Shadowtrade Imports",
			mx = "Shadowtrade Imports",
			de = "Shadowtrade Imports",
			fr = "Shadowtrade Imports",
			it = "Shadowtrade Imports",
			pt = "Shadowtrade Imports",
			ru = "Shadowtrade Imports",
			ko = "Shadowtrade Imports",
			cn = "Shadowtrade Imports",
			tw = "Shadowtrade Imports",
		},
	},
	[532322] = {
		readable = "Shadowtrade Imports",
		text = {
			en = "Shadowtrade Imports",
			es = "Shadowtrade Imports",
			mx = "Shadowtrade Imports",
			de = "Shadowtrade Imports",
			fr = "Shadowtrade Imports",
			it = "Shadowtrade Imports",
			pt = "Shadowtrade Imports",
			ru = "Shadowtrade Imports",
			ko = "Shadowtrade Imports",
			cn = "Shadowtrade Imports",
			tw = "Shadowtrade Imports",
		},
	},
	[532323] = {
		readable = "Shadowtrade Imports",
		text = {
			en = "Shadowtrade Imports",
			es = "Shadowtrade Imports",
			mx = "Shadowtrade Imports",
			de = "Shadowtrade Imports",
			fr = "Shadowtrade Imports",
			it = "Shadowtrade Imports",
			pt = "Shadowtrade Imports",
			ru = "Shadowtrade Imports",
			ko = "Shadowtrade Imports",
			cn = "Shadowtrade Imports",
			tw = "Shadowtrade Imports",
		},
	},
	[536867] = {
		readable = "Swoopwing Eggs",
		model = 4254405,
		text = {
			en = "Swoopwing Eggs",
			es = "Swoopwing Eggs",
			mx = "Swoopwing Eggs",
			de = "Swoopwing Eggs",
			fr = "Swoopwing Eggs",
			it = "Swoopwing Eggs",
			pt = "Swoopwing Eggs",
			ru = "Swoopwing Eggs",
			ko = "Swoopwing Eggs",
			cn = "Swoopwing Eggs",
			tw = "Swoopwing Eggs",
		},
	},
	[537690] = {
		readable = "Prosperity Pebble",
		model = 1318183,
		text = {
			en = "Prosperity Pebble",
			es = "Prosperity Pebble",
			mx = "Prosperity Pebble",
			de = "Prosperity Pebble",
			fr = "Prosperity Pebble",
			it = "Prosperity Pebble",
			pt = "Prosperity Pebble",
			ru = "Prosperity Pebble",
			ko = "Prosperity Pebble",
			cn = "Prosperity Pebble",
			tw = "Prosperity Pebble",
		},
	},
})
do ObjectDB[objectID] = objectData; end
