local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[478443] = {
		readable = "Mislaid Curiosity",
		model = 5100456,
		text = {
			en = "Mislaid Curiosity",
			de = "Verlegte Kuriosität",
			es = "Curiosidad extraviada",
			mx = "Curiosidad extraviada",
			fr = "Curiosité fourvoyée",
			it = "Curiosità Smarrita",
			pt = "Curiosidade Desviada",
			ru = "Потерянная вещица",
			ko = "어긋난 호기심",
			cn = "错放的奇珍",
			tw = "亂放的珍品",
		},
	},
	[503013] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			de = "Robuste Truhe",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			cn = "坚固宝箱",
			tw = "結實的箱子",
		},
	},
	[503868] = {
		readable = "Nemesis Strongbox",
		model = 2907352,
		text = {
			en = "Nemesis Strongbox",
			de = "Schließkassette der Nemesis",
			es = "Caja fuerte de némesis",
			mx = "Caja fuerte de némesis",
			fr = "Coffre-fort de Némésis",
			it = "Forziere della Nemesi",
			pt = "Caixa-forte da Nêmesis",
			ru = "Сейф заклятого врага",
			ko = "원수의 금고",
			cn = "宿敌保险箱",
			tw = "死敵保險箱",
		},
	},
	[503869] = {
		readable = "Nemesis Strongbox",
		model = 2907352,
		text = {
			en = "Nemesis Strongbox",
			de = "Schließkassette der Nemesis",
			es = "Caja fuerte de némesis",
			mx = "Caja fuerte de némesis",
			fr = "Coffre-fort de Némésis",
			it = "Forziere della Nemesi",
			pt = "Caixa-forte da Nêmesis",
			ru = "Сейф заклятого врага",
			ko = "원수의 금고",
			cn = "宿敌保险箱",
			tw = "死敵保險箱",
		},
	},
	[503871] = {
		readable = "Nemesis Strongbox",
		model = 2907352,
		text = {
			en = "Nemesis Strongbox",
			de = "Schließkassette der Nemesis",
			es = "Caja fuerte de némesis",
			mx = "Caja fuerte de némesis",
			fr = "Coffre-fort de Némésis",
			it = "Forziere della Nemesi",
			pt = "Caixa-forte da Nêmesis",
			ru = "Сейф заклятого врага",
			ko = "원수의 금고",
			cn = "宿敌保险箱",
			tw = "死敵保險箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end
