local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[477098] = {
		readable = "Bilge Rat Trunk",
		model = 942843,
		text = {
			en = "Bilge Rat Trunk",
			de = "Bilgerattentruhe",
			es = "Arcón de las Ratas de Pantoque",
			mx = "Baúl de rata de sentina",
			fr = "Malle des Soutaillons",
			it = "Baule dei Ratti di Sentina",
			pt = "Baú do Rato de Porão",
			ru = "Ларь братства Трюмных Крыс",
			ko = "항만의 시궁쥐단 사물함",
			cn = "水鼠帮行李箱",
			tw = "污鼠會箱子",
		},
	},
	[477248] = {
		readable = "Songs of the Siren",
		model = 198022,
		text = {
			en = "Songs of the Siren",
			de = "Lieder der Sirene",
			es = "Cantos de la sirena",
			mx = "Canciones de sirena",
			fr = "Chants de la sirène",
			it = "Canti della Sirena",
			pt = "Canções da Sirena",
			ru = "Песни сирены",
			ko = "세이렌의 노래",
			cn = "海妖冥曲",
			tw = "海妖之歌",
		},
	},
	[477366] = {
		readable = "Dat-Dat's Book Stash",
		model = 2123117,
		text = {
			en = "Dat-Dat's Book Stash",
			de = "Dat-Dats Bücherhort",
			es = "Biblioteca de Dat-Dat",
			mx = "Alijo de libros de Dingue Dingue",
			fr = "Réserve de livres de Dat-Dat",
			it = "Scorta di Libri di Dat-Dat",
			pt = "Acervo de Livros do Tantã",
			ru = "Тайник с книгами Дат-Дата",
			ko = "댓댓의 책 보관함",
			cn = "达特达特的藏书",
			tw = "達達的書籍儲藏箱",
		},
	},
	[477612] = {
		readable = "Siren Isle Manifest",
		model = 2459257,
		text = {
			en = "Siren Isle Manifest",
			de = "Manifest der Sireneninsel",
			es = "Manifiesto de la Isla de la Sirena",
			mx = "Manifiesto de la Isla de las Sirenas",
			fr = "Manifeste de l’île aux Sirènes",
			it = "Manifesto dell'Isola delle Sirene",
			pt = "Ilha das Sirenas Manifesta",
			ru = "Манифест острова Сирен",
			ko = "세이렌의 섬 목록",
			cn = "海妖岛舱单",
			tw = "海妖島貨物清單",
		},
	},
	[505510] = {
		readable = "Barnacle-Encrusted Chest",
		text = {
			en = "Barnacle-Encrusted Chest",
			de = "Seepockenverkrustete Truhe",
			es = "Cofre incrustado de percebes",
			mx = "Cofre incrustado de percebe",
			fr = "Coffre incrusté de bigorneaux",
			it = "Cassa Incrostata di Conchiglie",
			pt = "Baú Incrustado de Cracas",
			ru = "Покрытый ракушками сундук",
			ko = "따개비로 뒤덮인 상자",
			cn = "长满藤壶的宝箱",
			tw = "嵌滿藤壺的箱子",
		},
	},
	[507120] = {
		readable = "Ducky Friend",
		model = 4690953,
		text = {
			en = "Ducky Friend",
			de = "Knuddelente",
			es = "Amigo patito",
			mx = "Patito amigo",
			fr = "Copain canard",
			it = "Amico Anatroso",
			pt = "Patinho Amigo",
			ru = "Друг-утенок",
			ko = "오리 친구",
			cn = "宝贝朋友",
			tw = "小鴨朋友",
		},
	},
})
do ObjectDB[objectID] = objectData; end
