local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[529525] = {
		readable = "Light-Soaked Cleaver",
		text = {
			en = "Light-Soaked Cleaver",
			es = "Light-Soaked Cleaver",
			mx = "Light-Soaked Cleaver",
			de = "Light-Soaked Cleaver",
			fr = "Light-Soaked Cleaver",
			it = "Light-Soaked Cleaver",
			pt = "Light-Soaked Cleaver",
			ru = "Light-Soaked Cleaver",
			ko = "Light-Soaked Cleaver",
			cn = "Light-Soaked Cleaver",
			tw = "Light-Soaked Cleaver",
		},
	},
	[529533] = {
		readable = "Spear of Fallen Memories",
		text = {
			en = "Spear of Fallen Memories",
			es = "Spear of Fallen Memories",
			mx = "Spear of Fallen Memories",
			de = "Spear of Fallen Memories",
			fr = "Spear of Fallen Memories",
			it = "Spear of Fallen Memories",
			pt = "Spear of Fallen Memories",
			ru = "Spear of Fallen Memories",
			ko = "Spear of Fallen Memories",
			cn = "Spear of Fallen Memories",
			tw = "Spear of Fallen Memories",
		},
	},
	[529537] = {
		readable = "Efrat's Forgotten Bulwark",
		text = {
			en = "Efrat's Forgotten Bulwark",
			es = "Efrat's Forgotten Bulwark",
			mx = "Efrat's Forgotten Bulwark",
			de = "Efrat's Forgotten Bulwark",
			fr = "Efrat's Forgotten Bulwark",
			it = "Efrat's Forgotten Bulwark",
			pt = "Efrat's Forgotten Bulwark",
			ru = "Efrat's Forgotten Bulwark",
			ko = "Efrat's Forgotten Bulwark",
			cn = "Efrat's Forgotten Bulwark",
			tw = "Efrat's Forgotten Bulwark",
		},
	},
	[529591] = {
		readable = "Sufaadi Skiff Lantern",
		text = {
			en = "Sufaadi Skiff Lantern",
			es = "Sufaadi Skiff Lantern",
			mx = "Sufaadi Skiff Lantern",
			de = "Sufaadi Skiff Lantern",
			fr = "Sufaadi Skiff Lantern",
			it = "Sufaadi Skiff Lantern",
			pt = "Sufaadi Skiff Lantern",
			ru = "Sufaadi Skiff Lantern",
			ko = "Sufaadi Skiff Lantern",
			cn = "Sufaadi Skiff Lantern",
			tw = "Sufaadi Skiff Lantern",
		},
	},
	[529664] = {
		readable = "Shadowguard Crusher",
		text = {
			en = "Shadowguard Crusher",
			es = "Shadowguard Crusher",
			mx = "Shadowguard Crusher",
			de = "Shadowguard Crusher",
			fr = "Shadowguard Crusher",
			it = "Shadowguard Crusher",
			pt = "Shadowguard Crusher",
			ru = "Shadowguard Crusher",
			ko = "Shadowguard Crusher",
			cn = "Shadowguard Crusher",
			tw = "Shadowguard Crusher",
		},
	},
	[536065] = {
		readable = "Nuts and Bolts",
		model = 1842503,
		text = {
			en = "Nuts and Bolts",
			es = "Nuts and Bolts",
			mx = "Nuts and Bolts",
			de = "Nuts and Bolts",
			fr = "Nuts and Bolts",
			it = "Nuts and Bolts",
			pt = "Nuts and Bolts",
			ru = "Nuts and Bolts",
			ko = "Nuts and Bolts",
			cn = "Nuts and Bolts",
			tw = "Nuts and Bolts",
		},
	},
	[548001] = {
		readable = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
		text = {
			en = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			es = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			mx = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			de = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			fr = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			it = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			pt = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			ru = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			ko = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			cn = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
			tw = "P.O.S.T. Master's Prototype Parcel and Postage Presser",
		},
	},
	[548010] = {
		readable = "Phaseblade of the Void Marches",
		text = {
			en = "Phaseblade of the Void Marches",
			es = "Phaseblade of the Void Marches",
			mx = "Phaseblade of the Void Marches",
			de = "Phaseblade of the Void Marches",
			fr = "Phaseblade of the Void Marches",
			it = "Phaseblade of the Void Marches",
			pt = "Phaseblade of the Void Marches",
			ru = "Phaseblade of the Void Marches",
			ko = "Phaseblade of the Void Marches",
			cn = "Phaseblade of the Void Marches",
			tw = "Phaseblade of the Void Marches",
		},
	},
	[548597] = {
		readable = "Bladed Rifle of Unfettered Momentum",
		text = {
			en = "Bladed Rifle of Unfettered Momentum",
			es = "Bladed Rifle of Unfettered Momentum",
			mx = "Bladed Rifle of Unfettered Momentum",
			de = "Bladed Rifle of Unfettered Momentum",
			fr = "Bladed Rifle of Unfettered Momentum",
			it = "Bladed Rifle of Unfettered Momentum",
			pt = "Bladed Rifle of Unfettered Momentum",
			ru = "Bladed Rifle of Unfettered Momentum",
			ko = "Bladed Rifle of Unfettered Momentum",
			cn = "Bladed Rifle of Unfettered Momentum",
			tw = "Bladed Rifle of Unfettered Momentum",
		},
	},
})
do ObjectDB[objectID] = objectData; end
