local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[499956] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			mx = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
			tw = "Corrupted Chest",
		},
	},
	[499957] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			mx = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
			tw = "Corrupted Chest",
		},
	},
	[499958] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			mx = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
			tw = "Corrupted Chest",
		},
	},
	[517344] = {
		readable = "Cursed Horseshoe",
		model = 929369,
		text = {
			en = "Cursed Horseshoe",
			es = "Cursed Horseshoe",
			mx = "Cursed Horseshoe",
			de = "Cursed Horseshoe",
			fr = "Cursed Horseshoe",
			it = "Cursed Horseshoe",
			pt = "Cursed Horseshoe",
			ru = "Cursed Horseshoe",
			ko = "Cursed Horseshoe",
			cn = "Cursed Horseshoe",
			tw = "Cursed Horseshoe",
		},
	},
	[517348] = {
		readable = "Cursed Horseshoe",
		model = 929369,
		text = {
			en = "Cursed Horseshoe",
			es = "Cursed Horseshoe",
			mx = "Cursed Horseshoe",
			de = "Cursed Horseshoe",
			fr = "Cursed Horseshoe",
			it = "Cursed Horseshoe",
			pt = "Cursed Horseshoe",
			ru = "Cursed Horseshoe",
			ko = "Cursed Horseshoe",
			cn = "Cursed Horseshoe",
			tw = "Cursed Horseshoe",
		},
	},
	[517349] = {
		readable = "Cursed Horseshoe",
		model = 929369,
		text = {
			en = "Cursed Horseshoe",
			es = "Cursed Horseshoe",
			mx = "Cursed Horseshoe",
			de = "Cursed Horseshoe",
			fr = "Cursed Horseshoe",
			it = "Cursed Horseshoe",
			pt = "Cursed Horseshoe",
			ru = "Cursed Horseshoe",
			ko = "Cursed Horseshoe",
			cn = "Cursed Horseshoe",
			tw = "Cursed Horseshoe",
		},
	},
	[517350] = {
		readable = "Cursed Horseshoe",
		model = 929369,
		text = {
			en = "Cursed Horseshoe",
			es = "Cursed Horseshoe",
			mx = "Cursed Horseshoe",
			de = "Cursed Horseshoe",
			fr = "Cursed Horseshoe",
			it = "Cursed Horseshoe",
			pt = "Cursed Horseshoe",
			ru = "Cursed Horseshoe",
			ko = "Cursed Horseshoe",
			cn = "Cursed Horseshoe",
			tw = "Cursed Horseshoe",
		},
	},
	[519487] = {
		readable = "Worn Wolf Saddle",
		model = 850504,
		text = {
			en = "Worn Wolf Saddle",
			es = "Worn Wolf Saddle",
			mx = "Worn Wolf Saddle",
			de = "Worn Wolf Saddle",
			fr = "Worn Wolf Saddle",
			it = "Worn Wolf Saddle",
			pt = "Worn Wolf Saddle",
			ru = "Worn Wolf Saddle",
			ko = "Worn Wolf Saddle",
			cn = "Worn Wolf Saddle",
			tw = "Worn Wolf Saddle",
		},
	},
	[519559] = {
		readable = "Bag of Wolf Tack",
		model = 878854,
		text = {
			en = "Bag of Wolf Tack",
			es = "Bag of Wolf Tack",
			mx = "Bag of Wolf Tack",
			de = "Bag of Wolf Tack",
			fr = "Bag of Wolf Tack",
			it = "Bag of Wolf Tack",
			pt = "Bag of Wolf Tack",
			ru = "Bag of Wolf Tack",
			ko = "Bag of Wolf Tack",
			cn = "Bag of Wolf Tack",
			tw = "Bag of Wolf Tack",
		},
	},
	[529289] = {
		readable = "Spore Sample",
		model = 5201692,
		text = {
			en = "Spore Sample",
			es = "Spore Sample",
			mx = "Spore Sample",
			de = "Spore Sample",
			fr = "Spore Sample",
			it = "Spore Sample",
			pt = "Spore Sample",
			ru = "Spore Sample",
			ko = "Spore Sample",
			cn = "Spore Sample",
			tw = "Spore Sample",
		},
	},
	[529677] = {
		readable = "Void-Forged Engine Block",
		model = 197685,
		text = {
			en = "Void-Forged Engine Block",
			es = "Void-Forged Engine Block",
			mx = "Void-Forged Engine Block",
			de = "Void-Forged Engine Block",
			fr = "Void-Forged Engine Block",
			it = "Void-Forged Engine Block",
			pt = "Void-Forged Engine Block",
			ru = "Void-Forged Engine Block",
			ko = "Void-Forged Engine Block",
			cn = "Void-Forged Engine Block",
			tw = "Void-Forged Engine Block",
		},
	},
})
do ObjectDB[objectID] = objectData; end