local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[452867] = {
		readable = "Employee Schedule",
		model = 1305630,
		text = {
			en = "Employee Schedule",
			es = "Employee Schedule",
			de = "Employee Schedule",
			fr = "Employee Schedule",
			it = "Employee Schedule",
			pt = "Employee Schedule",
			ru = "Employee Schedule",
			ko = "Employee Schedule",
			cn = "Employee Schedule",
		},
	},
	[454411] = {
		readable = "Taunting Note",
		text = {
			en = "Taunting Note",
			es = "Taunting Note",
			de = "Taunting Note",
			fr = "Taunting Note",
			it = "Taunting Note",
			pt = "Taunting Note",
			ru = "Taunting Note",
			ko = "Taunting Note",
			cn = "Taunting Note",
		},
	},
	[456073] = {
		readable = "Sputtering Taserblade",
		text = {
			en = "Sputtering Taserblade",
			es = "Sputtering Taserblade",
			de = "Sputtering Taserblade",
			fr = "Sputtering Taserblade",
			it = "Sputtering Taserblade",
			pt = "Sputtering Taserblade",
			ru = "Sputtering Taserblade",
			ko = "Sputtering Taserblade",
			cn = "Sputtering Taserblade",
		},
	},
	[456747] = {
		readable = "Gig Sheets",
		text = {
			en = "Gig Sheets",
			es = "Gig Sheets",
			de = "Gig Sheets",
			fr = "Gig Sheets",
			it = "Gig Sheets",
			pt = "Gig Sheets",
			ru = "Gig Sheets",
			ko = "Gig Sheets",
			cn = "Gig Sheets",
		},
	},
	[461478] = {
		readable = "For Rent Sign",
		model = 305398,
		text = {
			en = "For Rent Sign",
			es = "For Rent Sign",
			de = "For Rent Sign",
			fr = "For Rent Sign",
			it = "For Rent Sign",
			pt = "For Rent Sign",
			ru = "For Rent Sign",
			ko = "For Rent Sign",
			cn = "For Rent Sign",
		},
	},
	[461492] = {
		readable = "Weapons Cache",
		text = {
			en = "Weapons Cache",
			es = "Weapons Cache",
			de = "Weapons Cache",
			fr = "Weapons Cache",
			it = "Weapons Cache",
			pt = "Weapons Cache",
			ru = "Weapons Cache",
			ko = "Weapons Cache",
			cn = "Weapons Cache",
		},
	},
	[480708] = {
		readable = "Overpriced Tropical Punch",
		model = 309567,
		text = {
			en = "Overpriced Tropical Punch",
			es = "Overpriced Tropical Punch",
			de = "Overpriced Tropical Punch",
			fr = "Overpriced Tropical Punch",
			it = "Overpriced Tropical Punch",
			pt = "Overpriced Tropical Punch",
			ru = "Overpriced Tropical Punch",
			ko = "Overpriced Tropical Punch",
			cn = "Overpriced Tropical Punch",
		},
	},
	[482270] = {
		readable = "Blackwater Ordinance",
		model = 5512209,
		text = {
			en = "Blackwater Ordinance",
			es = "Blackwater Ordinance",
			de = "Blackwater Ordinance",
			fr = "Blackwater Ordinance",
			it = "Blackwater Ordinance",
			pt = "Blackwater Ordinance",
			ru = "Blackwater Ordinance",
			ko = "Blackwater Ordinance",
			cn = "Blackwater Ordinance",
		},
	},
	[493305] = {
		readable = "Exploded Plunger",
		model = 343855,
		text = {
			en = "Exploded Plunger",
			es = "Exploded Plunger",
			de = "Exploded Plunger",
			fr = "Exploded Plunger",
			it = "Exploded Plunger",
			pt = "Exploded Plunger",
			ru = "Exploded Plunger",
			ko = "Exploded Plunger",
			cn = "Exploded Plunger",
		},
	},
	[499090] = {
		readable = "Fireworks Hat",
		text = {
			en = "Fireworks Hat",
			es = "Fireworks Hat",
			de = "Fireworks Hat",
			fr = "Fireworks Hat",
			it = "Fireworks Hat",
			pt = "Fireworks Hat",
			ru = "Fireworks Hat",
			ko = "Fireworks Hat",
			cn = "Fireworks Hat",
		},
	},
	[499207] = {
		readable = "Suspicious Book",
		text = {
			en = "Suspicious Book",
			es = "Suspicious Book",
			de = "Suspicious Book",
			fr = "Suspicious Book",
			it = "Suspicious Book",
			pt = "Suspicious Book",
			ru = "Suspicious Book",
			ko = "Suspicious Book",
			cn = "Suspicious Book",
		},
	},
	[502893] = {
		readable = "First Half of Noggenfogger's Journal",
		model = 936411,
		text = {
			en = "First Half of Noggenfogger's Journal",
			es = "First Half of Noggenfogger's Journal",
			de = "First Half of Noggenfogger's Journal",
			fr = "First Half of Noggenfogger's Journal",
			it = "First Half of Noggenfogger's Journal",
			pt = "First Half of Noggenfogger's Journal",
			ru = "First Half of Noggenfogger's Journal",
			ko = "First Half of Noggenfogger's Journal",
			cn = "First Half of Noggenfogger's Journal",
		},
	},
	[502902] = {
		readable = "Second Half of Noggenfogger's Journal",
		model = 936411,
		text = {
			en = "Second Half of Noggenfogger's Journal",
			es = "Second Half of Noggenfogger's Journal",
			de = "Second Half of Noggenfogger's Journal",
			fr = "Second Half of Noggenfogger's Journal",
			it = "Second Half of Noggenfogger's Journal",
			pt = "Second Half of Noggenfogger's Journal",
			ru = "Second Half of Noggenfogger's Journal",
			ko = "Second Half of Noggenfogger's Journal",
			cn = "Second Half of Noggenfogger's Journal",
		},
	},
	[502903] = {
		readable = "Gallywix's Notes",
		model = 929395,
		text = {
			en = "Gallywix's Notes",
			es = "Gallywix's Notes",
			de = "Gallywix's Notes",
			fr = "Gallywix's Notes",
			it = "Gallywix's Notes",
			pt = "Gallywix's Notes",
			ru = "Gallywix's Notes",
			ko = "Gallywix's Notes",
			cn = "Gallywix's Notes",
		},
	},
	[502908] = {
		readable = "A Threatening Letter",
		model = 1331239,
		text = {
			en = "A Threatening Letter",
			es = "A Threatening Letter",
			de = "A Threatening Letter",
			fr = "A Threatening Letter",
			it = "A Threatening Letter",
			pt = "A Threatening Letter",
			ru = "A Threatening Letter",
			ko = "A Threatening Letter",
			cn = "A Threatening Letter",
		},
	},
})
do ObjectDB[objectID] = objectData; end