local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[500694] = {
		readable = "Nerubian Lord",
		text = {
			en = "Nerubian Lord",
			es = "Nerubian Lord",
			de = "Nerubian Lord",
			fr = "Nerubian Lord",
			it = "Nerubian Lord",
			pt = "Nerubian Lord",
			ru = "Nerubian Lord",
			ko = "Nerubian Lord",
			cn = "Nerubian Lord",
		},
	},
	[502995] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[503011] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[503012] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[503157] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[507221] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[507226] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[507227] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end