local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[516154] = {
		readable = "Half-Empty Bag",
		model = 5100456,
		text = {
			en = "Half-Empty Bag",
			de = "Halbleere Tasche",
			es = "Bolsa medio vacía",
			mx = "Bolsa medio vacía",
			fr = "Sac à moitié vide",
			it = "Borsa Mezza Vuota",
			pt = "Bolsa pela Metade",
			ru = "Полупустая сумка",
			ko = "반쯤 빈 가방",
			cn = "半满的口袋",
			tw = "半滿的背包",
		},
	},
	[516156] = {
		readable = "Half-Empty Bag",
		model = 5100456,
		text = {
			en = "Half-Empty Bag",
			de = "Halbleere Tasche",
			es = "Bolsa medio vacía",
			mx = "Bolsa medio vacía",
			fr = "Sac à moitié vide",
			it = "Borsa Mezza Vuota",
			pt = "Bolsa pela Metade",
			ru = "Полупустая сумка",
			ko = "반쯤 빈 가방",
			cn = "半满的口袋",
			tw = "半滿的背包",
		},
	},
	[516158] = {
		readable = "Half-Empty Bag",
		model = 5100456,
		text = {
			en = "Half-Empty Bag",
			de = "Halbleere Tasche",
			es = "Bolsa medio vacía",
			mx = "Bolsa medio vacía",
			fr = "Sac à moitié vide",
			it = "Borsa Mezza Vuota",
			pt = "Bolsa pela Metade",
			ru = "Полупустая сумка",
			ko = "반쯤 빈 가방",
			cn = "半满的口袋",
			tw = "半滿的背包",
		},
	},
	[516160] = {
		readable = "Half-Empty Bag",
		model = 5100456,
		text = {
			en = "Half-Empty Bag",
			de = "Halbleere Tasche",
			es = "Bolsa medio vacía",
			mx = "Bolsa medio vacía",
			fr = "Sac à moitié vide",
			it = "Borsa Mezza Vuota",
			pt = "Bolsa pela Metade",
			ru = "Полупустая сумка",
			ko = "반쯤 빈 가방",
			cn = "半满的口袋",
			tw = "半滿的背包",
		},
	},
	[516163] = {
		readable = "Half-Empty Bag",
		model = 5100456,
		text = {
			en = "Half-Empty Bag",
			de = "Halbleere Tasche",
			es = "Bolsa medio vacía",
			mx = "Bolsa medio vacía",
			fr = "Sac à moitié vide",
			it = "Borsa Mezza Vuota",
			pt = "Bolsa pela Metade",
			ru = "Полупустая сумка",
			ko = "반쯤 빈 가방",
			cn = "半满的口袋",
			tw = "半滿的背包",
		},
	},
	[516165] = {
		readable = "Half-Empty Bag",
		model = 5100456,
		text = {
			en = "Half-Empty Bag",
			de = "Halbleere Tasche",
			es = "Bolsa medio vacía",
			mx = "Bolsa medio vacía",
			fr = "Sac à moitié vide",
			it = "Borsa Mezza Vuota",
			pt = "Bolsa pela Metade",
			ru = "Полупустая сумка",
			ko = "반쯤 빈 가방",
			cn = "半满的口袋",
			tw = "半滿的背包",
		},
	},
	[516167] = {
		readable = "Half-Empty Bag",
		model = 5100456,
		text = {
			en = "Half-Empty Bag",
			de = "Halbleere Tasche",
			es = "Bolsa medio vacía",
			mx = "Bolsa medio vacía",
			fr = "Sac à moitié vide",
			it = "Borsa Mezza Vuota",
			pt = "Bolsa pela Metade",
			ru = "Полупустая сумка",
			ko = "반쯤 빈 가방",
			cn = "半满的口袋",
			tw = "半滿的背包",
		},
	},
})
do ObjectDB[objectID] = objectData; end
