local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[403740] = {
		readable = "Cleanbrass Bolt",
		model = 197725,
		text = {
			en = "Cleanbrass Bolt",
			de = "Reinmessingbolzen",
			es = "Tornillo de broncebrillo",
			mx = "Tuerca broncelimpio",
			fr = "Boulon en laiton-franc",
			it = "Bullone di Purottone",
			pt = "Latafuso Polido",
			ru = "Чистомедный болт",
			ko = "무결황동 나사",
			cn = "亮铜螺钉",
			tw = "淨銅螺栓",
		},
	},
	[408912] = {
		readable = "Aged Marker",
		model = 4521375,
		text = {
			en = "Aged Marker",
			de = "Alte Markierung",
			es = "Marcador envejecido",
			mx = "Marcador avejentado",
			fr = "Marqueur vieilli",
			it = "Indicatore Vecchio",
			pt = "Marcador Envelhecido",
			ru = "Старый указатель",
			ko = "오래된 표지",
			cn = "陈年标记",
			tw = "老舊的標記",
		},
	},
	[408914] = {
		readable = "Aged Marker",
		model = 4521375,
		text = {
			en = "Aged Marker",
			de = "Alte Markierung",
			es = "Marcador envejecido",
			mx = "Marcador avejentado",
			fr = "Marqueur vieilli",
			it = "Indicatore Vecchio",
			pt = "Marcador Envelhecido",
			ru = "Старый указатель",
			ko = "오래된 표지",
			cn = "陈年标记",
			tw = "老舊的標記",
		},
	},
	[408915] = {
		readable = "Aged Marker",
		model = 4521375,
		text = {
			en = "Aged Marker",
			de = "Alte Markierung",
			es = "Marcador envejecido",
			mx = "Marcador avejentado",
			fr = "Marqueur vieilli",
			it = "Indicatore Vecchio",
			pt = "Marcador Envelhecido",
			ru = "Старый указатель",
			ko = "오래된 표지",
			cn = "陈年标记",
			tw = "老舊的標記",
		},
	},
	[408916] = {
		readable = "Aged Marker",
		model = 4521375,
		text = {
			en = "Aged Marker",
			de = "Alte Markierung",
			es = "Marcador envejecido",
			mx = "Marcador avejentado",
			fr = "Marqueur vieilli",
			it = "Indicatore Vecchio",
			pt = "Marcador Envelhecido",
			ru = "Старый указатель",
			ko = "오래된 표지",
			cn = "陈年标记",
			tw = "老舊的標記",
		},
	},
	[408918] = {
		readable = "Aged Marker",
		model = 4521375,
		text = {
			en = "Aged Marker",
			de = "Alte Markierung",
			es = "Marcador envejecido",
			mx = "Marcador avejentado",
			fr = "Marqueur vieilli",
			it = "Indicatore Vecchio",
			pt = "Marcador Envelhecido",
			ru = "Старый указатель",
			ko = "오래된 표지",
			cn = "陈年标记",
			tw = "老舊的標記",
		},
	},
	[408939] = {
		readable = "Banner Stand",
		model = 4182505,
		text = {
			en = "Banner Stand",
			de = "Bannerständer",
			es = "Pie de estandarte",
			mx = "Pendón del estandarte",
			fr = "Support de bannière",
			it = "Base dello Stendardo",
			pt = "Suporte de Estandarte",
			ru = "Стойка со знаменем",
			ko = "깃발 고정대",
			cn = "旗帜支架",
			tw = "旗幟立架",
		},
	},
	[416418] = {
		readable = "Harvest Seed Supply",
		model = 977078,
		text = {
			en = "Harvest Seed Supply",
			es = "Suministro de semillas de la cosecha",
			mx = "Suministro de semillas de cosecha",
			de = "Erntesamenvorrat",
			fr = "Ravitaillement en grain",
			it = "Rifornimento di Semi",
			pt = "Suprimento de Sementes da Colheita",
			ru = "Запас семян",
			ko = "수확물 씨앗 보급품",
			cn = "收获之种补给",
			tw = "豐收之種補給",
		},
	},
})
do ObjectDB[objectID] = objectData; end
