local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[503363] = {
		readable = "Battered Book",
		model = 4337371,
		text = {
			en = "Battered Book",
			es = "Battered Book",
			mx = "Battered Book",
			de = "Battered Book",
			fr = "Battered Book",
			it = "Battered Book",
			pt = "Battered Book",
			ru = "Battered Book",
			ko = "Battered Book",
			cn = "Battered Book",
			tw = "Battered Book",
		},
	},
	[503370] = {
		readable = "Submerged Bottle",
		model = 304791,
		text = {
			en = "Submerged Bottle",
			es = "Submerged Bottle",
			mx = "Submerged Bottle",
			de = "Submerged Bottle",
			fr = "Submerged Bottle",
			it = "Submerged Bottle",
			pt = "Submerged Bottle",
			ru = "Submerged Bottle",
			ko = "Submerged Bottle",
			cn = "Submerged Bottle",
			tw = "Submerged Bottle",
		},
	},
	[503375] = {
		readable = "Ancient Coffer",
		model = 1981374,
		text = {
			en = "Ancient Coffer",
			es = "Ancient Coffer",
			mx = "Ancient Coffer",
			de = "Ancient Coffer",
			fr = "Ancient Coffer",
			it = "Ancient Coffer",
			pt = "Ancient Coffer",
			ru = "Ancient Coffer",
			ko = "Ancient Coffer",
			cn = "Ancient Coffer",
			tw = "Ancient Coffer",
		},
	},
	[558090] = {
		readable = "A Dog-eared Book",
		model = 5387320,
		text = {
			en = "A Dog-eared Book",
			es = "A Dog-eared Book",
			mx = "A Dog-eared Book",
			de = "A Dog-eared Book",
			fr = "A Dog-eared Book",
			it = "A Dog-eared Book",
			pt = "A Dog-eared Book",
			ru = "A Dog-eared Book",
			ko = "A Dog-eared Book",
			cn = "A Dog-eared Book",
			tw = "A Dog-eared Book",
		},
	},
})
do ObjectDB[objectID] = objectData; end
