local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[466810] = {
		readable = "Void Cleft",
		model = 4906531,
		text = {
			en = "Void Cleft",
			es = "Void Cleft",
			mx = "Void Cleft",
			de = "Void Cleft",
			fr = "Void Cleft",
			it = "Void Cleft",
			pt = "Void Cleft",
			ru = "Void Cleft",
			ko = "Void Cleft",
			cn = "Void Cleft",
			tw = "Void Cleft",
		},
	},
	[466978] = {
		readable = "Om'Bera's Clipboard",
		model = 3998364,
		text = {
			en = "Om'Bera's Clipboard",
			es = "Om'Bera's Clipboard",
			mx = "Om'Bera's Clipboard",
			de = "Om'Bera's Clipboard",
			fr = "Om'Bera's Clipboard",
			it = "Om'Bera's Clipboard",
			pt = "Om'Bera's Clipboard",
			ru = "Om'Bera's Clipboard",
			ko = "Om'Bera's Clipboard",
			cn = "Om'Bera's Clipboard",
			tw = "Om'Bera's Clipboard",
		},
	},
	[466983] = {
		readable = "Curved Dagger",
		text = {
			en = "Curved Dagger",
			es = "Curved Dagger",
			mx = "Curved Dagger",
			de = "Curved Dagger",
			fr = "Curved Dagger",
			it = "Curved Dagger",
			pt = "Curved Dagger",
			ru = "Curved Dagger",
			ko = "Curved Dagger",
			cn = "Curved Dagger",
			tw = "Curved Dagger",
		},
	},
	[499082] = {
		readable = "Abandoned Lockbox",
		text = {
			en = "Abandoned Lockbox",
			es = "Abandoned Lockbox",
			mx = "Abandoned Lockbox",
			de = "Abandoned Lockbox",
			fr = "Abandoned Lockbox",
			it = "Abandoned Lockbox",
			pt = "Abandoned Lockbox",
			ru = "Abandoned Lockbox",
			ko = "Abandoned Lockbox",
			cn = "Abandoned Lockbox",
			tw = "Abandoned Lockbox",
		},
	},
	[499093] = {
		readable = "Forlorn Wind Chime",
		text = {
			en = "Forlorn Wind Chime",
			es = "Forlorn Wind Chime",
			mx = "Forlorn Wind Chime",
			de = "Forlorn Wind Chime",
			fr = "Forlorn Wind Chime",
			it = "Forlorn Wind Chime",
			pt = "Forlorn Wind Chime",
			ru = "Forlorn Wind Chime",
			ko = "Forlorn Wind Chime",
			cn = "Forlorn Wind Chime",
			tw = "Forlorn Wind Chime",
		},
	},
	[499097] = {
		readable = "Sand-Worn Coffer",
		model = 3450717,
		text = {
			en = "Sand-Worn Coffer",
			es = "Sand-Worn Coffer",
			mx = "Sand-Worn Coffer",
			de = "Sand-Worn Coffer",
			fr = "Sand-Worn Coffer",
			it = "Sand-Worn Coffer",
			pt = "Sand-Worn Coffer",
			ru = "Sand-Worn Coffer",
			ko = "Sand-Worn Coffer",
			cn = "Sand-Worn Coffer",
			tw = "Sand-Worn Coffer",
		},
	},
	[499334] = {
		readable = "Flickering Lantern",
		text = {
			en = "Flickering Lantern",
			es = "Flickering Lantern",
			mx = "Flickering Lantern",
			de = "Flickering Lantern",
			fr = "Flickering Lantern",
			it = "Flickering Lantern",
			pt = "Flickering Lantern",
			ru = "Flickering Lantern",
			ko = "Flickering Lantern",
			cn = "Flickering Lantern",
			tw = "Flickering Lantern",
		},
	},
	[499949] = {
		readable = "Stolen Research Crate",
		model = 3450717,
		text = {
			en = "Stolen Research Crate",
			es = "Stolen Research Crate",
			mx = "Stolen Research Crate",
			de = "Stolen Research Crate",
			fr = "Stolen Research Crate",
			it = "Stolen Research Crate",
			pt = "Stolen Research Crate",
			ru = "Stolen Research Crate",
			ko = "Stolen Research Crate",
			cn = "Stolen Research Crate",
			tw = "Stolen Research Crate",
		},
	},
	[502437] = {
		readable = "Wastelander Stash",
		text = {
			en = "Wastelander Stash",
			es = "Wastelander Stash",
			mx = "Wastelander Stash",
			de = "Wastelander Stash",
			fr = "Wastelander Stash",
			it = "Wastelander Stash",
			pt = "Wastelander Stash",
			ru = "Wastelander Stash",
			ko = "Wastelander Stash",
			cn = "Wastelander Stash",
			tw = "Wastelander Stash",
		},
	},
	[502452] = {
		readable = "Tumbled Package",
		text = {
			en = "Tumbled Package",
			es = "Tumbled Package",
			mx = "Tumbled Package",
			de = "Tumbled Package",
			fr = "Tumbled Package",
			it = "Tumbled Package",
			pt = "Tumbled Package",
			ru = "Tumbled Package",
			ko = "Tumbled Package",
			cn = "Tumbled Package",
			tw = "Tumbled Package",
		},
	},
	[502471] = {
		readable = "Rashaal's Vase",
		model = 3996881,
		text = {
			en = "Rashaal's Vase",
			es = "Rashaal's Vase",
			mx = "Rashaal's Vase",
			de = "Rashaal's Vase",
			fr = "Rashaal's Vase",
			it = "Rashaal's Vase",
			pt = "Rashaal's Vase",
			ru = "Rashaal's Vase",
			ko = "Rashaal's Vase",
			cn = "Rashaal's Vase",
			tw = "Rashaal's Vase",
		},
	},
	[502485] = {
		readable = "Shattered Crystals",
		text = {
			en = "Shattered Crystals",
			es = "Shattered Crystals",
			mx = "Shattered Crystals",
			de = "Shattered Crystals",
			fr = "Shattered Crystals",
			it = "Shattered Crystals",
			pt = "Shattered Crystals",
			ru = "Shattered Crystals",
			ko = "Shattered Crystals",
			cn = "Shattered Crystals",
			tw = "Shattered Crystals",
		},
	},
	[502547] = {
		readable = "Skeletal Tail Bones",
		model = 1664097,
		text = {
			en = "Skeletal Tail Bones",
			es = "Skeletal Tail Bones",
			mx = "Skeletal Tail Bones",
			de = "Skeletal Tail Bones",
			fr = "Skeletal Tail Bones",
			it = "Skeletal Tail Bones",
			pt = "Skeletal Tail Bones",
			ru = "Skeletal Tail Bones",
			ko = "Skeletal Tail Bones",
			cn = "Skeletal Tail Bones",
			tw = "Skeletal Tail Bones",
		},
	},
	[502603] = {
		readable = "Crudely Stitched Sack",
		model = 977078,
		text = {
			en = "Crudely Stitched Sack",
			es = "Crudely Stitched Sack",
			mx = "Crudely Stitched Sack",
			de = "Crudely Stitched Sack",
			fr = "Crudely Stitched Sack",
			it = "Crudely Stitched Sack",
			pt = "Crudely Stitched Sack",
			ru = "Crudely Stitched Sack",
			ko = "Crudely Stitched Sack",
			cn = "Crudely Stitched Sack",
			tw = "Crudely Stitched Sack",
		},
	},
	[504172] = {
		readable = "Ixthar's Favorite Crystal",
		text = {
			en = "Ixthar's Favorite Crystal",
			es = "Ixthar's Favorite Crystal",
			mx = "Ixthar's Favorite Crystal",
			de = "Ixthar's Favorite Crystal",
			fr = "Ixthar's Favorite Crystal",
			it = "Ixthar's Favorite Crystal",
			pt = "Ixthar's Favorite Crystal",
			ru = "Ixthar's Favorite Crystal",
			ko = "Ixthar's Favorite Crystal",
			cn = "Ixthar's Favorite Crystal",
			tw = "Ixthar's Favorite Crystal",
		},
	},
})
do ObjectDB[objectID] = objectData; end
