local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[456032] = {
		readable = "Ruffled Paper",
		model = 929401,
		text = {
			en = "Ruffled Paper",
			de = "Zerknittertes Papier",
			es = "Papel arrugado",
			fr = "Papier froissé",
			it = "Foglio Accartocciato",
			mx = "Papel arrugado",
			pt = "Papel Amarfanhado",
			ru = "Помятая бумажка",
			ko = "주름진 종이",
			cn = "起皱的纸张",
			tw = "弄皺的紙張",
		},
	},
	[456036] = {
		readable = "Loose Paper",
		model = 936413,
		text = {
			en = "Loose Paper",
			de = "Loses Papier",
			es = "Papel suelto",
			fr = "Papier volant",
			it = "Foglio di Carta",
			mx = "Papel suelto",
			pt = "Papel Solto",
			ru = "Выброшенная бумажка",
			ko = "흘린 종이",
			cn = "散落的纸张",
			tw = "脫落的紙張",
		},
	},
	[456038] = {
		readable = "Wet Paper",
		model = 305393,
		text = {
			en = "Wet Paper",
			de = "Nasses Papier",
			es = "Papel mojado",
			fr = "Papier humide",
			it = "Carta Bagnata",
			mx = "Papel mojado",
			pt = "Papel Molhado",
			ru = "Мокрая бумажка",
			ko = "젖은 종이",
			cn = "湿漉漉的纸张",
			tw = "濕透的紙張",
		},
	},
	[456039] = {
		readable = "Crumpled Letter",
		model = 1331238,
		text = {
			en = "Crumpled Letter",
			de = "Zusammengeknüllter Brief",
			es = "Carta arrugada",
			fr = "Lettre chiffonnée",
			it = "Lettera Accartocciata",
			mx = "Carta arrugada",
			pt = "Carta Amassada",
			ru = "Мятое письмо",
			ko = "구겨진 편지",
			cn = "皱巴巴的信",
			tw = "皺巴巴的信",
		},
	},
	[456041] = {
		readable = "Folded Paper",
		model = 311987,
		text = {
			en = "Folded Paper",
			de = "Gefaltetes Papier",
			es = "Papel doblado",
			fr = "Papier plié",
			it = "Foglio Ripiegato",
			mx = "Papel doblado",
			pt = "Papel Dobrado",
			ru = "Сложенная бумажка",
			ko = "접힌 종이",
			cn = "折起来的纸",
			tw = "折好的紙張",
		},
	},
	[456061] = {
		readable = "Battered Celebration Crate",
		model = 5282318,
		text = {
			en = "Battered Celebration Crate",
			de = "Ramponierte Feierkiste",
			es = "Cajón de celebración maltrecho",
			fr = "Caisse d’anniversaire abîmée",
			it = "Cassa della Celebrazione Malconcia",
			mx = "Cajón de festejo maltrecho",
			pt = "Caixote de Celebração Surrado",
			ru = "Потрепанный ящик с праздника",
			ko = "찌그러진 기념 상자",
			cn = "破损的庆典箱子",
			tw = "破損的慶典木箱",
		},
	},
	[462417] = {
		readable = "Waterlogged Celebration Crate",
		model = 5282318,
		text = {
			en = "Waterlogged Celebration Crate",
			de = "Durchnässte Feierkiste",
			es = "Cajón de celebración calado",
			fr = "Caisse d’anniversaire détrempée",
			it = "Cassa della Celebrazione Fradicia",
			mx = "Waterlogged Celebration Crate",
			pt = "Caixote de Celebração Encharcado",
			ru = "Промокший насквозь ящик с праздника",
			ko = "물에 젖은 기념 상자",
			cn = "浸水的庆典箱子",
			tw = "浸水的節慶木箱",
		},
	},
	[463104] = {
		readable = "Nola's Lash Wish",
		model = 511490,
		text = {
			en = "Nola's Lash Wish",
			de = "Nolas letzter Wunsch",
			es = "Último deseo de Nola",
			fr = "La dernière volonté de Nola",
			it = "Ultima Volontà di Nola",
			mx = "Última voluntad de Nola",
			pt = "O Açoitante Desejo de Nola",
			ru = "Последняя просьба Нолы",
			ko = "놀라의 마지막 소원",
			cn = "诺拉的遗愿",
			tw = "諾菈的最後心願",
		},
	},
	[465234] = {
		readable = "Missing Page from Yennu's Snackbook",
		model = 936413,
		text = {
			en = "Missing Page from Yennu's Snackbook",
			de = "Fehlende Seite aus Yennus Knabberkodex",
			es = "Página desaparecida del diario de tentempiés de Yennu",
			fr = "Page manquante du carnet de croquant de Yennu",
			it = "Pagina Mancante del Diario degli Spuntini di Yennu",
			mx = "Página faltante del libro de tentempiés de Yennu",
			pt = "Página Perdida do Livro de Petiscos do Yennu",
			ru = "Недостающая страница из книжки закусок Йенну",
			ko = "옌누의 수첩에서 사라진 책장",
			cn = "Missing Page from Yennu's Snackbook",
			tw = "葉努的點心簿的缺失頁面",
		},
	},
	[465277] = {
		readable = "Mound of Dirt",
		model = 189528,
		text = {
			en = "Mound of Dirt",
			de = "Erdhaufen",
			es = "Túmulo de barro",
			fr = "Monticule de poussière",
			it = "Mucchio di Terra",
			mx = "Túmulo de barro",
			pt = "Monturo de Terra",
			ru = "Куча грязи",
			ko = "흙무더기",
			cn = "Mound of Dirt",
			tw = "一堆泥土",
		},
	},
	[466438] = {
		readable = "Charred Celebration Crate",
		model = 5282318,
		text = {
			en = "Charred Celebration Crate",
			de = "Verkohlte Feierkiste",
			es = "Cajón de celebración chamuscado",
			fr = "Caisse d’anniversaire carbonisée",
			it = "Cassa della Celebrazione Carbonizzata",
			mx = "Cajón de festejo calcinado",
			pt = "Caixote de Celebração Calcinado",
			ru = "Обгорелый ящик с праздника",
			ko = "그을린 기념 상자",
			cn = "焦灼的庆典箱子",
			tw = "燒焦的節慶木箱",
		},
	},
	[466512] = {
		readable = "Crystallized Celebration Crate",
		model = 877007,
		text = {
			en = "Crystallized Celebration Crate",
			de = "Kristallisierte Feierkiste",
			es = "Cajón de celebración cristalizado",
			fr = "Caisse d’anniversaire cristallisée",
			it = "Cassa della Celebrazione Cristallizzata",
			mx = "Cajón de festejo cristalizado",
			pt = "Caixote de Celebração Cristalizado",
			ru = "Кристаллизованный ящик с праздника",
			ko = "결정화된 기념 상자",
			cn = "结晶的庆典箱子",
			tw = "晶化的節慶木箱",
		},
	},
	[467060] = {
		readable = "Ball of Yarn",
		model = 198143,
		text = {
			en = "Ball of Yarn",
			de = "Wollknäuel",
			es = "Ovillo",
			fr = "Pelote de laine",
			it = "Gomitolo di Lana",
			mx = "Bola de estambre",
			pt = "Bola de Lã",
			ru = "Клубок пряжи",
			ko = "털실 공",
			cn = "Ball of Yarn",
			tw = "毛線球",
		},
	},
	[467075] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[467083] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[467293] = {
		readable = "Chew Toy",
		model = 1597754,
		text = {
			en = "Chew Toy",
			de = "Kauspielzeug",
			es = "Mordedor",
			fr = "Jouet pour chien",
			it = "Giocattolo da Masticare",
			mx = "Mordedor",
			pt = "Brinquedinho de Morder",
			ru = "Игрушка для питомца",
			ko = "때묻은 장난감",
			cn = "Chew Toy",
			tw = "磨牙玩具",
		},
	},
	[467305] = {
		readable = "Toy Box",
		model = 4252799,
		text = {
			en = "Toy Box",
			de = "Spielzeugkiste",
			es = "Caja de juguetes",
			fr = "Coffre à jouets",
			it = "Scatola di Giocattoli",
			mx = "Caja de juguetes",
			pt = "Caixa de Brinquedo",
			ru = "Игрушки",
			ko = "장난감 상자",
			cn = "Toy Box",
			tw = "玩具箱",
		},
	},
	[467329] = {
		readable = "Maru's Toy",
		model = 4615240,
		text = {
			en = "Maru's Toy",
			de = "Marus Spielzeug",
			es = "Juguete de Maru",
			fr = "Jouet de Maru",
			it = "Giocattolo di Maru",
			mx = "Juguete de Maru",
			pt = "Brinquedo de Maru",
			ru = "Игрушка Мару",
			ko = "마루의 장난감",
			cn = "Maru's Toy",
			tw = "瑪魯的玩具",
		},
	},
	[467334] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[467336] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[467338] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[467339] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[467342] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[467351] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[467403] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			de = "Fortunakarte des Dunkelmond-Jahrmarkts",
			es = "Carta de la fortuna de la Luna Negra",
			fr = "Carte de bonne aventure de Sombrelune",
			it = "Carta della Fortuna di Lunacupa",
			mx = "Naipe de la fortuna de la Luna Negra",
			pt = "Carta da Sorte de Negraluna",
			ru = "Карта Новолуния для предсказаний",
			ko = "다크문 점괘 카드",
			cn = "暗月占卜牌",
			tw = "暗月命運卡片",
		},
	},
	[469568] = {
		readable = "Burnt Feather",
		model = 199706,
		text = {
			en = "Burnt Feather",
			de = "Verbrannte Feder",
			es = "Pluma quemada",
			fr = "Plume brûlée",
			it = "Piuma Bruciata",
			mx = "Pluma quemada",
			pt = "Pena Queimada",
			ru = "Обгорелое перо",
			ko = "불탄 깃털",
			cn = "烧焦的羽毛",
			tw = "燒焦的羽毛",
		},
	},
	[469569] = {
		readable = "Plucked Feather",
		model = 199708,
		text = {
			en = "Plucked Feather",
			de = "Ausgezupfte Feder",
			es = "Pluma arrancada",
			fr = "Plume arrachée",
			it = "Piuma Strappata",
			mx = "Pluma arrancada",
			pt = "Pena Arrancada",
			ru = "Выдернутое перо",
			ko = "너덜너덜한 깃털",
			cn = "拔下的羽毛",
			tw = "掉落的羽毛",
		},
	},
	[469573] = {
		readable = "Frozen Feather",
		model = 199704,
		text = {
			en = "Frozen Feather",
			de = "Gefrorene Feder",
			es = "Pluma congelada",
			fr = "Plume gelée",
			it = "Piuma Congelata",
			mx = "Pluma congelada",
			pt = "Pena Congelada",
			ru = "Замороженное перо",
			ko = "얼어붙은 깃털",
			cn = "冻结的羽毛",
			tw = "凍結的羽毛",
		},
	},
	[469574] = {
		readable = "Normal Feather",
		model = 199708,
		text = {
			en = "Normal Feather",
			de = "Normale Feder",
			es = "Pluma normal",
			fr = "Plume normale",
			it = "Piuma Normale",
			mx = "Pluma normal",
			pt = "Pena Normal",
			ru = "Обычное перо",
			ko = "평범한 깃털",
			cn = "普通羽毛",
			tw = "普通的羽毛",
		},
	},
	[469985] = {
		readable = "Ice Block",
		model = 201047,
		text = {
			en = "Ice Block",
			de = "Eisblock",
			es = "Bloque de hielo",
			fr = "Bloc de glace",
			it = "Blocco di Ghiaccio",
			mx = "Bloque de hielo",
			pt = "Bloco de Gelo",
			ru = "Ледяная глыба",
			ko = "얼음 방패",
			cn = "冰块",
			tw = "冰塊",
		},
	},
	[470229] = {
		readable = "Plush Toy",
		model = 1021411,
		text = {
			en = "Plush Toy",
			de = "Kuscheltier",
			es = "Juguete de peluche",
			fr = "Peluche",
			it = "Peluche",
			mx = "Juguete de peluche",
			pt = "Brinquedo de Pelúcia",
			ru = "Мягкая игрушка",
			ko = "봉제 인형",
			cn = "毛绒玩具",
			tw = "玩偶"
		},
	},
	[472068] = {
		readable = "Bakar Sketch",
		model = 936413,
		text = {
			en = "Bakar Sketch",
			de = "Zeichnung eines Bakars",
			es = "Dibujo de bakar",
			fr = "Croquis de bakar",
			it = "Disegno di Bakar",
			mx = "Boceto de bakar",
			pt = "Rabisco de Bakar",
			ru = "Набросок бакара",
			ko = "바카르 그림",
			cn = "獒犬速写",
			tw = "巴卡犬素描",
		},
	},
	[473934] = {
		readable = "Property of Cooktholomew",
		model = 200884,
		text = {
			en = "Property of Cooktholomew",
			de = "Eigentum von Smutholomäus",
			es = "Propiedad de Bartolochef",
			fr = "Propriété de Cuistolomée",
			it = "Proprietà di Cuocolomeo",
			mx = "Propiedad de Cheftolomeo",
			pt = "Propriedade de Gastrolomeu",
			ru = "Собственность Повартоломью",
			ko = "밥톨로뮤의 재산",
			cn = "库索劳默的财物",
			tw = "庫克托羅姆的財產",
		},
	},
	[475130] = {
		readable = "Hidden Hatch",
		model = 243849,
		text = {
			en = "Hidden Hatch",
			de = "Verborgene Luke",
			es = "Trampilla oculta",
			fr = "Trappe secrète",
			it = "Hidden Hatch",
			mx = "Escotilla oculta",
			pt = "Hidden Hatch",
			ru = "Потайной люк",
			ko = "Hidden Hatch",
			cn = "Hidden Hatch",
			tw = "隱藏艙門",
		},
	},
	[478090] = {
		readable = "Mildewed Celebration Crate",
		model = 5282318,
		text = {
			en = "Mildewed Celebration Crate",
			de = "Verschimmelte Feierkiste",
			es = "Cajón de celebración enmohecido",
			fr = "Caisse d’anniversaire moisie",
			it = "Cassa della Celebrazione Ammuffita",
			mx = "Cajón de festejo enmohecido",
			pt = "Caixote de Celebração Mofado",
			ru = "Заплесневевший ящик с праздника",
			ko = "흰곰팡이가 핀 기념 상자",
			cn = "发霉的庆典箱子",
		},
	},
	[505260] = {
		readable = "Potion of Truth",
		model = 892744,
		text = {
			en = "Potion of Truth",
			de = "Trank der Wahrheit",
			es = "Poción de la verdad",
			fr = "Potion de vérité",
			it = "Pozione della Verità",
			mx = "Poción de la verdad",
			pt = "Poção da Verdade",
			ru = "Зелье истины",
			ko = "진실의 물약",
			cn = "真相药水",
			tw = "真相藥水",
		},
	},
})
do ObjectDB[objectID] = objectData; end
