local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[504093] = {
		readable = "Web Bomb",
		model = 5364090,
		text = {
			en = "Web Bomb",
			de = "Netzbombe",
			es = "Bomba de telaraña",
			mx = "Bomba de telaraña",
			fr = "Bombe de toile",
			it = "Bomba Ragnatela",
			pt = "Bomba de Teia",
			ru = "Паутинная бомба",
			ko = "거미줄 폭탄",
			cn = "缠网炸弹",
			tw = "織網炸彈",
		},
	},
	[504195] = {
		readable = "Web Bomb",
		model = 5364090,
		text = {
			en = "Web Bomb",
			de = "Netzbombe",
			es = "Bomba de telaraña",
			mx = "Bomba de telaraña",
			fr = "Bombe de toile",
			it = "Bomba Ragnatela",
			pt = "Bomba de Teia",
			ru = "Паутинная бомба",
			ko = "거미줄 폭탄",
			cn = "缠网炸弹",
			tw = "織網炸彈",
		},
	},
	[506525] = {
		readable = "Plundered Artifacts",
		model = 5689833,
		text = {
			en = "Plundered Artifacts",
			de = "Geplünderte Artefakte",
			es = "Artefactos desvalijados",
			mx = "Artefactos saqueados",
			fr = "Artéfacts pillés",
			it = "Manufatti Saccheggiati",
			pt = "Artefatos Saqueados",
			ru = "Награбленные артефакты",
			ko = "약탈당한 유물",
			cn = "掠夺的神器",
			tw = "搜刮來的神器",
		},
	},
})
do ObjectDB[objectID] = objectData; end
