local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[516414] = {
		readable = "Red Dawn Oaths of Loyalty",
		model = 2026834,
		text = {
			en = "Red Dawn Oaths of Loyalty",
			es = "Red Dawn Oaths of Loyalty",
			mx = "Red Dawn Oaths of Loyalty",
			de = "Red Dawn Oaths of Loyalty",
			fr = "Red Dawn Oaths of Loyalty",
			it = "Red Dawn Oaths of Loyalty",
			pt = "Red Dawn Oaths of Loyalty",
			ru = "Red Dawn Oaths of Loyalty",
			ko = "Red Dawn Oaths of Loyalty",
			cn = "Red Dawn Oaths of Loyalty",
			tw = "Red Dawn Oaths of Loyalty",
		},
	},
	[516415] = {
		readable = "Red Dawn Propaganda",
		model = 5334703,
		text = {
			en = "Red Dawn Propaganda",
			es = "Red Dawn Propaganda",
			mx = "Red Dawn Propaganda",
			de = "Red Dawn Propaganda",
			fr = "Red Dawn Propaganda",
			it = "Red Dawn Propaganda",
			pt = "Red Dawn Propaganda",
			ru = "Red Dawn Propaganda",
			ko = "Red Dawn Propaganda",
			cn = "Red Dawn Propaganda",
			tw = "Red Dawn Propaganda",
		},
	},
	[516416] = {
		readable = "Red Dawn Propaganda",
		model = 5334703,
		text = {
			en = "Red Dawn Propaganda",
			es = "Red Dawn Propaganda",
			mx = "Red Dawn Propaganda",
			de = "Red Dawn Propaganda",
			fr = "Red Dawn Propaganda",
			it = "Red Dawn Propaganda",
			pt = "Red Dawn Propaganda",
			ru = "Red Dawn Propaganda",
			ko = "Red Dawn Propaganda",
			cn = "Red Dawn Propaganda",
			tw = "Red Dawn Propaganda",
		},
	},
	[516417] = {
		readable = "Red Dawn Propaganda",
		model = 5334703,
		text = {
			en = "Red Dawn Propaganda",
			es = "Red Dawn Propaganda",
			mx = "Red Dawn Propaganda",
			de = "Red Dawn Propaganda",
			fr = "Red Dawn Propaganda",
			it = "Red Dawn Propaganda",
			pt = "Red Dawn Propaganda",
			ru = "Red Dawn Propaganda",
			ko = "Red Dawn Propaganda",
			cn = "Red Dawn Propaganda",
			tw = "Red Dawn Propaganda",
		},
	},
})
do ObjectDB[objectID] = objectData; end
