local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[467435] = {
		readable = "Zaranit Bud",
		text = {
			en = "Zaranit Bud",
			es = "Zaranit Bud",
			mx = "Zaranit Bud",
			de = "Zaranit Bud",
			fr = "Zaranit Bud",
			it = "Zaranit Bud",
			pt = "Zaranit Bud",
			ru = "Zaranit Bud",
			ko = "Zaranit Bud",
			cn = "Zaranit Bud",
			tw = "Zaranit Bud",
		},
	},
	[475872] = {
		readable = "Rippling Wellspring",
		model = 353152,
		text = {
			en = "Rippling Wellspring",
			es = "Rippling Wellspring",
			mx = "Rippling Wellspring",
			de = "Rippling Wellspring",
			fr = "Rippling Wellspring",
			it = "Rippling Wellspring",
			pt = "Rippling Wellspring",
			ru = "Rippling Wellspring",
			ko = "Rippling Wellspring",
			cn = "Rippling Wellspring",
			tw = "Rippling Wellspring",
		},
	},
	[502375] = {
		readable = "Sand Pile",
		model = 5486311,
		text = {
			en = "Sand Pile",
			es = "Sand Pile",
			mx = "Sand Pile",
			de = "Sand Pile",
			fr = "Sand Pile",
			it = "Sand Pile",
			pt = "Sand Pile",
			ru = "Sand Pile",
			ko = "Sand Pile",
			cn = "Sand Pile",
			tw = "Sand Pile",
		},
	},
	[502376] = {
		readable = "Sand Pile",
		model = 5486311,
		text = {
			en = "Sand Pile",
			es = "Sand Pile",
			mx = "Sand Pile",
			de = "Sand Pile",
			fr = "Sand Pile",
			it = "Sand Pile",
			pt = "Sand Pile",
			ru = "Sand Pile",
			ko = "Sand Pile",
			cn = "Sand Pile",
			tw = "Sand Pile",
		},
	},
	[502377] = {
		readable = "Sand Pile",
		model = 5486311,
		text = {
			en = "Sand Pile",
			es = "Sand Pile",
			mx = "Sand Pile",
			de = "Sand Pile",
			fr = "Sand Pile",
			it = "Sand Pile",
			pt = "Sand Pile",
			ru = "Sand Pile",
			ko = "Sand Pile",
			cn = "Sand Pile",
			tw = "Sand Pile",
		},
	},
})
do ObjectDB[objectID] = objectData; end
