local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[467468] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			de = "Muffs Selbstschließer",
			es = "Baúl automático de Muff",
			mx = "Baúl automático de Muff",
			fr = "Autovestiaire de Muff",
			it = "Blocco Automatico di Muff",
			pt = "Autotrancante de Muff",
			ru = "Автозапиратель недотепы",
			ko = "머프의 자동 잠금 장치",
			cn = "傻瓜式自动锁柜",
			tw = "莫夫的自動上鎖箱",
		},
	},
	[474393] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			de = "Muffs Selbstschließer",
			es = "Baúl automático de Muff",
			mx = "Baúl automático de Muff",
			fr = "Autovestiaire de Muff",
			it = "Blocco Automatico di Muff",
			pt = "Autotrancante de Muff",
			ru = "Автозапиратель недотепы",
			ko = "머프의 자동 잠금 장치",
			cn = "傻瓜式自动锁柜",
			tw = "莫夫的自動上鎖箱",
		},
	},
	[474397] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			de = "Muffs Selbstschließer",
			es = "Baúl automático de Muff",
			mx = "Baúl automático de Muff",
			fr = "Autovestiaire de Muff",
			it = "Blocco Automatico di Muff",
			pt = "Autotrancante de Muff",
			ru = "Автозапиратель недотепы",
			ko = "머프의 자동 잠금 장치",
			cn = "傻瓜式自动锁柜",
			tw = "莫夫的自動上鎖箱",
		},
	},
	[474398] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			de = "Muffs Selbstschließer",
			es = "Baúl automático de Muff",
			mx = "Baúl automático de Muff",
			fr = "Autovestiaire de Muff",
			it = "Blocco Automatico di Muff",
			pt = "Autotrancante de Muff",
			ru = "Автозапиратель недотепы",
			ko = "머프의 자동 잠금 장치",
			cn = "傻瓜式自动锁柜",
			tw = "莫夫的自動上鎖箱",
		},
	},
	[476068] = {
		readable = "Papa's Prized Putter",
		text = {
			en = "Papa's Prized Putter",
			de = "Papas prächtiger Putter",
			es = "Palo de golf favorito de papá",
			mx = "Putter preciado de papá",
			fr = "Putter préféré de papa",
			it = "Putter Preferito di Papà",
			pt = "Taco Precioso do Papai",
			ru = "Папина любимая клюшка",
			ko = "아빠가 아끼는 골프채",
			cn = "老爹的宝贝推杆",
			tw = "老爹的寶貴推桿",
		},
	},
	[476071] = {
		readable = "Unsupervised Takeout",
		text = {
			en = "Unsupervised Takeout",
			de = "Nicht überwachte Entnahme",
			es = "Envío sin supervisión",
			mx = "Comida para llevar sin supervisión",
			fr = "Livraison sans surveillance",
			it = "Asporto Non Supervisionato",
			pt = "Entrega Sem Supervisão",
			ru = "Безнадзорная еда",
			ko = "방치된 음식",
			cn = "无人照看的外卖",
			tw = "無人看顧的外賣",
		},
	},
	[477363] = {
		readable = "Particularly Nice Lamp",
		text = {
			en = "Particularly Nice Lamp",
			de = "Besonders hübsche Lampe",
			es = "Lámpara especialmente bonita",
			mx = "Lámpara particularmente linda",
			fr = "Lampe particulièrement jolie",
			it = "Lampada Particolarmente Bella",
			pt = "Abajur Particularmente Legal",
			ru = "Довольно милая лампа",
			ko = "무척이나 멋진 등불",
			cn = "特别精美的台灯",
			tw = "特別漂亮的油燈",
		},
	},
	[477374] = {
		readable = "Uncracked Cold Ones",
		text = {
			en = "Uncracked Cold Ones",
			de = "Ungeöffnete Kaltgetränke",
			es = "Latas frías sin abrir",
			mx = "Latas frías sin abrir",
			fr = "Boissons fraîches non ouvertes",
			it = "Lattine Fredde Non Aperte",
			pt = "Geladas Intocadas",
			ru = "Невскрытые холодные напитки",
			ko = "따지 않은 시원한 콜라",
			cn = "未开封的冰饮",
			tw = "未裂開的冰涼可樂",
		},
	},
	[477376] = {
		readable = "Trick Deck of Cards",
		text = {
			en = "Trick Deck of Cards",
			de = "Trickkartenset",
			es = "Mazo de cartas trucado",
			mx = "Mazo de cartas para trucos",
			fr = "Jeu de cartes truqué",
			it = "Mazzo di Carte Truccate",
			pt = "Baralho de Cartas para Truques",
			ru = "Колода карт для фокусов",
			ko = "속임수 카드 묶음",
			cn = "一叠戏法卡牌",
			tw = "特技牌堆",
		},
	},
	[493307] = {
		readable = "Inert Plunger?",
		model = 343855,
		text = {
			en = "Inert Plunger?",
			de = "Inaktiver Zünder?",
			es = "¿Detonador inerte?",
			mx = "¿Desatascador inerte?",
			fr = "Détonateur inerte ?",
			it = "Detonatore Inerte?",
			pt = "Detonador Inerte?",
			ru = "Неподвижный поршень",
			ko = "격발장치 삽입?",
			cn = "失效的起爆器？",
			tw = "停滯的引爆裝置？",
		},
	},
	[495592] = {
		readable = "Blackened Dice",
		text = {
			en = "Blackened Dice",
			de = "Geschwärzter Würfel",
			es = "Dados ennegrecidos",
			mx = "Dado ennegrecido",
			fr = "Dés noircis",
			it = "Dadi Anneriti",
			pt = "Dados Enegrecidos",
			ru = "Черненый кубик",
			ko = "검게 물든 주사위",
			cn = "熏黑的骰子",
			tw = "黑鑄骰子",
		},
	},
	[504096] = {
		readable = "Crumpled Schematics",
		text = {
			en = "Crumpled Schematics",
			de = "Zusammengeknüllter Bauplan",
			es = "Esquemas arrugados",
			mx = "Esquemas arrugados",
			fr = "Schémas froissés",
			it = "Schemi Accartocciati",
			pt = "Diagramas Amassados",
			ru = "Смятые чертежи",
			ko = "구겨진 설계도",
			cn = "皱巴巴的结构图",
			tw = "弄皺的結構圖",
		},
	},
})
do ObjectDB[objectID] = objectData; end
