local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[469681] = {
		readable = "Footprints",
		model = 1567098,
		text = {
			en = "Footprints",
			es = "Footprints",
			mx = "Footprints",
			de = "Footprints",
			fr = "Footprints",
			it = "Footprints",
			pt = "Footprints",
			ru = "Footprints",
			ko = "Footprints",
			cn = "Footprints",
			tw = "Footprints",
		},
	},
	[469901] = {
		readable = "Void Glass Node",
		model = 5049181,
		text = {
			en = "Void Glass Node",
			es = "Void Glass Node",
			mx = "Void Glass Node",
			de = "Void Glass Node",
			fr = "Void Glass Node",
			it = "Void Glass Node",
			pt = "Void Glass Node",
			ru = "Void Glass Node",
			ko = "Void Glass Node",
			cn = "Void Glass Node",
			tw = "Void Glass Node",
		},
	},
	[500591] = {
		readable = "Firebud",
		text = {
			en = "Firebud",
			es = "Firebud",
			mx = "Firebud",
			de = "Firebud",
			fr = "Firebud",
			it = "Firebud",
			pt = "Firebud",
			ru = "Firebud",
			ko = "Firebud",
			cn = "Firebud",
			tw = "Firebud",
		},
	},
	[509461] = {
		readable = "Sealed Chest",
		text = {
			en = "Sealed Chest",
			es = "Sealed Chest",
			mx = "Sealed Chest",
			de = "Sealed Chest",
			fr = "Sealed Chest",
			it = "Sealed Chest",
			pt = "Sealed Chest",
			ru = "Sealed Chest",
			ko = "Sealed Chest",
			cn = "Sealed Chest",
			tw = "Sealed Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end
