local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[516153] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			de = "Zerbeulte Kiste",
			es = "Cajón abollado",
			mx = "Cajón abollado",
			fr = "Caisse endommagée",
			it = "Cassa Ammaccata",
			pt = "Caixote Amassado",
			ru = "Продавленный ящик",
			ko = "움푹 파인 상자",
			cn = "被挤压过的箱子",
			tw = "被擠壓過的木箱",
		},
	},
	[516155] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			de = "Zerbeulte Kiste",
			es = "Cajón abollado",
			mx = "Cajón abollado",
			fr = "Caisse endommagée",
			it = "Cassa Ammaccata",
			pt = "Caixote Amassado",
			ru = "Продавленный ящик",
			ko = "움푹 파인 상자",
			cn = "被挤压过的箱子",
			tw = "被擠壓過的木箱",
		},
	},
	[516157] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			de = "Zerbeulte Kiste",
			es = "Cajón abollado",
			mx = "Cajón abollado",
			fr = "Caisse endommagée",
			it = "Cassa Ammaccata",
			pt = "Caixote Amassado",
			ru = "Продавленный ящик",
			ko = "움푹 파인 상자",
			cn = "被挤压过的箱子",
			tw = "被擠壓過的木箱",
		},
	},
	[516159] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			de = "Zerbeulte Kiste",
			es = "Cajón abollado",
			mx = "Cajón abollado",
			fr = "Caisse endommagée",
			it = "Cassa Ammaccata",
			pt = "Caixote Amassado",
			ru = "Продавленный ящик",
			ko = "움푹 파인 상자",
			cn = "被挤压过的箱子",
			tw = "被擠壓過的木箱",
		},
	},
	[516164] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			de = "Zerbeulte Kiste",
			es = "Cajón abollado",
			mx = "Cajón abollado",
			fr = "Caisse endommagée",
			it = "Cassa Ammaccata",
			pt = "Caixote Amassado",
			ru = "Продавленный ящик",
			ko = "움푹 파인 상자",
			cn = "被挤压过的箱子",
			tw = "被擠壓過的木箱",
		},
	},
	[516166] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			de = "Zerbeulte Kiste",
			es = "Cajón abollado",
			mx = "Cajón abollado",
			fr = "Caisse endommagée",
			it = "Cassa Ammaccata",
			pt = "Caixote Amassado",
			ru = "Продавленный ящик",
			ko = "움푹 파인 상자",
			cn = "被挤压过的箱子",
			tw = "被擠壓過的木箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end
