local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[411744] = {
		readable = "Barrel of Wine",
		model = 4220170,
		text = {
			en = "Barrel of Wine",
			de = "Weinfass",
			es = "Barrica de vino",
			mx = "Barril de vino",
			fr = "Tonneau de vin",
			it = "Barile di Vino",
			pt = "Barril de Vinho",
			ru = "Бочка с вином",
			ko = "포도주 통",
			cn = "酒桶",
			tw = "一桶酒",
		},
	},
	[465646] = {
		readable = "Draconic Trophy",
		text = {
			en = "Draconic Trophy",
			de = "Drakonische Trophäe",
			es = "Trofeo dracónico",
			mx = "Trofeo dracónico",
			fr = "Trophée draconique",
			it = "Trofeo Draconico",
			pt = "Troféu Dragônico",
			ru = "Дракон-трофей",
			ko = "용 노획품",
			cn = "巨龙战利品",
			tw = "龍族獎盃",
		},
	},
	[465672] = {
		readable = "Gleaming Stonehead's Dented Armor",
		model = 5890942,
		text = {
			en = "Gleaming Stonehead's Dented Armor",
			de = "Verbeulte Rüstung des schimmernden Steinkopfs",
			es = "Armadura reluciente abollada de Cabeza Pétrea",
			mx = "Armadura abollada de Cefalopétreo resplandeciente",
			fr = "Armure cabossée de Tête-de-Caillasse étincelante",
			it = "Armatura Ammaccata dei Testaroccia Lucente",
			pt = "Armadura Amassada do Cabeça-de-pedra Rebrilhante",
			ru = "Помятый доспех сияющего камнелоба",
			ko = "빛나는 바위머리의 찌그러인 방어구",
			cn = "流光石脑袋的凹陷护甲",
			tw = "微光岩石頭的凹陷護甲",
		},
	},
	[465675] = {
		readable = "Rusting Clanker",
		model = 893080,
		text = {
			en = "Rusting Clanker",
			de = "Rostender Klapperer",
			es = "Cacharro oxidado",
			mx = "Rechinante oxidada",
			fr = "Tas de ferraille rouillé",
			it = "Sferragliatore Rugginoso",
			pt = "Tilintador Enferrujado",
			ru = "Ржавый лязгун",
			ko = "녹슨 쇳덩이",
			cn = "生锈的叮当机器",
			tw = "生鏽鏗鏘者",
		},
	},
	[465679] = {
		readable = "Questing Beast's Skull",
		text = {
			en = "Questing Beast's Skull",
			de = "Questbestienschädel",
			es = "Calavera de bestia aulladora",
			mx = "Cráneo de la Bestia Aulladora",
			fr = "Crâne de bête à quête",
			it = "Teschio di Bestia in Missione",
			pt = "Caveira de Fera das Missões",
			ru = "Череп зверя уже-не-рыкающего",
			ko = "여행 중인 야수의 해골",
			cn = "探险猛兽的颅骨",
			tw = "尋求的野獸頭骨",
		},
	},
	[504669] = {
		readable = "Mouthwash Bottle",
		text = {
			en = "Mouthwash Bottle",
			de = "Mundwasserflasche",
			es = "Botella de enjuague bucal",
			mx = "Botella de enjuague bucal",
			fr = "Bouteille de bain de bouche",
			it = "Bottiglia Lavabocca",
			pt = "Garrafa de Enxaguante Bucal",
			ru = "Ополаскиватель для рта",
			ko = "구강 청결제",
			cn = "漱口水瓶子",
			tw = "漱口瓶",
		},
	},
	[504670] = {
		readable = "Leftover Food",
		text = {
			en = "Leftover Food",
			de = "Essensreste",
			es = "Restos de comida",
			mx = "Sobras de comida",
			fr = "Restes de nourriture",
			it = "Cibo Avanzato",
			pt = "Sobras de Comida",
			ru = "Остатки еды",
			ko = "남은 음식",
			cn = "剩余的食物",
			tw = "吃剩的食物",
		},
	},
})
do ObjectDB[objectID] = objectData; end
