local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[495583] = {
		readable = "Missing Shipment",
		model = 3450717,
		text = {
			en = "Missing Shipment",
			es = "Missing Shipment",
			mx = "Missing Shipment",
			de = "Missing Shipment",
			fr = "Missing Shipment",
			it = "Missing Shipment",
			pt = "Missing Shipment",
			ru = "Missing Shipment",
			ko = "Missing Shipment",
			cn = "Missing Shipment",
			tw = "Missing Shipment",
		},
	},
	[563555] = {
		readable = "Writ of Repossession",
		text = {
			en = "Writ of Repossession",
			es = "Writ of Repossession",
			mx = "Writ of Repossession",
			de = "Writ of Repossession",
			fr = "Writ of Repossession",
			it = "Writ of Repossession",
			pt = "Writ of Repossession",
			ru = "Writ of Repossession",
			ko = "Writ of Repossession",
			cn = "Writ of Repossession",
			tw = "Writ of Repossession",
		},
	},
	[564545] = {
		readable = "Brann's Repossessed Gear",
		model = 4252795,
		text = {
			en = "Brann's Repossessed Gear",
			es = "Brann's Repossessed Gear",
			mx = "Brann's Repossessed Gear",
			de = "Brann's Repossessed Gear",
			fr = "Brann's Repossessed Gear",
			it = "Brann's Repossessed Gear",
			pt = "Brann's Repossessed Gear",
			ru = "Brann's Repossessed Gear",
			ko = "Brann's Repossessed Gear",
			cn = "Brann's Repossessed Gear",
			tw = "Brann's Repossessed Gear",
		},
	},
	[567732] = {
		readable = "Kaja'6-Pack",
		model = 5793092,
		text = {
			en = "Kaja'6-Pack",
			es = "Kaja'6-Pack",
			mx = "Kaja'6-Pack",
			de = "Kaja'6-Pack",
			fr = "Kaja'6-Pack",
			it = "Kaja'6-Pack",
			pt = "Kaja'6-Pack",
			ru = "Kaja'6-Pack",
			ko = "Kaja'6-Pack",
			cn = "Kaja'6-Pack",
			tw = "Kaja'6-Pack",
		},
	},
})
do ObjectDB[objectID] = objectData; end
