local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[469858] = {
		readable = "Shiny Trash Can",
		text = {
			en = "Shiny Trash Can",
			de = "Glänzende Mülltonne",
			es = "Cubo de basura brillante",
			mx = "Bote de basura brillante",
			fr = "Poubelle étincelante",
			it = "Pattumiera Luccicante",
			pt = "Lata de Lixo Brilhosa",
			ru = "Блестящая корзина для мусора",
			ko = "빛나는 쓰레기 깡통",
			cn = "闪亮的垃圾桶",
			tw = "亮晶晶的垃圾桶",
		},
	},
	[478435] = {
		readable = "Waiting Garbage Can",
		text = {
			en = "Waiting Garbage Can",
			de = "Wartende Mülltonne",
			es = "Cubo de basura en espera",
			mx = "Cesto de basura a la espera",
			fr = "Poubelle disponible",
			it = "Pattumiera in Attesa",
			pt = "Lata de Lixo à Espera",
			ru = "Мусорный бак в ожидании",
			ko = "대기 중인 쓰레기통",
			cn = "闲置的垃圾桶",
			tw = "正在等待垃圾桶",
		},
	},
	[478436] = {
		readable = "Waiting Garbage Can",
		text = {
			en = "Waiting Garbage Can",
			de = "Wartende Mülltonne",
			es = "Cubo de basura en espera",
			mx = "Cesto de basura a la espera",
			fr = "Poubelle disponible",
			it = "Pattumiera in Attesa",
			pt = "Lata de Lixo à Espera",
			ru = "Мусорный бак в ожидании",
			ko = "대기 중인 쓰레기통",
			cn = "闲置的垃圾桶",
			tw = "正在等待垃圾桶",
		},
	},
	[478437] = {
		readable = "Waiting Garbage Can",
		text = {
			en = "Waiting Garbage Can",
			de = "Wartende Mülltonne",
			es = "Cubo de basura en espera",
			mx = "Cesto de basura a la espera",
			fr = "Poubelle disponible",
			it = "Pattumiera in Attesa",
			pt = "Lata de Lixo à Espera",
			ru = "Мусорный бак в ожидании",
			ko = "대기 중인 쓰레기통",
			cn = "闲置的垃圾桶",
			tw = "正在等待垃圾桶",
		},
	},
	[478438] = {
		readable = "Waiting Garbage Can",
		text = {
			en = "Waiting Garbage Can",
			de = "Wartende Mülltonne",
			es = "Cubo de basura en espera",
			mx = "Cesto de basura a la espera",
			fr = "Poubelle disponible",
			it = "Pattumiera in Attesa",
			pt = "Lata de Lixo à Espera",
			ru = "Мусорный бак в ожидании",
			ko = "대기 중인 쓰레기통",
			cn = "闲置的垃圾桶",
			tw = "正在等待垃圾桶",
		},
	},
})
do ObjectDB[objectID] = objectData; end
