local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[500581] = {
		readable = "Container of Highly Profitable Sludge",
		text = {
			en = "Container of Highly Profitable Sludge",
			es = "Container of Highly Profitable Sludge",
			de = "Container of Highly Profitable Sludge",
			fr = "Container of Highly Profitable Sludge",
			it = "Container of Highly Profitable Sludge",
			pt = "Container of Highly Profitable Sludge",
			ru = "Container of Highly Profitable Sludge",
			ko = "Container of Highly Profitable Sludge",
			cn = "Container of Highly Profitable Sludge",
		},
	},
	[500582] = {
		readable = "Crate of Somewhat Profitable Sludge",
		text = {
			en = "Crate of Somewhat Profitable Sludge",
			es = "Crate of Somewhat Profitable Sludge",
			de = "Crate of Somewhat Profitable Sludge",
			fr = "Crate of Somewhat Profitable Sludge",
			it = "Crate of Somewhat Profitable Sludge",
			pt = "Crate of Somewhat Profitable Sludge",
			ru = "Crate of Somewhat Profitable Sludge",
			ko = "Crate of Somewhat Profitable Sludge",
			cn = "Crate of Somewhat Profitable Sludge",
		},
	},
	[500583] = {
		readable = "Box of Lightly Profitable Sludge",
		text = {
			en = "Box of Lightly Profitable Sludge",
			es = "Box of Lightly Profitable Sludge",
			de = "Box of Lightly Profitable Sludge",
			fr = "Box of Lightly Profitable Sludge",
			it = "Box of Lightly Profitable Sludge",
			pt = "Box of Lightly Profitable Sludge",
			ru = "Box of Lightly Profitable Sludge",
			ko = "Box of Lightly Profitable Sludge",
			cn = "Box of Lightly Profitable Sludge",
		},
	},
	[500750] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			es = "Uncovered Strongbox",
			de = "Uncovered Strongbox",
			fr = "Uncovered Strongbox",
			it = "Uncovered Strongbox",
			pt = "Uncovered Strongbox",
			ru = "Uncovered Strongbox",
			ko = "Uncovered Strongbox",
			cn = "Uncovered Strongbox",
		},
	},
	[500755] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			es = "Uncovered Strongbox",
			de = "Uncovered Strongbox",
			fr = "Uncovered Strongbox",
			it = "Uncovered Strongbox",
			pt = "Uncovered Strongbox",
			ru = "Uncovered Strongbox",
			ko = "Uncovered Strongbox",
			cn = "Uncovered Strongbox",
		},
	},
	[500756] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			es = "Uncovered Strongbox",
			de = "Uncovered Strongbox",
			fr = "Uncovered Strongbox",
			it = "Uncovered Strongbox",
			pt = "Uncovered Strongbox",
			ru = "Uncovered Strongbox",
			ko = "Uncovered Strongbox",
			cn = "Uncovered Strongbox",
		},
	},
	[500757] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			es = "Uncovered Strongbox",
			de = "Uncovered Strongbox",
			fr = "Uncovered Strongbox",
			it = "Uncovered Strongbox",
			pt = "Uncovered Strongbox",
			ru = "Uncovered Strongbox",
			ko = "Uncovered Strongbox",
			cn = "Uncovered Strongbox",
		},
	},
	[500758] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			es = "Uncovered Strongbox",
			de = "Uncovered Strongbox",
			fr = "Uncovered Strongbox",
			it = "Uncovered Strongbox",
			pt = "Uncovered Strongbox",
			ru = "Uncovered Strongbox",
			ko = "Uncovered Strongbox",
			cn = "Uncovered Strongbox",
		},
	},
	[504338] = {
		readable = "Rooftop Teleporter",
		text = {
			en = "Rooftop Teleporter",
			es = "Rooftop Teleporter",
			de = "Rooftop Teleporter",
			fr = "Rooftop Teleporter",
			it = "Rooftop Teleporter",
			pt = "Rooftop Teleporter",
			ru = "Rooftop Teleporter",
			ko = "Rooftop Teleporter",
			cn = "Rooftop Teleporter",
		},
	},
})
do ObjectDB[objectID] = objectData; end