local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[476815] = {
		readable = "Ancient Treasure Note",
		model = 936413,
		text = {
			en = "Ancient Treasure Note",
			de = "Uralte Schatznotiz",
			es = "Nota sobre un tesoro antiguo",
			fr = "Note sur un trésor ancien",
			it = "Nota sul Tesoro Antico",
			mx = "Nota de tesoro antigua",
			pt = "Anotação sobre Tesouro Antigo",
			ru = "Запись о древнем сокровище",
			ko = "고대의 보물 쪽지",
			cn = "古代宝藏的笔记",
			tw = "古代寶藏筆記",
		},
	},
	[477605] = {
		readable = "Ancient Treasure Note",
		model = 936413,
		text = {
			en = "Ancient Treasure Note",
			de = "Uralte Schatznotiz",
			es = "Nota sobre un tesoro antiguo",
			fr = "Note sur un trésor ancien",
			it = "Nota sul Tesoro Antico",
			mx = "Nota de tesoro antigua",
			pt = "Anotação sobre Tesouro Antigo",
			ru = "Запись о древнем сокровище",
			ko = "고대의 보물 쪽지",
			cn = "古代宝藏的笔记",
			tw = "古代寶藏筆記",
		},
	},
	[477609] = {
		readable = "Ancient Treasure Note",
		model = 936413,
		text = {
			en = "Ancient Treasure Note",
			de = "Uralte Schatznotiz",
			es = "Nota sobre un tesoro antiguo",
			fr = "Note sur un trésor ancien",
			it = "Nota sul Tesoro Antico",
			mx = "Nota de tesoro antigua",
			pt = "Anotação sobre Tesouro Antigo",
			ru = "Запись о древнем сокровище",
			ko = "고대의 보물 쪽지",
			cn = "古代宝藏的笔记",
			tw = "古代寶藏筆記",
		},
	},
})
do ObjectDB[objectID] = objectData; end
