local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[500694] = {
		readable = "Nerubian Lord",
		text = {
			en = "Nerubian Lord",
			de = "Lady der Neruber",
			es = "Señor nerubiano",
			mx = "Señor nerubiano",
			fr = "Dame ou seigneur nérubien",
			it = "Signora Nerubiana",
			pt = "Lorde Nerubiano",
			ru = "Нерубский владыка",
			ko = "네루비안 군주",
			cn = "蛛魔领主",
			tw = "奈幽領主",
		},
	},
	[502995] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			de = "Robuste Truhe",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			cn = "坚固宝箱",
			tw = "結實的箱子",
		},
	},
	[503011] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			de = "Robuste Truhe",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			cn = "坚固宝箱",
			tw = "結實的箱子",
		},
	},
	[503012] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			de = "Robuste Truhe",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			cn = "坚固宝箱",
			tw = "結實的箱子",
		},
	},
	[503157] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			de = "Robuste Truhe",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			cn = "坚固宝箱",
			tw = "結實的箱子",
		},
	},
	[507221] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			de = "Robuste Truhe",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			cn = "坚固宝箱",
			tw = "結實的箱子",
		},
	},
	[507226] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			de = "Robuste Truhe",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			cn = "坚固宝箱",
			tw = "結實的箱子",
		},
	},
	[507227] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			de = "Robuste Truhe",
			es = "Cofre robusto",
			mx = "Cofre robusto",
			fr = "Coffre solide",
			it = "Cassa Resistente",
			pt = "Baú Resistente",
			ru = "Прочный сундук",
			ko = "튼튼한 상자",
			cn = "坚固宝箱",
			tw = "結實的箱子",
		},
	},
})
do ObjectDB[objectID] = objectData; end
