local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454311] = {
		readable = "Redberry",
		text = {
			en = "Redberry",
			de = "Rotbeere",
			es = "Cereza",
			mx = "Baya roja",
			fr = "Bairouge",
			it = "Bacca Rossa",
			pt = "Fruta Silvestre",
			ru = "Красноягода",
			ko = "붉은 열매",
			cn = "红莓",
			tw = "紅莓",
		},
	},
	[454312] = {
		readable = "Redberry",
		model = 1586163,
		text = {
			en = "Redberry",
			de = "Rotbeere",
			es = "Cereza",
			mx = "Baya roja",
			fr = "Bairouge",
			it = "Bacca Rossa",
			pt = "Fruta Silvestre",
			ru = "Красноягода",
			ko = "붉은 열매",
			cn = "红莓",
			tw = "紅莓",
		},
	},
	[454456] = {
		readable = "Note",
		model = 943682,
		text = {
			en = "Note",
			de = "Notiz",
			es = "Nota",
			mx = "Nota",
			fr = "Note",
			it = "Nota",
			pt = "Bilhete",
			ru = "Записка",
			ko = "쪽지",
			cn = "纸条",
			tw = "紙條",
		},
	},
	[500640] = {
		readable = "Metal Scrap",
		model = 2068148,
		text = {
			en = "Metal Scrap",
			de = "Metallschrott",
			es = "Chatarra",
			mx = "Trozo de metal",
			fr = "Morceau de métal",
			it = "Pezzo di Metallo",
			pt = "Sucata de Metal",
			ru = "Обломок металла",
			ko = "금속 조각",
			cn = "金属碎片",
			tw = "金屬碎塊",
		},
	},
})
do ObjectDB[objectID] = objectData; end
