local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[465183] = {
		readable = "Mysterious Bones",
		model = 4690413,
		text = {
			en = "Mysterious Bones",
			de = "Mysteriöse Knochen",
			es = "Huesos misteriosos",
			fr = "Ossements mystérieux",
			it = "Ossa Misteriose",
			mx = "Huesos misteriosos",
			pt = "Ossos Misteriosos",
			ru = "Таинственные кости",
			ko = "수수께끼의 뼈",
			cn = "神秘的骨头",
			tw = "神秘的骸骨",
		},
	},
	[466118] = {
		readable = "Unfinished Note",
		model = 936413,
		text = {
			en = "Unfinished Note",
			de = "Unvollendete Notiz",
			es = "Nota sin terminar",
			fr = "Note inachevée",
			it = "Nota Incompiuta",
			mx = "Nota incompleta",
			pt = "Anotação Inacabada",
			ru = "Незаконченная записка",
			ko = "미완성 쪽지",
			cn = "未写完的纸条",
			tw = "未完成的筆記",
		},
	},
	[466119] = {
		readable = "Hastily Scrawled Note",
		model = 936413,
		text = {
			en = "Hastily Scrawled Note",
			de = "Hastig geschriebene Notiz",
			es = "Nota garabateada deprisa",
			fr = "Note griffonnée à la hâte",
			it = "Nota Scarabocchiata di Fretta",
			mx = "Nota escrita con prisa",
			pt = "Bilhete Escrito Às Pressas",
			ru = "Нацарапанная в спешке записка",
			ko = "급히 갈겨쓴 쪽지",
			cn = "字迹潦草的字条",
			tw = "飛快潦草的筆記",
		},
	},
	[466120] = {
		readable = "Water-Resistant Note",
		model = 936413,
		text = {
			en = "Water-Resistant Note",
			de = "Wasserfeste Notiz",
			es = "Nota impermeable",
			fr = "Note imperméable",
			it = "Nota Resistente all'Acqua",
			mx = "Nota resistente al agua",
			pt = "Anotação Impermeável",
			ru = "Непромокаемая записка",
			ko = "방수 쪽지",
			cn = "防水的纸条",
			tw = "防水筆記",
		},
	},
	[466128] = {
		readable = "Peculiar Gem",
		model = 1282671,
		text = {
			en = "Peculiar Gem",
			de = "Seltsamer Edelstein",
			es = "Gema peculiar",
			fr = "Gemme étrange",
			it = "Gemma Peculiare",
			mx = "Gema peculiar",
			pt = "Gema Peculiar",
			ru = "Необычный самоцвет",
			ko = "기묘한 보석",
			cn = "奇异宝石",
			tw = "奇特寶石",
		},
	},
	[469327] = {
		readable = "Play Script",
		model = 936429,
		text = {
			en = "Play Script",
			de = "Theaterskript",
			es = "Guion de la obra",
			fr = "Script de la pièce",
			it = "Sceneggiatura dello Spettacolo",
			mx = "Guion",
			pt = "Texto da Peça",
			ru = "Сценарий пьесы",
			ko = "연극 각본",
			cn = "剧本",
			tw = "劇本",
		},
	},
	[469332] = {
		readable = "Prop Sword",
		model = 1361976,
		text = {
			en = "Prop Sword",
			de = "Schwertrequisit",
			es = "Espada de atrezo",
			fr = "Épée factice",
			it = "Spada Finta",
			mx = "Espada de utilería",
			pt = "Espada Cenográfica",
			ru = "Бутафорский меч",
			ko = "검 소품",
			cn = "道具用剑",
			tw = "道具劍",
		},
	},
	[469334] = {
		readable = "Mask of the Trickster",
		model = 1357703,
		text = {
			en = "Mask of the Trickster",
			de = "Maske des Tricksers",
			es = "Máscara de la tramposa",
			fr = "Masque de l’entourloupeur",
			it = "Maschera dell'Ingannatrice",
			mx = "Máscara de bromista",
			pt = "Máscara da Trapaceira",
			ru = "Маска трикстера",
			ko = "요술쟁이의 가면",
			cn = "欺诈者的面具",
			tw = "欺詐者面具",
		},
	},
	[469335] = {
		readable = "Conductor's Baton",
		model = 3036134,
		text = {
			en = "Conductor's Baton",
			de = "Taktstock des Dirigenten",
			es = "Bastón de director",
			fr = "Bâton du chef",
			it = "Bacchetta del Conduttore",
			mx = "Batuta de director",
			pt = "Batuta do Maestro",
			ru = "Дирижерская палочка",
			ko = "지휘자의 봉",
			cn = "指挥棒",
			tw = "指揮棒",
		},
	},
})
do ObjectDB[objectID] = objectData; end
