local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[73940] = {
		readable = "Ooze Covered Silver Vein",
		model = 219553,
		text = {
			en = "Ooze Covered Silver Vein",
			es = "[Ooze Covered Silver Vein]",
			mx = "[Ooze Covered Silver Vein]",
			de = "Brühschlammbedecktes Silbervorkommen",
			fr = "Filon d'argent couvert de limon",
			it = "Ooze Covered Silver Vein",
			pt = "Veio de Prata Coberto de Gosma",
			ru = "Покрытая слизью серебряная жила",
			ko = "진흙으로 덮인 은 광맥",
			cn = "[Ooze Covered Silver Vein]",
			tw = "[Ooze Covered Silver Vein]",
		},
	},
	[73941] = {
		readable = "Ooze Covered Gold Vein",
		model = 219553,
		text = {
			en = "Ooze Covered Gold Vein",
			es = "Filón de oro cubierto de moco",
			mx = "[Ooze Covered Gold Vein]",
			de = "Schlammbedecktes Goldvorkommen",
			fr = "Filon d'or couvert de limon",
			it = "Ooze Covered Gold Vein",
			pt = "Veio de Ouro Coberto de Gosma",
			ru = "Покрытая слизью золотая жила",
			ko = "진흙으로 덮인 금 광맥",
			cn = "软泥覆盖的金矿脉",
			tw = "[Ooze Covered Gold Vein]",
		},
	},
	[103711] = {
		readable = "Tin Vein",
		model = 219568,
		text = {
			en = "Tin Vein",
			es = "Filón de estaño",
			mx = "Filón de estaño",
			de = "Zinnvorkommen",
			fr = "Filon d'étain",
			it = "Tin Vein",
			pt = "Veio de Estanho",
			ru = "Оловянная жила",
			ko = "주석 광맥",
			cn = "锡矿",
			tw = "錫礦脈",
		},
	},
	[103713] = {
		readable = "Copper Vein",
		model = 219514,
		text = {
			en = "Copper Vein",
			es = "Filón de cobre",
			mx = "Filón de cobre",
			de = "Kupfervorkommen",
			fr = "Filon de cuivre",
			it = "Copper Vein",
			pt = "Veio de Cobre",
			ru = "Медная жила",
			ko = "구리 광맥",
			cn = "铜矿",
			tw = "銅礦",
		},
	},
	[105569] = {
		readable = "Silver Vein",
		model = 219569,
		text = {
			en = "Silver Vein",
			es = "Filón de plata",
			mx = "Filón de plata",
			de = "Silbervorkommen",
			fr = "Filon d'argent",
			it = "Silver Vein",
			pt = "Veio de Prata",
			ru = "Серебряная жила",
			ko = "은 광맥",
			cn = "银矿",
			tw = "銀礦",
		},
	},
})
do ObjectDB[objectID] = objectData; end
