local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[500581] = {
		readable = "Container of Highly Profitable Sludge",
		text = {
			en = "Container of Highly Profitable Sludge",
			de = "Behälter mit hochprofitablem Schlick",
			es = "Contenedor de fango muy rentable",
			mx = "Contenedor de viscosidad de alta rentabilidad",
			fr = "Conteneur de vase très rentable",
			it = "Cassa di Poltiglia Molto Remunerativa",
			pt = "Recipiente de Lodo Altamente Lucrativo",
			ru = "Контейнер с весьма многообещающей жижей",
			ko = "매우 수익성 있는 오물 상자",
			cn = "大有赚头的淤泥容器",
			tw = "裝著高價值淤泥的容器",
		},
	},
	[500582] = {
		readable = "Crate of Somewhat Profitable Sludge",
		text = {
			en = "Crate of Somewhat Profitable Sludge",
			de = "Kiste mit mäßig profitablem Schlick",
			es = "Cajón de fango algo rentable",
			mx = "Cajón de viscosidad de mediana rentabilidad",
			fr = "Caisse de vase plutôt rentable",
			it = "Cassa di Poltiglia Vagamente Remunerativa",
			pt = "Caixote de Lodo Mais ou Menos Lucrativo",
			ru = "Ящик с довольно многообещающей жижей",
			ko = "어느 정도 수익성 있는 오물 상자",
			cn = "小有赚头的淤泥箱",
			tw = "裝著有價值淤泥的木箱",
		},
	},
	[500583] = {
		readable = "Box of Lightly Profitable Sludge",
		text = {
			en = "Box of Lightly Profitable Sludge",
			de = "Schachtel mit leicht profitablem Schlick",
			es = "Caja de fango ligeramente rentable",
			mx = "Caja de viscosidad de baja rentabilidad",
			fr = "Boîte de vase légèrement rentable",
			it = "Scatola di Poltiglia Leggermente Remunerativa",
			pt = "Caixa de Lodo Ligeiramente Lucrativo",
			ru = "Коробка в меру многообещающей жижи",
			ko = "약간 수익성 있는 오물 상자",
			cn = "略有赚头的淤泥箱",
			tw = "裝著稍有價值淤泥的箱子",
		},
	},
	[500750] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			de = "Aufgedeckte Schließkassette",
			es = "Caja fuerte descubierta",
			mx = "Caja fuerte descubierta",
			fr = "Coffre renforcé découvert",
			it = "Forziere Scoperto",
			pt = "Caixa-forte Descoberta",
			ru = "Откопанный сундучок",
			ko = "발견되지 않은 금고",
			cn = "发现的保险箱",
			tw = "發現的保險箱",
		},
	},
	[500755] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			de = "Aufgedeckte Schließkassette",
			es = "Caja fuerte descubierta",
			mx = "Caja fuerte descubierta",
			fr = "Coffre renforcé découvert",
			it = "Forziere Scoperto",
			pt = "Caixa-forte Descoberta",
			ru = "Откопанный сундучок",
			ko = "발견되지 않은 금고",
			cn = "发现的保险箱",
			tw = "發現的保險箱",
		},
	},
	[500756] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			de = "Aufgedeckte Schließkassette",
			es = "Caja fuerte descubierta",
			mx = "Caja fuerte descubierta",
			fr = "Coffre renforcé découvert",
			it = "Forziere Scoperto",
			pt = "Caixa-forte Descoberta",
			ru = "Откопанный сундучок",
			ko = "발견되지 않은 금고",
			cn = "发现的保险箱",
			tw = "發現的保險箱",
		},
	},
	[500757] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			de = "Aufgedeckte Schließkassette",
			es = "Caja fuerte descubierta",
			mx = "Caja fuerte descubierta",
			fr = "Coffre renforcé découvert",
			it = "Forziere Scoperto",
			pt = "Caixa-forte Descoberta",
			ru = "Откопанный сундучок",
			ko = "발견되지 않은 금고",
			cn = "发现的保险箱",
			tw = "發現的保險箱",
		},
	},
	[500758] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			de = "Aufgedeckte Schließkassette",
			es = "Caja fuerte descubierta",
			mx = "Caja fuerte descubierta",
			fr = "Coffre renforcé découvert",
			it = "Forziere Scoperto",
			pt = "Caixa-forte Descoberta",
			ru = "Откопанный сундучок",
			ko = "발견되지 않은 금고",
			cn = "发现的保险箱",
			tw = "發現的保險箱",
		},
	},
	[504338] = {
		readable = "Rooftop Teleporter",
		text = {
			en = "Rooftop Teleporter",
			de = "Dachteleporter",
			es = "Teletransportador de la azotea",
			mx = "Teletransportador de azotea",
			fr = "Téléporteur du toit",
			it = "Teletrasporto sul Tetto",
			pt = "Teleportador do Terraço",
			ru = "Телепорт на крышу",
			ko = "옥상 순간이동기",
			cn = "屋顶传送器",
			tw = "屋頂傳送器",
		},
	},
})
do ObjectDB[objectID] = objectData; end
