local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[499086] = {
		readable = "Lightly-Dented Luggage",
		text = {
			en = "Lightly-Dented Luggage",
			es = "Lightly-Dented Luggage",
			mx = "Lightly-Dented Luggage",
			de = "Lightly-Dented Luggage",
			fr = "Lightly-Dented Luggage",
			it = "Lightly-Dented Luggage",
			pt = "Lightly-Dented Luggage",
			ru = "Lightly-Dented Luggage",
			ko = "Lightly-Dented Luggage",
			cn = "Lightly-Dented Luggage",
			tw = "Lightly-Dented Luggage",
		},
	},
	[558105] = {
		readable = "Mysterious Notebook",
		model = 949611,
		text = {
			en = "Mysterious Notebook",
			es = "Mysterious Notebook",
			mx = "Mysterious Notebook",
			de = "Mysterious Notebook",
			fr = "Mysterious Notebook",
			it = "Mysterious Notebook",
			pt = "Mysterious Notebook",
			ru = "Mysterious Notebook",
			ko = "Mysterious Notebook",
			cn = "Mysterious Notebook",
			tw = "Mysterious Notebook",
		},
	},
	[558109] = {
		readable = "Ba'key's Aromatic Broker Cookies Recipes",
		model = 3836262,
		text = {
			en = "Ba'key's Aromatic Broker Cookies Recipes",
			es = "Ba'key's Aromatic Broker Cookies Recipes",
			mx = "Ba'key's Aromatic Broker Cookies Recipes",
			de = "Ba'key's Aromatic Broker Cookies Recipes",
			fr = "Ba'key's Aromatic Broker Cookies Recipes",
			it = "Ba'key's Aromatic Broker Cookies Recipes",
			pt = "Ba'key's Aromatic Broker Cookies Recipes",
			ru = "Ba'key's Aromatic Broker Cookies Recipes",
			ko = "Ba'key's Aromatic Broker Cookies Recipes",
			cn = "Ba'key's Aromatic Broker Cookies Recipes",
			tw = "Ba'key's Aromatic Broker Cookies Recipes",
		},
	},
	[558115] = {
		readable = "Coins: An Oath We Exchange",
		model = 3836262,
		text = {
			en = "Coins: An Oath We Exchange",
			es = "Coins: An Oath We Exchange",
			mx = "Coins: An Oath We Exchange",
			de = "Coins: An Oath We Exchange",
			fr = "Coins: An Oath We Exchange",
			it = "Coins: An Oath We Exchange",
			pt = "Coins: An Oath We Exchange",
			ru = "Coins: An Oath We Exchange",
			ko = "Coins: An Oath We Exchange",
			cn = "Coins: An Oath We Exchange",
			tw = "Coins: An Oath We Exchange",
		},
	},
	[558372] = {
		readable = "Geologist Field Journal",
		model = 949611,
		text = {
			en = "Geologist Field Journal",
			es = "Geologist Field Journal",
			mx = "Geologist Field Journal",
			de = "Geologist Field Journal",
			fr = "Geologist Field Journal",
			it = "Geologist Field Journal",
			pt = "Geologist Field Journal",
			ru = "Geologist Field Journal",
			ko = "Geologist Field Journal",
			cn = "Geologist Field Journal",
			tw = "Geologist Field Journal",
		},
	},
})
do ObjectDB[objectID] = objectData; end
