local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[475164] = {
		readable = "Ve'nari's Package",
		text = {
			en = "Ve'nari's Package",
			es = "Ve'nari's Package",
			mx = "Ve'nari's Package",
			de = "Ve'nari's Package",
			fr = "Ve'nari's Package",
			it = "Ve'nari's Package",
			pt = "Ve'nari's Package",
			ru = "Ve'nari's Package",
			ko = "Ve'nari's Package",
			cn = "Ve'nari's Package",
			tw = "Ve'nari's Package",
		},
	},
	[475207] = {
		readable = "Honey Pot",
		model = 5203781,
		text = {
			en = "Honey Pot",
			es = "Honey Pot",
			mx = "Honey Pot",
			de = "Honey Pot",
			fr = "Honey Pot",
			it = "Honey Pot",
			pt = "Honey Pot",
			ru = "Honey Pot",
			ko = "Honey Pot",
			cn = "Honey Pot",
			tw = "Honey Pot",
		},
	},
	[475213] = {
		readable = "Ve'nari's Package",
		text = {
			en = "Ve'nari's Package",
			es = "Ve'nari's Package",
			mx = "Ve'nari's Package",
			de = "Ve'nari's Package",
			fr = "Ve'nari's Package",
			it = "Ve'nari's Package",
			pt = "Ve'nari's Package",
			ru = "Ve'nari's Package",
			ko = "Ve'nari's Package",
			cn = "Ve'nari's Package",
			tw = "Ve'nari's Package",
		},
	},
	[475250] = {
		readable = "Honey Pot",
		model = 5203782,
		text = {
			en = "Honey Pot",
			es = "Honey Pot",
			mx = "Honey Pot",
			de = "Honey Pot",
			fr = "Honey Pot",
			it = "Honey Pot",
			pt = "Honey Pot",
			ru = "Honey Pot",
			ko = "Honey Pot",
			cn = "Honey Pot",
			tw = "Honey Pot",
		},
	},
	[475314] = {
		readable = "Pricklebloom",
		text = {
			en = "Pricklebloom",
			es = "Pricklebloom",
			mx = "Pricklebloom",
			de = "Pricklebloom",
			fr = "Pricklebloom",
			it = "Pricklebloom",
			pt = "Pricklebloom",
			ru = "Pricklebloom",
			ko = "Pricklebloom",
			cn = "Pricklebloom",
			tw = "Pricklebloom",
		},
	},
	[475321] = {
		readable = "Crystalbloom",
		text = {
			en = "Crystalbloom",
			es = "Crystalbloom",
			mx = "Crystalbloom",
			de = "Crystalbloom",
			fr = "Crystalbloom",
			it = "Crystalbloom",
			pt = "Crystalbloom",
			ru = "Crystalbloom",
			ko = "Crystalbloom",
			cn = "Crystalbloom",
			tw = "Crystalbloom",
		},
	},
	[475324] = {
		readable = "Firebud",
		model = 4093303,
		text = {
			en = "Firebud",
			es = "Firebud",
			mx = "Firebud",
			de = "Firebud",
			fr = "Firebud",
			it = "Firebud",
			pt = "Firebud",
			ru = "Firebud",
			ko = "Firebud",
			cn = "Firebud",
			tw = "Firebud",
		},
	},
	[475391] = {
		readable = "Honeycomb",
		model = 1777397,
		text = {
			en = "Honeycomb",
			es = "Honeycomb",
			mx = "Honeycomb",
			de = "Honeycomb",
			fr = "Honeycomb",
			it = "Honeycomb",
			pt = "Honeycomb",
			ru = "Honeycomb",
			ko = "Honeycomb",
			cn = "Honeycomb",
			tw = "Honeycomb",
		},
	},
	[475392] = {
		readable = "Honeycomb",
		text = {
			en = "Honeycomb",
			es = "Honeycomb",
			mx = "Honeycomb",
			de = "Honeycomb",
			fr = "Honeycomb",
			it = "Honeycomb",
			pt = "Honeycomb",
			ru = "Honeycomb",
			ko = "Honeycomb",
			cn = "Honeycomb",
			tw = "Honeycomb",
		},
	},
	[475393] = {
		readable = "Honeycomb",
		text = {
			en = "Honeycomb",
			es = "Honeycomb",
			mx = "Honeycomb",
			de = "Honeycomb",
			fr = "Honeycomb",
			it = "Honeycomb",
			pt = "Honeycomb",
			ru = "Honeycomb",
			ko = "Honeycomb",
			cn = "Honeycomb",
			tw = "Honeycomb",
		},
	},
	[516700] = {
		readable = "Oasis Animal Leavings",
		model = 304609,
		text = {
			en = "Oasis Animal Leavings",
			es = "Oasis Animal Leavings",
			mx = "Oasis Animal Leavings",
			de = "Oasis Animal Leavings",
			fr = "Oasis Animal Leavings",
			it = "Oasis Animal Leavings",
			pt = "Oasis Animal Leavings",
			ru = "Oasis Animal Leavings",
			ko = "Oasis Animal Leavings",
			cn = "Oasis Animal Leavings",
			tw = "Oasis Animal Leavings",
		},
	},
	[516792] = {
		readable = "Watering Jug",
		text = {
			en = "Watering Jug",
			es = "Watering Jug",
			mx = "Watering Jug",
			de = "Watering Jug",
			fr = "Watering Jug",
			it = "Watering Jug",
			pt = "Watering Jug",
			ru = "Watering Jug",
			ko = "Watering Jug",
			cn = "Watering Jug",
			tw = "Watering Jug",
		},
	},
})
do ObjectDB[objectID] = objectData; end
