local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[469724] = {
		readable = "Damaged Echo Surveyor",
		text = {
			en = "Damaged Echo Surveyor",
			es = "Damaged Echo Surveyor",
			mx = "Damaged Echo Surveyor",
			de = "Damaged Echo Surveyor",
			fr = "Damaged Echo Surveyor",
			it = "Damaged Echo Surveyor",
			pt = "Damaged Echo Surveyor",
			ru = "Damaged Echo Surveyor",
			ko = "Damaged Echo Surveyor",
			cn = "Damaged Echo Surveyor",
			tw = "Damaged Echo Surveyor",
		},
	},
	[469871] = {
		readable = "Console Battery",
		model = 3993862,
		text = {
			en = "Console Battery",
			es = "Console Battery",
			mx = "Console Battery",
			de = "Console Battery",
			fr = "Console Battery",
			it = "Console Battery",
			pt = "Console Battery",
			ru = "Console Battery",
			ko = "Console Battery",
			cn = "Console Battery",
			tw = "Console Battery",
		},
	},
	[477249] = {
		readable = "Stolen Supplies",
		text = {
			en = "Stolen Supplies",
			es = "Stolen Supplies",
			mx = "Stolen Supplies",
			de = "Stolen Supplies",
			fr = "Stolen Supplies",
			it = "Stolen Supplies",
			pt = "Stolen Supplies",
			ru = "Stolen Supplies",
			ko = "Stolen Supplies",
			cn = "Stolen Supplies",
			tw = "Stolen Supplies",
		},
	},
	[483713] = {
		readable = "Watering Jug",
		text = {
			en = "Watering Jug",
			es = "Watering Jug",
			mx = "Watering Jug",
			de = "Watering Jug",
			fr = "Watering Jug",
			it = "Watering Jug",
			pt = "Watering Jug",
			ru = "Watering Jug",
			ko = "Watering Jug",
			cn = "Watering Jug",
			tw = "Watering Jug",
		},
	},
	[500046] = {
		readable = "Gift of the Brothers",
		text = {
			en = "Gift of the Brothers",
			es = "Gift of the Brothers",
			mx = "Gift of the Brothers",
			de = "Gift of the Brothers",
			fr = "Gift of the Brothers",
			it = "Gift of the Brothers",
			pt = "Gift of the Brothers",
			ru = "Gift of the Brothers",
			ko = "Gift of the Brothers",
			cn = "Gift of the Brothers",
			tw = "Gift of the Brothers",
		},
	},
	[503823] = {
		readable = "Mailroom Distribution",
		model = 3920034,
		text = {
			en = "Mailroom Distribution",
			es = "Mailroom Distribution",
			mx = "Mailroom Distribution",
			de = "Mailroom Distribution",
			fr = "Mailroom Distribution",
			it = "Mailroom Distribution",
			pt = "Mailroom Distribution",
			ru = "Mailroom Distribution",
			ko = "Mailroom Distribution",
			cn = "Mailroom Distribution",
			tw = "Mailroom Distribution",
		},
	},
	[516444] = {
		readable = "Ethereal Pocket-Storage",
		text = {
			en = "Ethereal Pocket-Storage",
			es = "Ethereal Pocket-Storage",
			mx = "Ethereal Pocket-Storage",
			de = "Ethereal Pocket-Storage",
			fr = "Ethereal Pocket-Storage",
			it = "Ethereal Pocket-Storage",
			pt = "Ethereal Pocket-Storage",
			ru = "Ethereal Pocket-Storage",
			ko = "Ethereal Pocket-Storage",
			cn = "Ethereal Pocket-Storage",
			tw = "Ethereal Pocket-Storage",
		},
	},
	[516994] = {
		readable = "Tazavesh Trash",
		model = 3930677,
		text = {
			en = "Tazavesh Trash",
			es = "Tazavesh Trash",
			mx = "Tazavesh Trash",
			de = "Tazavesh Trash",
			fr = "Tazavesh Trash",
			it = "Tazavesh Trash",
			pt = "Tazavesh Trash",
			ru = "Tazavesh Trash",
			ko = "Tazavesh Trash",
			cn = "Tazavesh Trash",
			tw = "Tazavesh Trash",
		},
	},
	[558108] = {
		readable = "Multiversal Energy Dynamics and the Murmuration Paradox",
		model = 949619,
		text = {
			en = "Multiversal Energy Dynamics and the Murmuration Paradox",
			es = "Multiversal Energy Dynamics and the Murmuration Paradox",
			mx = "Multiversal Energy Dynamics and the Murmuration Paradox",
			de = "Multiversal Energy Dynamics and the Murmuration Paradox",
			fr = "Multiversal Energy Dynamics and the Murmuration Paradox",
			it = "Multiversal Energy Dynamics and the Murmuration Paradox",
			pt = "Multiversal Energy Dynamics and the Murmuration Paradox",
			ru = "Multiversal Energy Dynamics and the Murmuration Paradox",
			ko = "Multiversal Energy Dynamics and the Murmuration Paradox",
			cn = "Multiversal Energy Dynamics and the Murmuration Paradox",
			tw = "Multiversal Energy Dynamics and the Murmuration Paradox",
		},
	},
	[558110] = {
		readable = "From Vengeance to Void",
		model = 3836262,
		text = {
			en = "From Vengeance to Void",
			es = "From Vengeance to Void",
			mx = "From Vengeance to Void",
			de = "From Vengeance to Void",
			fr = "From Vengeance to Void",
			it = "From Vengeance to Void",
			pt = "From Vengeance to Void",
			ru = "From Vengeance to Void",
			ko = "From Vengeance to Void",
			cn = "From Vengeance to Void",
			tw = "From Vengeance to Void",
		},
	},
})
do ObjectDB[objectID] = objectData; end
