local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[499022] = {
		readable = "Corrupted Chest",
		model = 3048900,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
		},
	},
	[499026] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
		},
	},
	[499028] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
		},
	},
	[499029] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
		},
	},
	[499031] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
		},
	},
	[499954] = {
		readable = "Corrupted Chest",
		model = 3048900,
		text = {
			en = "Corrupted Chest",
			es = "Corrupted Chest",
			de = "Corrupted Chest",
			fr = "Corrupted Chest",
			it = "Corrupted Chest",
			pt = "Corrupted Chest",
			ru = "Corrupted Chest",
			ko = "Corrupted Chest",
			cn = "Corrupted Chest",
		},
	},
	[524391] = {
		readable = "Prize Chest",
		model = 5788112,
		text = {
			en = "Prize Chest",
			es = "Prize Chest",
			de = "Prize Chest",
			fr = "Prize Chest",
			it = "Prize Chest",
			pt = "Prize Chest",
			ru = "Prize Chest",
			ko = "Prize Chest",
			cn = "Prize Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end