local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[516153] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			es = "Dented Crate",
			de = "Dented Crate",
			fr = "Dented Crate",
			it = "Dented Crate",
			pt = "Dented Crate",
			ru = "Dented Crate",
			ko = "Dented Crate",
			cn = "Dented Crate",
		},
	},
	[516155] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			es = "Dented Crate",
			de = "Dented Crate",
			fr = "Dented Crate",
			it = "Dented Crate",
			pt = "Dented Crate",
			ru = "Dented Crate",
			ko = "Dented Crate",
			cn = "Dented Crate",
		},
	},
	[516157] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			es = "Dented Crate",
			de = "Dented Crate",
			fr = "Dented Crate",
			it = "Dented Crate",
			pt = "Dented Crate",
			ru = "Dented Crate",
			ko = "Dented Crate",
			cn = "Dented Crate",
		},
	},
	[516159] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			es = "Dented Crate",
			de = "Dented Crate",
			fr = "Dented Crate",
			it = "Dented Crate",
			pt = "Dented Crate",
			ru = "Dented Crate",
			ko = "Dented Crate",
			cn = "Dented Crate",
		},
	},
	[516164] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			es = "Dented Crate",
			de = "Dented Crate",
			fr = "Dented Crate",
			it = "Dented Crate",
			pt = "Dented Crate",
			ru = "Dented Crate",
			ko = "Dented Crate",
			cn = "Dented Crate",
		},
	},
	[516166] = {
		readable = "Dented Crate",
		text = {
			en = "Dented Crate",
			es = "Dented Crate",
			de = "Dented Crate",
			fr = "Dented Crate",
			it = "Dented Crate",
			pt = "Dented Crate",
			ru = "Dented Crate",
			ko = "Dented Crate",
			cn = "Dented Crate",
		},
	},
})
do ObjectDB[objectID] = objectData; end