local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[466393] = {
		readable = "Astral Chest",
		model = 353152,
		text = {
			en = "Astral Chest",
			de = "Astraltruhe",
			es = "Cofre astral",
			fr = "Coffre astral",
			it = "Cassa Astrale",
			mx = "Cofre astral",
			pt = "Baú Astral",
			ru = "Астральный сундук",
			ko = "천공의 보관함",
			cn = "星界宝箱",
			tw = "星界箱子",
		},
	},
	[466400] = {
		readable = "\"Property of Elder Ko'nani\"",
		model = 4008620,
		text = {
			en = "\"Property of Elder Ko'nani\"",
			de = "\"Eigentum von Ältester Ko'nani\"]",
			es = "\"Propiedad del anciano Ko'nani\"]",
			fr = "« Propriété de l’ancien Ko’nani »",
			it = "\"Proprietà dell'Anziano Ko'nani\"]",
			mx = "\"Propiedad del ancestro Ko'nani\"]",
			pt = "\"Propriedade do Ancião Ko'nani\"",
			ru = "\"Собственность старейшины Ко'нани\"",
			ko = "\"장로 코나니의 재산\"]",
			cn = "“长者库纳尼的财物”",
			tw = "「長者科納尼所有」"
		},
	},
	[466420] = {
		readable = "Rubenstein's Safe",
		model = 203020,
		text = {
			en = "Rubenstein's Safe",
			de = "Rubensteins Tresor",
			es = "Caja fuerte de Rubenstein",
			fr = "Coffre-fort de Rubenstein",
			it = "Cassaforte di Rubenstein",
			mx = "Caja fuerte de Rubenstein",
			pt = "Cofre de Rubenstein",
			ru = "Сейф Рубенштейна",
			ko = "루벤슈타인의 금고",
			cn = "鲁布斯坦的保险箱",
			tw = "魯賓斯坦的保險箱",
		},
	},
	[466479] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			de = "Verschlüsselte Truhe",
			es = "Cofre encriptado",
			fr = "Coffre codé",
			it = "Cassa Cifrata",
			mx = "Cofre cifrado",
			pt = "Baú Cifrado",
			ru = "Зашифрованный сундук",
			ko = "마법에 걸린 보관함",
			cn = "加密的宝箱",
			tw = "加密箱子",
		},
	},
	[466484] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			de = "Verschlüsselte Truhe",
			es = "Cofre encriptado",
			fr = "Coffre codé",
			it = "Cassa Cifrata",
			mx = "Cofre cifrado",
			pt = "Baú Cifrado",
			ru = "Зашифрованный сундук",
			ko = "마법에 걸린 보관함",
			cn = "加密的宝箱",
			tw = "加密箱子",
		},
	},
	[466489] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			de = "Verschlüsselte Truhe",
			es = "Cofre encriptado",
			fr = "Coffre codé",
			it = "Cassa Cifrata",
			mx = "Cofre cifrado",
			pt = "Baú Cifrado",
			ru = "Зашифрованный сундук",
			ko = "마법에 걸린 보관함",
			cn = "加密的宝箱",
			tw = "加密箱子",
		},
	},
	[466495] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			de = "Verschlüsselte Truhe",
			es = "Cofre encriptado",
			fr = "Coffre codé",
			it = "Cassa Cifrata",
			mx = "Cofre cifrado",
			pt = "Baú Cifrado",
			ru = "Зашифрованный сундук",
			ko = "마법에 걸린 보관함",
			cn = "加密的宝箱",
			tw = "加密箱子",
		},
	},
	[466497] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			de = "Verschlüsselte Truhe",
			es = "Cofre encriptado",
			fr = "Coffre codé",
			it = "Cassa Cifrata",
			mx = "Cofre cifrado",
			pt = "Baú Cifrado",
			ru = "Зашифрованный сундук",
			ko = "마법에 걸린 보관함",
			cn = "加密的宝箱",
			tw = "加密箱子",
		},
	},
})
do ObjectDB[objectID] = objectData; end
