local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[467468] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			es = "Muff's Auto-Locker",
			de = "Muff's Auto-Locker",
			fr = "Muff's Auto-Locker",
			it = "Muff's Auto-Locker",
			pt = "Muff's Auto-Locker",
			ru = "Muff's Auto-Locker",
			ko = "Muff's Auto-Locker",
			cn = "Muff's Auto-Locker",
		},
	},
	[474393] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			es = "Muff's Auto-Locker",
			de = "Muff's Auto-Locker",
			fr = "Muff's Auto-Locker",
			it = "Muff's Auto-Locker",
			pt = "Muff's Auto-Locker",
			ru = "Muff's Auto-Locker",
			ko = "Muff's Auto-Locker",
			cn = "Muff's Auto-Locker",
		},
	},
	[474397] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			es = "Muff's Auto-Locker",
			de = "Muff's Auto-Locker",
			fr = "Muff's Auto-Locker",
			it = "Muff's Auto-Locker",
			pt = "Muff's Auto-Locker",
			ru = "Muff's Auto-Locker",
			ko = "Muff's Auto-Locker",
			cn = "Muff's Auto-Locker",
		},
	},
	[474398] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			es = "Muff's Auto-Locker",
			de = "Muff's Auto-Locker",
			fr = "Muff's Auto-Locker",
			it = "Muff's Auto-Locker",
			pt = "Muff's Auto-Locker",
			ru = "Muff's Auto-Locker",
			ko = "Muff's Auto-Locker",
			cn = "Muff's Auto-Locker",
		},
	},
	[476068] = {
		readable = "Papa's Prized Putter",
		text = {
			en = "Papa's Prized Putter",
			es = "Papa's Prized Putter",
			de = "Papa's Prized Putter",
			fr = "Papa's Prized Putter",
			it = "Papa's Prized Putter",
			pt = "Papa's Prized Putter",
			ru = "Papa's Prized Putter",
			ko = "Papa's Prized Putter",
			cn = "Papa's Prized Putter",
		},
	},
	[476071] = {
		readable = "Unsupervised Takeout",
		text = {
			en = "Unsupervised Takeout",
			es = "Unsupervised Takeout",
			de = "Unsupervised Takeout",
			fr = "Unsupervised Takeout",
			it = "Unsupervised Takeout",
			pt = "Unsupervised Takeout",
			ru = "Unsupervised Takeout",
			ko = "Unsupervised Takeout",
			cn = "Unsupervised Takeout",
		},
	},
	[477363] = {
		readable = "Particularly Nice Lamp",
		text = {
			en = "Particularly Nice Lamp",
			es = "Particularly Nice Lamp",
			de = "Particularly Nice Lamp",
			fr = "Particularly Nice Lamp",
			it = "Particularly Nice Lamp",
			pt = "Particularly Nice Lamp",
			ru = "Particularly Nice Lamp",
			ko = "Particularly Nice Lamp",
			cn = "Particularly Nice Lamp",
		},
	},
	[477374] = {
		readable = "Uncracked Cold Ones",
		text = {
			en = "Uncracked Cold Ones",
			es = "Uncracked Cold Ones",
			de = "Uncracked Cold Ones",
			fr = "Uncracked Cold Ones",
			it = "Uncracked Cold Ones",
			pt = "Uncracked Cold Ones",
			ru = "Uncracked Cold Ones",
			ko = "Uncracked Cold Ones",
			cn = "Uncracked Cold Ones",
		},
	},
	[477376] = {
		readable = "Trick Deck of Cards",
		text = {
			en = "Trick Deck of Cards",
			es = "Trick Deck of Cards",
			de = "Trick Deck of Cards",
			fr = "Trick Deck of Cards",
			it = "Trick Deck of Cards",
			pt = "Trick Deck of Cards",
			ru = "Trick Deck of Cards",
			ko = "Trick Deck of Cards",
			cn = "Trick Deck of Cards",
		},
	},
	[493307] = {
		readable = "Inert Plunger?",
		model = 343855,
		text = {
			en = "Inert Plunger?",
			es = "Inert Plunger?",
			de = "Inert Plunger?",
			fr = "Inert Plunger?",
			it = "Inert Plunger?",
			pt = "Inert Plunger?",
			ru = "Inert Plunger?",
			ko = "Inert Plunger?",
			cn = "Inert Plunger?",
		},
	},
	[495592] = {
		readable = "Blackened Dice",
		text = {
			en = "Blackened Dice",
			es = "Blackened Dice",
			de = "Blackened Dice",
			fr = "Blackened Dice",
			it = "Blackened Dice",
			pt = "Blackened Dice",
			ru = "Blackened Dice",
			ko = "Blackened Dice",
			cn = "Blackened Dice",
		},
	},
	[504096] = {
		readable = "Crumpled Schematics",
		text = {
			en = "Crumpled Schematics",
			es = "Crumpled Schematics",
			de = "Crumpled Schematics",
			fr = "Crumpled Schematics",
			it = "Crumpled Schematics",
			pt = "Crumpled Schematics",
			ru = "Crumpled Schematics",
			ko = "Crumpled Schematics",
			cn = "Crumpled Schematics",
		},
	},
})
do ObjectDB[objectID] = objectData; end