local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[495603] = {
		readable = "Loose Sand",
		text = {
			en = "Loose Sand",
			es = "Loose Sand",
			mx = "Loose Sand",
			de = "Loose Sand",
			fr = "Loose Sand",
			it = "Loose Sand",
			pt = "Loose Sand",
			ru = "Loose Sand",
			ko = "Loose Sand",
			cn = "Loose Sand",
			tw = "Loose Sand",
		},
	},
	[516302] = {
		readable = "Pricklebloom",
		text = {
			en = "Pricklebloom",
			es = "Pricklebloom",
			mx = "Pricklebloom",
			de = "Pricklebloom",
			fr = "Pricklebloom",
			it = "Pricklebloom",
			pt = "Pricklebloom",
			ru = "Pricklebloom",
			ko = "Pricklebloom",
			cn = "Pricklebloom",
			tw = "Pricklebloom",
		},
	},
	[516304] = {
		readable = "Lustrous Conker",
		text = {
			en = "Lustrous Conker",
			es = "Lustrous Conker",
			mx = "Lustrous Conker",
			de = "Lustrous Conker",
			fr = "Lustrous Conker",
			it = "Lustrous Conker",
			pt = "Lustrous Conker",
			ru = "Lustrous Conker",
			ko = "Lustrous Conker",
			cn = "Lustrous Conker",
			tw = "Lustrous Conker",
		},
	},
	[516626] = {
		readable = "Phase-Lost Pocket-Storage",
		model = 2833918,
		text = {
			en = "Phase-Lost Pocket-Storage",
			es = "Phase-Lost Pocket-Storage",
			mx = "Phase-Lost Pocket-Storage",
			de = "Phase-Lost Pocket-Storage",
			fr = "Phase-Lost Pocket-Storage",
			it = "Phase-Lost Pocket-Storage",
			pt = "Phase-Lost Pocket-Storage",
			ru = "Phase-Lost Pocket-Storage",
			ko = "Phase-Lost Pocket-Storage",
			cn = "Phase-Lost Pocket-Storage",
			tw = "Phase-Lost Pocket-Storage",
		},
	},
	[529539] = {
		readable = "Petrified Branch of Janaa",
		text = {
			en = "Petrified Branch of Janaa",
			es = "Petrified Branch of Janaa",
			mx = "Petrified Branch of Janaa",
			de = "Petrified Branch of Janaa",
			fr = "Petrified Branch of Janaa",
			it = "Petrified Branch of Janaa",
			pt = "Petrified Branch of Janaa",
			ru = "Petrified Branch of Janaa",
			ko = "Petrified Branch of Janaa",
			cn = "Petrified Branch of Janaa",
			tw = "Petrified Branch of Janaa",
		},
	},
	[529643] = {
		readable = "Tulwar of the Golden Guard",
		text = {
			en = "Tulwar of the Golden Guard",
			es = "Tulwar of the Golden Guard",
			mx = "Tulwar of the Golden Guard",
			de = "Tulwar of the Golden Guard",
			fr = "Tulwar of the Golden Guard",
			it = "Tulwar of the Golden Guard",
			pt = "Tulwar of the Golden Guard",
			ru = "Tulwar of the Golden Guard",
			ko = "Tulwar of the Golden Guard",
			cn = "Tulwar of the Golden Guard",
			tw = "Tulwar of the Golden Guard",
		},
	},
	[547995] = {
		readable = "Warglaive of the Audacious Hunter",
		text = {
			en = "Warglaive of the Audacious Hunter",
			es = "Warglaive of the Audacious Hunter",
			mx = "Warglaive of the Audacious Hunter",
			de = "Warglaive of the Audacious Hunter",
			fr = "Warglaive of the Audacious Hunter",
			it = "Warglaive of the Audacious Hunter",
			pt = "Warglaive of the Audacious Hunter",
			ru = "Warglaive of the Audacious Hunter",
			ko = "Warglaive of the Audacious Hunter",
			cn = "Warglaive of the Audacious Hunter",
			tw = "Warglaive of the Audacious Hunter",
		},
	},
})
do ObjectDB[objectID] = objectData; end
