local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[474396] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			de = "Muffs Selbstschließer",
			es = "Baúl automático de Muff",
			mx = "Baúl automático de Muff",
			fr = "Autovestiaire de Muff",
			it = "Blocco Automatico di Muff",
			pt = "Autotrancante de Muff",
			ru = "Автозапиратель недотепы",
			ko = "머프의 자동 잠금 장치",
			cn = "傻瓜式自动锁柜",
			tw = "莫夫的自動上鎖箱",
		},
	},
	[475987] = { -- this object no exist out ptr,  please check to delete from here
		readable = "Pile 'o' Scrap",
		text = {
			en = "Pile 'o' Scrap",
			es = "Pile 'o' Scrap",
			mx = "Pile 'o' Scrap",
			de = "Pile 'o' Scrap",
			fr = "Pile 'o' Scrap",
			it = "Pile 'o' Scrap",
			pt = "Pile 'o' Scrap",
			ru = "Pile 'o' Scrap",
			ko = "Pile 'o' Scrap",
			cn = "Pile 'o' Scrap",
			tw = "Pile 'o' Scrap",
		},
	},
	[475990] = {
		readable = "Junk Pile",
		text = {
			en = "Junk Pile",
			de = "Müllhaufen",
			es = "Montón de chatarra",
			mx = "Montón de chatarra",
			fr = "Tas de camelote",
			it = "Pila di Rifiuti",
			pt = "Pilha de Sucata",
			ru = "Груда мусора",
			ko = "잡동사니 더미",
			cn = "垃圾堆",
			tw = "垃圾堆",
		},
	},
	[476066] = {
		readable = "Abandoned Toolbox",
		text = {
			en = "Abandoned Toolbox",
			de = "Zurückgelassene Werkzeugkiste",
			es = "Caja de herramientas abandonada",
			mx = "Caja de herramientas abandonada",
			fr = "Boîte à outils abandonnée",
			it = "Cassetta degli Attrezzi Abbandonata",
			pt = "Caixa de Ferramentas Abandonada",
			ru = "Брошенный ящик с инструментами",
			ko = "버려진 연장통",
			cn = "被丢弃的工具箱",
			tw = "廢棄工具箱",
		},
	},
	[476070] = {
		readable = "Potent Potable",
		text = {
			en = "Potent Potable",
			de = "Kräftige Komposition",
			es = "Mejunje potente",
			mx = "Mejunje potente",
			fr = "Boisson forte",
			it = "Bevanda Potente",
			pt = "Potável Potente",
			ru = "Мощное зелье",
			ko = "고성능 휴대 장치",
			cn = "强效饮料",
			tw = "強力飲料",
		},
	},
	[477373] = {
		readable = "Marooned Floatmingo",
		text = {
			en = "Marooned Floatmingo",
			de = "Verlassener Floßmingo",
			es = "Flamenco flotante abandonado",
			mx = "Flotamenco abandonado",
			fr = "Flottemant rose échoué",
			it = "Fenicottero Galleggiante Abbandonato",
			pt = "Flutuamingo Encalhado",
			ru = "Брошенный плавминго",
			ko = "고립된 풍선학",
			cn = "孤独的充气火烈鸟",
			tw = "受困的漂浮紅鶴",
		},
	},
	[490816] = {
		readable = "Unexploded Fireworks",
		text = {
			en = "Unexploded Fireworks",
			de = "Nicht explodiertes Feuerwerk",
			es = "Fuegos artificiales sin explotar",
			mx = "Fuegos artificiales no explotados",
			fr = "Feux d’artifice inutilisés",
			it = "Fuochi d'Artificio Inesplosi",
			pt = "Fogos de Artifício Não Explodidos",
			ru = "Неразорвавшиеся фейерверки",
			ko = "폭발하지 않은 폭죽",
			cn = "未爆炸的烟花",
			tw = "未爆炸的煙火",
		},
	},
	[499119] = {
		readable = "Lonely Tub",
		text = {
			en = "Lonely Tub",
			de = "Einsame Wanne",
			es = "Cubo solitario",
			mx = "Bañera solitaria",
			fr = "Bassine isolée",
			it = "Vasca Solitaria",
			pt = "Banheira Solitária",
			ru = "Одинокая лохань",
			ko = "외로운 통",
			cn = "偏僻的澡盆",
			tw = "孤單的木盆",
		},
	},
	[502917] = {
		readable = "Misplaced Work Order",
		model = 936411,
		text = {
			en = "Misplaced Work Order",
			de = "Verlegter Arbeitsauftrag",
			es = "Pedido extraviado",
			mx = "Orden de trabajo extraviada",
			fr = "Commande égarée",
			it = "Ordine di Lavoro Smarrito",
			pt = "Ordem de Serviço Equivocada",
			ru = "Потерянный наряд на работу",
			ko = "잘못 놓인 주문서",
			cn = "错放的工作指令",
			tw = "遺落的訂單",
		},
	},
})
do ObjectDB[objectID] = objectData; end
