local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[474396] = {
		readable = "Muff's Auto-Locker",
		text = {
			en = "Muff's Auto-Locker",
			es = "Muff's Auto-Locker",
			de = "Muff's Auto-Locker",
			fr = "Muff's Auto-Locker",
			it = "Muff's Auto-Locker",
			pt = "Muff's Auto-Locker",
			ru = "Muff's Auto-Locker",
			ko = "Muff's Auto-Locker",
			cn = "Muff's Auto-Locker",
		},
	},
	[475987] = {
		readable = "Pile 'o' Scrap",
		text = {
			en = "Pile 'o' Scrap",
			es = "Pile 'o' Scrap",
			de = "Pile 'o' Scrap",
			fr = "Pile 'o' Scrap",
			it = "Pile 'o' Scrap",
			pt = "Pile 'o' Scrap",
			ru = "Pile 'o' Scrap",
			ko = "Pile 'o' Scrap",
			cn = "Pile 'o' Scrap",
		},
	},
	[475990] = {
		readable = "Junk Pile",
		text = {
			en = "Junk Pile",
			es = "Junk Pile",
			de = "Junk Pile",
			fr = "Junk Pile",
			it = "Junk Pile",
			pt = "Junk Pile",
			ru = "Junk Pile",
			ko = "Junk Pile",
			cn = "Junk Pile",
		},
	},
	[476066] = {
		readable = "Abandoned Toolbox",
		text = {
			en = "Abandoned Toolbox",
			es = "Abandoned Toolbox",
			de = "Abandoned Toolbox",
			fr = "Abandoned Toolbox",
			it = "Abandoned Toolbox",
			pt = "Abandoned Toolbox",
			ru = "Abandoned Toolbox",
			ko = "Abandoned Toolbox",
			cn = "Abandoned Toolbox",
		},
	},
	[476070] = {
		readable = "Potent Potable",
		text = {
			en = "Potent Potable",
			es = "Potent Potable",
			de = "Potent Potable",
			fr = "Potent Potable",
			it = "Potent Potable",
			pt = "Potent Potable",
			ru = "Potent Potable",
			ko = "Potent Potable",
			cn = "Potent Potable",
		},
	},
	[477373] = {
		readable = "Marooned Floatmingo",
		text = {
			en = "Marooned Floatmingo",
			es = "Marooned Floatmingo",
			de = "Marooned Floatmingo",
			fr = "Marooned Floatmingo",
			it = "Marooned Floatmingo",
			pt = "Marooned Floatmingo",
			ru = "Marooned Floatmingo",
			ko = "Marooned Floatmingo",
			cn = "Marooned Floatmingo",
		},
	},
	[490816] = {
		readable = "Unexploded Fireworks",
		text = {
			en = "Unexploded Fireworks",
			es = "Unexploded Fireworks",
			de = "Unexploded Fireworks",
			fr = "Unexploded Fireworks",
			it = "Unexploded Fireworks",
			pt = "Unexploded Fireworks",
			ru = "Unexploded Fireworks",
			ko = "Unexploded Fireworks",
			cn = "Unexploded Fireworks",
		},
	},
	[499119] = {
		readable = "Lonely Tub",
		text = {
			en = "Lonely Tub",
			es = "Lonely Tub",
			de = "Lonely Tub",
			fr = "Lonely Tub",
			it = "Lonely Tub",
			pt = "Lonely Tub",
			ru = "Lonely Tub",
			ko = "Lonely Tub",
			cn = "Lonely Tub",
		},
	},
	[502917] = {
		readable = "Misplaced Work Order",
		model = 936411,
		text = {
			en = "Misplaced Work Order",
			es = "Misplaced Work Order",
			de = "Misplaced Work Order",
			fr = "Misplaced Work Order",
			it = "Misplaced Work Order",
			pt = "Misplaced Work Order",
			ru = "Misplaced Work Order",
			ko = "Misplaced Work Order",
			cn = "Misplaced Work Order",
		},
	},
})
do ObjectDB[objectID] = objectData; end