local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[499956] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[499957] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[499958] = {
		readable = "Corrupted Chest",
		model = 3048901,
		text = {
			en = "Corrupted Chest",
			de = "Verderbte Truhe",
			es = "Cofre corrupto",
			mx = "Cofre corrupto",
			fr = "Coffre corrompu",
			it = "Cassa Corrotta",
			pt = "Baú Corrompido",
			ru = "Зараженный сундук",
			ko = "타락의 상자",
			cn = "腐化的宝箱",
			tw = "腐化寶箱",
		},
	},
	[517344] = {
		readable = "Cursed Horseshoe",
		model = 929369,
		text = {
			en = "Cursed Horseshoe",
			de = "Verfluchtes Hufeisen",
			es = "Herradura maldita",
			mx = "Herradura maldita",
			fr = "Fer à cheval maudit",
			it = "Ferro di Cavallo Maledetto",
			pt = "Ferradura Amaldiçoada",
			ru = "Проклятая подкова",
			ko = "Cursed Horseshoe",
			cn = "被诅咒的马蹄铁",
			tw = "詛咒馬蹄鐵",
		},
	},
	[517348] = {
		readable = "Cursed Horseshoe",
		model = 929369,
		text = {
			en = "Cursed Horseshoe",
			de = "Verfluchtes Hufeisen",
			es = "Herradura maldita",
			mx = "Herradura maldita",
			fr = "Fer à cheval maudit",
			it = "Ferro di Cavallo Maledetto",
			pt = "Ferradura Amaldiçoada",
			ru = "Проклятая подкова",
			ko = "Cursed Horseshoe",
			cn = "被诅咒的马蹄铁",
			tw = "詛咒馬蹄鐵",
		},
	},
	[517349] = {
		readable = "Cursed Horseshoe",
		model = 929369,
		text = {
			en = "Cursed Horseshoe",
			de = "Verfluchtes Hufeisen",
			es = "Herradura maldita",
			mx = "Herradura maldita",
			fr = "Fer à cheval maudit",
			it = "Ferro di Cavallo Maledetto",
			pt = "Ferradura Amaldiçoada",
			ru = "Проклятая подкова",
			ko = "Cursed Horseshoe",
			cn = "被诅咒的马蹄铁",
			tw = "詛咒馬蹄鐵",
		},
	},
	[517350] = {
		readable = "Cursed Horseshoe",
		model = 929369,
		text = {
			en = "Cursed Horseshoe",
			de = "Verfluchtes Hufeisen",
			es = "Herradura maldita",
			mx = "Herradura maldita",
			fr = "Fer à cheval maudit",
			it = "Ferro di Cavallo Maledetto",
			pt = "Ferradura Amaldiçoada",
			ru = "Проклятая подкова",
			ko = "Cursed Horseshoe",
			cn = "被诅咒的马蹄铁",
			tw = "詛咒馬蹄鐵",
		},
	},
	[519487] = {
		readable = "Worn Wolf Saddle",
		model = 850504,
		text = {
			en = "Worn Wolf Saddle",
			de = "Abgenutzter Wolfsattel",
			es = "Silla de montar de lobo gastada",
			mx = "Silla de montar de lobo desgastada",
			fr = "Selle de loup usée",
			it = "Sella da Lupo Consumata",
			pt = "Sela de Lobo Gasta",
			ru = "Изношенное волчье седло",
			ko = "닳은 늑대 안장",
			cn = "狼皮鞍座",
			tw = "破舊的狼鞍",
		},
	},
	[519559] = {
		readable = "Bag of Wolf Tack",
		model = 878854,
		text = {
			en = "Bag of Wolf Tack",
			de = "Tasche mit Zaum- und Sattelzeug für Wölfe",
			es = "Bolsa de aperos de lobo",
			mx = "Bolsa de arreos de lobo",
			fr = "Sac de sellerie pour loup",
			it = "Borsa di Selleria per Lupi",
			pt = "Bolsa de Arreios de Lobo",
			ru = "Сумка с волчьей сбруей",
			ko = "늑대 먹이 가방",
			cn = "座狼用具包",
			tw = "巨狼鞍轡袋",
		},
	},
	[529289] = {
		readable = "Spore Sample",
		model = 5201692,
		text = {
			en = "Spore Sample",
			de = "Sporenprobe",
			es = "Muestra de esporas",
			mx = "Muestra de esporas",
			fr = "Échantillon sporique",
			it = "Campione di Spora",
			pt = "Amostra de Esporo",
			ru = "Образец спор",
			ko = "포자 표본",
			cn = "孢子样本",
			tw = "孢子樣本",
		},
	},
	[529677] = {
		readable = "Void-Forged Engine Block",
		model = 197685,
		text = {
			en = "Void-Forged Engine Block",
			de = "Leerengeschmiedeter Motorblock",
			es = "Bloque motor forjado en el Vacío",
			mx = "Bloque de motor forjado por el Vacío",
			fr = "Bloc moteur forgé par le Vide",
			it = "Blocco Motore Forgiato dal Vuoto",
			pt = "Bloco de Motor Forjado no Caos",
			ru = "Блок цилиндров из Бездны",
			ko = "공허벼림 동력장치 집합체",
			cn = "虚铸引擎机体",
			tw = "虛無鑄造引擎本體",
		},
	},
})
do ObjectDB[objectID] = objectData; end
