local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[452866] = {
		readable = "Semi-Deluxe Noggenfogger Elixirs",
		model = 1310398,
		text = {
			en = "Semi-Deluxe Noggenfogger Elixirs",
			de = "Noggenfoggers halbluxuriöse Elixiere",
			es = "Elixir de semilujo de Tragonublo",
			mx = "Elixires de Tragonublo semilujosos",
			fr = "Élixirs Brouillecaboche semi-luxe",
			it = "Elisir di Granstrippo Semi-Deluxe",
			pt = "Elixires Nublacuca Semi-Deluxe",
			ru = "Почти изысканные эликсиры Гогельмогеля",
			ko = "준명품 노겐포저의 비약",
			cn = "半豪华版诺格弗格药剂",
			tw = "略顯豪華的諾格弗格藥劑",
		},
	},
	[500345] = {
		readable = "Ethereal Warning Letter",
		model = 936413,
		text = {
			en = "Ethereal Warning Letter",
			de = "Astraler Warnbrief",
			es = "Carta de advertencia etérea",
			mx = "Carta de advertencia de etéreos",
			fr = "Lettre d’avertissement éthérée",
			it = "Lettera d'Avvertimento Eterea",
			pt = "Carta de Alerta Etérea",
			ru = "Предупреждение об эфириалах",
			ko = "에테리얼의 경고 편지",
			cn = "虚灵警告信",
			tw = "以太族警告信",
		},
	},
	[500619] = {
		readable = "Zirdo's Ledger",
		model = 970085,
		text = {
			en = "Zirdo's Ledger",
			de = "Zirdos Geschäftsbuch",
			es = "Libro de contabilidad de Zirdo",
			mx = "Registro de Zirdo",
			fr = "Registre de Zirdo",
			it = "Libro Mastro di Zirdo",
			pt = "Livro-caixa de Zirdo",
			ru = "Учетная книга Зирдо",
			ko = "지르도의 장부",
			cn = "吉尔多的账本",
			tw = "吉多的手帳",
		},
	},
})
do ObjectDB[objectID] = objectData; end
