local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[473943] = {
		readable = "Salvageable Scrap",
		model = 1103093,
		text = {
			en = "Salvageable Scrap",
			de = "Verwertbarer Schrott",
			es = "Chatarra aprovechable",
			mx = "Chatarra reciclable",
			fr = "Matériau recyclable",
			it = "Scarto Recuperabile",
			pt = "Sucata Recuperável",
			ru = "Металлолом",
			ko = "쓸 만한 고철",
			cn = "可回收的废料",
			tw = "可回收的碎塊",
		},
	},
	[474030] = {
		readable = "Salvageable Scrap",
		model = 1611709,
		text = {
			en = "Salvageable Scrap",
			de = "Verwertbarer Schrott",
			es = "Chatarra aprovechable",
			mx = "Chatarra reciclable",
			fr = "Matériau recyclable",
			it = "Scarto Recuperabile",
			pt = "Sucata Recuperável",
			ru = "Металлолом",
			ko = "쓸 만한 고철",
			cn = "可回收的废料",
			tw = "可回收的碎塊",
		},
	},
	[474033] = {
		readable = "Salvageable Scrap",
		model = 1121294,
		text = {
			en = "Salvageable Scrap",
			de = "Verwertbarer Schrott",
			es = "Chatarra aprovechable",
			mx = "Chatarra reciclable",
			fr = "Matériau recyclable",
			it = "Scarto Recuperabile",
			pt = "Sucata Recuperável",
			ru = "Металлолом",
			ko = "쓸 만한 고철",
			cn = "可回收的废料",
			tw = "可回收的碎塊",
		},
	},
	[474084] = {
		readable = "Salvageable Scrap",
		model = 1140791,
		text = {
			en = "Salvageable Scrap",
			de = "Verwertbarer Schrott",
			es = "Chatarra aprovechable",
			mx = "Chatarra reciclable",
			fr = "Matériau recyclable",
			it = "Scarto Recuperabile",
			pt = "Sucata Recuperável",
			ru = "Металлолом",
			ko = "쓸 만한 고철",
			cn = "可回收的废料",
			tw = "可回收的碎塊",
		},
	},
	[474086] = {
		readable = "Salvageable Scrap",
		model = 2261829,
		text = {
			en = "Salvageable Scrap",
			de = "Verwertbarer Schrott",
			es = "Chatarra aprovechable",
			mx = "Chatarra reciclable",
			fr = "Matériau recyclable",
			it = "Scarto Recuperabile",
			pt = "Sucata Recuperável",
			ru = "Металлолом",
			ko = "쓸 만한 고철",
			cn = "可回收的废料",
			tw = "可回收的碎塊",
		},
	},
})
do ObjectDB[objectID] = objectData; end
