local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[469475] = {
		readable = "Stolen Barrier Projector",
		text = {
			en = "Stolen Barrier Projector",
			es = "Stolen Barrier Projector",
			mx = "Stolen Barrier Projector",
			de = "Stolen Barrier Projector",
			fr = "Stolen Barrier Projector",
			it = "Stolen Barrier Projector",
			pt = "Stolen Barrier Projector",
			ru = "Stolen Barrier Projector",
			ko = "Stolen Barrier Projector",
			cn = "Stolen Barrier Projector",
			tw = "Stolen Barrier Projector",
		},
	},
	[500813] = {
		readable = "Rod of analysis",
		text = {
			en = "Rod of analysis",
			es = "Rod of analysis",
			mx = "Rod of analysis",
			de = "Rod of analysis",
			fr = "Rod of analysis",
			it = "Rod of analysis",
			pt = "Rod of analysis",
			ru = "Rod of analysis",
			ko = "Rod of analysis",
			cn = "Rod of analysis",
			tw = "Rod of analysis",
		},
	},
	[502525] = {
		readable = "Barrier Projector",
		text = {
			en = "Barrier Projector",
			es = "Barrier Projector",
			mx = "Barrier Projector",
			de = "Barrier Projector",
			fr = "Barrier Projector",
			it = "Barrier Projector",
			pt = "Barrier Projector",
			ru = "Barrier Projector",
			ko = "Barrier Projector",
			cn = "Barrier Projector",
			tw = "Barrier Projector",
		},
	},
	[502907] = {
		readable = "Rod of Activation",
		text = {
			en = "Rod of Activation",
			es = "Rod of Activation",
			mx = "Rod of Activation",
			de = "Rod of Activation",
			fr = "Rod of Activation",
			it = "Rod of Activation",
			pt = "Rod of Activation",
			ru = "Rod of Activation",
			ko = "Rod of Activation",
			cn = "Rod of Activation",
			tw = "Rod of Activation",
		},
	},
})
do ObjectDB[objectID] = objectData; end
