local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[499099] = {
		readable = "Entropic Egg",
		model = 5049181,
		text = {
			en = "Entropic Egg",
			es = "Entropic Egg",
			mx = "Entropic Egg",
			de = "Entropic Egg",
			fr = "Entropic Egg",
			it = "Entropic Egg",
			pt = "Entropic Egg",
			ru = "Entropic Egg",
			ko = "Entropic Egg",
			cn = "Entropic Egg",
			tw = "Entropic Egg",
		},
	},
	[507058] = {
		readable = "Northeast Barrier Projector",
		text = {
			en = "Northeast Barrier Projector",
			es = "Northeast Barrier Projector",
			mx = "Northeast Barrier Projector",
			de = "Northeast Barrier Projector",
			fr = "Northeast Barrier Projector",
			it = "Northeast Barrier Projector",
			pt = "Northeast Barrier Projector",
			ru = "Northeast Barrier Projector",
			ko = "Northeast Barrier Projector",
			cn = "Northeast Barrier Projector",
			tw = "Northeast Barrier Projector",
		},
	},
	[558112] = {
		readable = "The Facets of K'aresh",
		model = 3836264,
		text = {
			en = "The Facets of K'aresh",
			es = "The Facets of K'aresh",
			mx = "The Facets of K'aresh",
			de = "The Facets of K'aresh",
			fr = "The Facets of K'aresh",
			it = "The Facets of K'aresh",
			pt = "The Facets of K'aresh",
			ru = "The Facets of K'aresh",
			ko = "The Facets of K'aresh",
			cn = "The Facets of K'aresh",
			tw = "The Facets of K'aresh",
		},
	},
	[567735] = {
		readable = "Northwest Barrier Projector",
		text = {
			en = "Northwest Barrier Projector",
			es = "Northwest Barrier Projector",
			mx = "Northwest Barrier Projector",
			de = "Northwest Barrier Projector",
			fr = "Northwest Barrier Projector",
			it = "Northwest Barrier Projector",
			pt = "Northwest Barrier Projector",
			ru = "Northwest Barrier Projector",
			ko = "Northwest Barrier Projector",
			cn = "Northwest Barrier Projector",
			tw = "Northwest Barrier Projector",
		},
	},
	[567736] = {
		readable = "South Barrier Projector",
		text = {
			en = "South Barrier Projector",
			es = "South Barrier Projector",
			mx = "South Barrier Projector",
			de = "South Barrier Projector",
			fr = "South Barrier Projector",
			it = "South Barrier Projector",
			pt = "South Barrier Projector",
			ru = "South Barrier Projector",
			ko = "South Barrier Projector",
			cn = "South Barrier Projector",
			tw = "South Barrier Projector",
		},
	},
})
do ObjectDB[objectID] = objectData; end
