local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[478679] = {
		readable = "Salvage Part",
		model = 203234,
		text = {
			en = "Salvage Part",
			de = "Bergungsteil",
			es = "Pieza desguazada",
			mx = "Pieza de reciclaje",
			fr = "Pièce détachée",
			it = "Parte Recuperata",
			pt = "Peça Recuperada",
			ru = "Запчасть",
			ko = "회수한 부품",
			cn = "回收部件",
			tw = "回收零件",
		},
	},
	[500759] = {
		readable = "Uncovered Strongbox",
		text = {
			en = "Uncovered Strongbox",
			de = "Aufgedeckte Schließkassette",
			es = "Caja fuerte descubierta",
			mx = "Caja fuerte descubierta",
			fr = "Coffre renforcé découvert",
			it = "Forziere Scoperto",
			pt = "Caixa-forte Descoberta",
			ru = "Откопанный сундучок",
			ko = "발견되지 않은 금고",
			cn = "发现的保险箱",
			tw = "發現的保險箱",
		},
	},
	[503450] = {
		readable = "Chunk of Charged Glass",
		text = {
			en = "Chunk of Charged Glass",
			de = "Brocken geladenes Glas",
			es = "Trozo de cristal cargado",
			mx = "Trozo de vidrio cargado",
			fr = "Morceau de verre chargé",
			it = "Pezzo di Vetro Caricato",
			pt = "Pedaço de Vidro Carregado",
			ru = "Осколок заряженного стекла",
			ko = "충만한 유리 덩어리",
			cn = "大块充能玻璃",
			tw = "大塊充能玻璃",
		},
	},
	[503870] = {
		readable = "Nemesis Strongbox",
		model = 2907352,
		text = {
			en = "Nemesis Strongbox",
			de = "Schließkassette der Nemesis",
			es = "Caja fuerte de némesis",
			mx = "Caja fuerte de némesis",
			fr = "Coffre-fort de Némésis",
			it = "Forziere della Nemesi",
			pt = "Caixa-forte da Nêmesis",
			ru = "Сейф заклятого врага",
			ko = "원수의 금고",
			cn = "宿敌保险箱",
			tw = "死敵保險箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end
