local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[504074] = {
		readable = "Nether Reader",
		model = 4094671,
		text = {
			en = "Nether Reader",
			es = "Nether Reader",
			mx = "Nether Reader",
			de = "Nether Reader",
			fr = "Nether Reader",
			it = "Nether Reader",
			pt = "Nether Reader",
			ru = "Nether Reader",
			ko = "Nether Reader",
			cn = "Nether Reader",
			tw = "Nether Reader",
		},
	},
	[529669] = {
		readable = "Korgorath's Talon",
		text = {
			en = "Korgorath's Talon",
			es = "Korgorath's Talon",
			mx = "Korgorath's Talon",
			de = "Korgorath's Talon",
			fr = "Korgorath's Talon",
			it = "Korgorath's Talon",
			pt = "Korgorath's Talon",
			ru = "Korgorath's Talon",
			ko = "Korgorath's Talon",
			cn = "Korgorath's Talon",
			tw = "Korgorath's Talon",
		},
	},
	[558117] = {
		readable = "I Have Become Void!",
		model = 3978478,
		text = {
			en = "I Have Become Void!",
			es = "I Have Become Void!",
			mx = "I Have Become Void!",
			de = "I Have Become Void!",
			fr = "I Have Become Void!",
			it = "I Have Become Void!",
			pt = "I Have Become Void!",
			ru = "I Have Become Void!",
			ko = "I Have Become Void!",
			cn = "I Have Become Void!",
			tw = "I Have Become Void!",
		},
	},
	[558375] = {
		readable = "Checklist of Minor Pleasures",
		model = 3836262,
		text = {
			en = "Checklist of Minor Pleasures",
			es = "Checklist of Minor Pleasures",
			mx = "Checklist of Minor Pleasures",
			de = "Checklist of Minor Pleasures",
			fr = "Checklist of Minor Pleasures",
			it = "Checklist of Minor Pleasures",
			pt = "Checklist of Minor Pleasures",
			ru = "Checklist of Minor Pleasures",
			ko = "Checklist of Minor Pleasures",
			cn = "Checklist of Minor Pleasures",
			tw = "Checklist of Minor Pleasures",
		},
	},
})
do ObjectDB[objectID] = objectData; end
