local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[478443] = {
		readable = "Mislaid Curiosity",
		model = 5100456,
		text = {
			en = "Mislaid Curiosity",
			es = "Mislaid Curiosity",
			de = "Mislaid Curiosity",
			fr = "Mislaid Curiosity",
			it = "Mislaid Curiosity",
			pt = "Mislaid Curiosity",
			ru = "Mislaid Curiosity",
			ko = "Mislaid Curiosity",
			cn = "Mislaid Curiosity",
		},
	},
	[503013] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[503868] = {
		readable = "Nemesis Strongbox",
		model = 2907352,
		text = {
			en = "Nemesis Strongbox",
			es = "Nemesis Strongbox",
			de = "Nemesis Strongbox",
			fr = "Nemesis Strongbox",
			it = "Nemesis Strongbox",
			pt = "Nemesis Strongbox",
			ru = "Nemesis Strongbox",
			ko = "Nemesis Strongbox",
			cn = "Nemesis Strongbox",
		},
	},
	[503869] = {
		readable = "Nemesis Strongbox",
		model = 2907352,
		text = {
			en = "Nemesis Strongbox",
			es = "Nemesis Strongbox",
			de = "Nemesis Strongbox",
			fr = "Nemesis Strongbox",
			it = "Nemesis Strongbox",
			pt = "Nemesis Strongbox",
			ru = "Nemesis Strongbox",
			ko = "Nemesis Strongbox",
			cn = "Nemesis Strongbox",
		},
	},
	[503871] = {
		readable = "Nemesis Strongbox",
		model = 2907352,
		text = {
			en = "Nemesis Strongbox",
			es = "Nemesis Strongbox",
			de = "Nemesis Strongbox",
			fr = "Nemesis Strongbox",
			it = "Nemesis Strongbox",
			pt = "Nemesis Strongbox",
			ru = "Nemesis Strongbox",
			ko = "Nemesis Strongbox",
			cn = "Nemesis Strongbox",
		},
	},
})
do ObjectDB[objectID] = objectData; end