local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[523414] = {
		readable = "Snake Nest",
		model = 202734,
		text = {
			en = "Snake Nest",
			es = "Snake Nest",
			mx = "Snake Nest",
			de = "Snake Nest",
			fr = "Snake Nest",
			it = "Snake Nest",
			pt = "Snake Nest",
			ru = "Snake Nest",
			ko = "Snake Nest",
			cn = "Snake Nest",
			tw = "Snake Nest",
		},
	},
	[523415] = {
		readable = "Fragrant Dreaming Glory",
		model = 219446,
		text = {
			en = "Fragrant Dreaming Glory",
			es = "Fragrant Dreaming Glory",
			mx = "Fragrant Dreaming Glory",
			de = "Fragrant Dreaming Glory",
			fr = "Fragrant Dreaming Glory",
			it = "Fragrant Dreaming Glory",
			pt = "Fragrant Dreaming Glory",
			ru = "Fragrant Dreaming Glory",
			ko = "Fragrant Dreaming Glory",
			cn = "Fragrant Dreaming Glory",
			tw = "Fragrant Dreaming Glory",
		},
	},
	[523494] = {
		readable = "Marsh Moss",
		model = 1794518,
		text = {
			en = "Marsh Moss",
			es = "Marsh Moss",
			mx = "Marsh Moss",
			de = "Marsh Moss",
			fr = "Marsh Moss",
			it = "Marsh Moss",
			pt = "Marsh Moss",
			ru = "Marsh Moss",
			ko = "Marsh Moss",
			cn = "Marsh Moss",
			tw = "Marsh Moss",
		},
	},
	[523689] = {
		readable = "Mossy Snake Bed",
		model = 5006773,
		text = {
			en = "Mossy Snake Bed",
			es = "Mossy Snake Bed",
			mx = "Mossy Snake Bed",
			de = "Mossy Snake Bed",
			fr = "Mossy Snake Bed",
			it = "Mossy Snake Bed",
			pt = "Mossy Snake Bed",
			ru = "Mossy Snake Bed",
			ko = "Mossy Snake Bed",
			cn = "Mossy Snake Bed",
			tw = "Mossy Snake Bed",
		},
	},
	[523827] = {
		readable = "Comfy Snake Bed",
		model = 5006773,
		text = {
			en = "Comfy Snake Bed",
			es = "Comfy Snake Bed",
			mx = "Comfy Snake Bed",
			de = "Comfy Snake Bed",
			fr = "Comfy Snake Bed",
			it = "Comfy Snake Bed",
			pt = "Comfy Snake Bed",
			ru = "Comfy Snake Bed",
			ko = "Comfy Snake Bed",
			cn = "Comfy Snake Bed",
			tw = "Comfy Snake Bed",
		},
	},
	[524223] = {
		readable = "K'arroc Egg",
		model = 1711713,
		text = {
			en = "K'arroc Egg",
			es = "K'arroc Egg",
			mx = "K'arroc Egg",
			de = "K'arroc Egg",
			fr = "K'arroc Egg",
			it = "K'arroc Egg",
			pt = "K'arroc Egg",
			ru = "K'arroc Egg",
			ko = "K'arroc Egg",
			cn = "K'arroc Egg",
			tw = "K'arroc Egg",
		},
	},
	[549326] = {
		readable = "Phase-Lost Exchequer",
		model = 3920034,
		text = {
			en = "Phase-Lost Exchequer",
			es = "Phase-Lost Exchequer",
			mx = "Phase-Lost Exchequer",
			de = "Phase-Lost Exchequer",
			fr = "Phase-Lost Exchequer",
			it = "Phase-Lost Exchequer",
			pt = "Phase-Lost Exchequer",
			ru = "Phase-Lost Exchequer",
			ko = "Phase-Lost Exchequer",
			cn = "Phase-Lost Exchequer",
			tw = "Phase-Lost Exchequer",
		},
	},
})
do ObjectDB[objectID] = objectData; end
