WINDS_OF_MYSTERIOUS_FORTUNE_HEADER = createHeader({
	readable = "Winds of Mysterious Fortune",
	icon = 6439633,
	eventID = EVENTS.WINDS_OF_MYSTERIOUS_FORTUNE,
	text = {
		en = "Winds of Mysterious Fortune",
		de = "Winde des mysteriösen Glücks",
		es = "Vientos de fortuna misteriosa",
		mx = "Vientos de fortuna misteriosa",
		fr = "Vents de bonne aventure mystérieuse",
		it = "Venti della Fortuna Misteriosa",
		pt = "Ventos da Fortuna Misteriosa",
		ru = "Ветра таинственной удачи",
		ko = "수수께끼의 운세의 바람",
		cn = "神秘运势之风",
		tw = "神​秘命​運​之​風",
	},
	description = {
		en = "Earn bonus experience and reputation on your adventures in Azeroth, and find mysterious fortunes in the Dragon Isles and Khaz Algar!",
		de = "Erhaltet zusätzliche Erfahrung und Ruf auf Euren Abenteuern in Azeroth und findet geheimnisvolle Schätze auf den Dracheninseln und in Khaz Algar!",
		es = "¡Consigue más experiencia y reputación en tus aventuras por Azeroth y descubre tesoros misteriosos en las Islas Dragón y en Khaz Algar!",
		mx = "Gana experiencia y reputación adicional en tus aventuras por Azeroth, ¡y encuentra misteriosas fortunas en las Islas Dragón y Khaz Algar!",
		fr = "Gagnez de l’expérience et de la réputation supplémentaires dans vos aventures sur Azeroth et trouvez de mystérieuses bonnes aventures sur les îles aux Dragons et en Khaz Algar !",
		it = "Ottieni esperienza e reputazione bonus nel corso delle tue avventure ad Azeroth, e trova tesori misteriosi sulle Isole dei Draghi e a Khaz Algar!",
		pt = "Ganhe bônus de experiência e reputação em suas aventuras em Azeroth e ache fortuitos mistérios nas Ilhas do Dragão e em Khaz Algar!",
		ru = "Получайте больше опыта и репутации в ходе приключений на Азероте и находите таинственные сокровища на Драконьих островах и в Каз Алгаре!",
		ko = "아제로스를 모험하며 추가 경험치와 평판을 획득하고, 용의 섬과 카즈 알가르에서 수수께끼의 보물을 발견해 보십시오!",
		cn = "在艾泽拉斯冒险可以获得额外的经验值和声望，还能在巨龙群岛和卡兹阿加找到神秘的鸿运之礼！",
		tw = "在艾澤拉斯冒險可以獲得額外的經驗與聲望，還能在巨龍群島以及卡茲阿爾加找到神秘​的​背袋！",
	},
});
