-- Last updated via https://wago.tools/db2/HolidayNames?build=11.2.5.62554
EVENTS = {
	-- Seasonal Holidays
	BREWFEST = 7,
	CHILDRENS_WEEK = 13,
	DARKMOON_FAIRE = 1,
	DAY_OF_THE_DEAD = 81,
	FEAST_OF_WINTER_VEIL = 14,
	HALLOWS_END = 16,
	HARVEST_FESTIVAL = 17,
	LOVE_IS_IN_THE_AIR = 9,
	LUNAR_FESTIVAL = 18,
	MIDSUMMER_FIRE_FESTIVAL = 11,
	NOBLEGARDEN = 15,
	PILGRIMS_BOUNTY = 101,
	PIRATES_DAY = 21,

	-- Seasonal Fish
	SEASONAL_FISH_SUMMER_BASS = 133889,	-- Generic Header [Crieve made this up, it's just supposed to be Unique!]
	SEASONAL_FISH_WINTER_SQUID = 133899,	-- Generic Header [Crieve made this up, it's just supposed to be Unique!]

	-- Weekly Events
	KALUAK_FISHING_DERBY = 161,
	STRANGLETHORN_FISHING_EXTRAVAGANZA = 6,
	--WANDERERS_FESTIVAL = 392,	-- This is the eventID for the yearly version, not the fake weekly one.
	WANDERERS_FESTIVAL = 133900,	-- Generic Header [Crieve made this up, it's just supposed to be Unique!]

	-- Micro-Holidays
	CALL_OF_THE_SCARAB = 248,
	FREE_T_SHIRT_DAY = 393,
	MARCH_OF_THE_TADPOLES = 253,
--	SECRETS_OF_AZEROTH = 425,	-- No longer needed as the event is always active now.
	THE_GREAT_GNOMEREGAN_RUN = 266,
	THOUSAND_BOAT_BASH = 249,
	TRIAL_OF_STYLE = 258,

	-- FOMO
	PLUNDERSTORM = 444,
	REMIX_LEGION = 447,
	REMIX_MOP = 437,
	DASTARDLY_DUOS = 451,
	WINDS_OF_MYSTERIOUS_FORTUNE = 450,
	A_GREEDY_EMISSARY = 422,

	-- Dragonriding Cups
	-- Note: These need to all be referenced in src\Modules\Events.lua
	DRAGONRIDING_CUP = 133701,	-- Generic Header [Crieve made this up, it's just supposed to be Unique!]
	KALIMDOR_CUP = 424,
	EASTERN_KINGDOMS_CUP = 427,
	OUTLAND_CUP = 428,
	NORTHREND_CUP = 431,
	PANDARIA_CUP = 432,
	BROKEN_ISLES_CUP = 433,

	-- No event file exists for these yet. (and maybe they don't need to?)
	AUCTION_HOUSE_DANCE_PARTY = 259,
	FIREWORKS_CELEBRATION = 5,
	FIREWORKS_SPECTACULAR = 12,
	GLOWCAP_FESTIVAL = 254,
	HATCHING_OF_THE_HIPPOGYPHS = 245,
	KIRIN_TOR_TAVERN_CRAWL = 252,
	LUMINOUS_LUMINARIES = 394,
	MOONKIN_FESTIVAL = 261,
	PET_BATTLE_BONUS_EVENT = 234,
	SPRING_BALLOON_FESTIVAL = 251,
	UNGORO_MADNESS = 250,
	VOLUNTEER_GUARD_DAY = 246,
	WELCOME_TO_SANCTUARY = 423,
	WORLD_QUEST_BONUS_EVENT = 244,

	-- Add PVP Brawls?
	-- TODO: Not wasting my time pasting this right now!

	-- Timewalking
	TIMEWALKING = 239,	-- Generic, "any" timewalking event
	TIMEWALKING_CLASSIC_DUNGEON_EVENT = 1508,
	-- EU	1583 (USED IN EVENT.LUA REMAPPING)
	-- CN/TW1584 (USED IN EVENT.LUA REMAPPING)
	-- KR	1585 (USED IN EVENT.LUA REMAPPING)
	TIMEWALKING_OUTLAND_DUNGEON_EVENT = 559,
	-- EU	622 (USED IN EVENT.LUA REMAPPING)
	-- CN/TW624 (USED IN EVENT.LUA REMAPPING)
	-- KR	623 (USED IN EVENT.LUA REMAPPING)
	TIMEWALKING_NORTHREND_DUNGEON_EVENT = 562,
	-- EU	616 (USED IN EVENT.LUA REMAPPING)
	-- CN/TW617 (USED IN EVENT.LUA REMAPPING)
	-- KR	618 (USED IN EVENT.LUA REMAPPING)
	TIMEWALKING_CATACLYSM_DUNGEON_EVENT = 587,
	-- EU	628 (USED IN EVENT.LUA REMAPPING)
	-- CN/TW630 (USED IN EVENT.LUA REMAPPING)
	-- KR	629 (USED IN EVENT.LUA REMAPPING)
	TIMEWALKING_MISTS_OF_PANDARIA_DUNGEON_EVENT = 643,
	-- EU	652 (USED IN EVENT.LUA REMAPPING)
	-- CN/TW654 (USED IN EVENT.LUA REMAPPING)
	-- KR	656 (USED IN EVENT.LUA REMAPPING)
	TIMEWALKING_WARLORDS_OF_DRAENOR_DUNGEON_EVENT = 1056,
	-- EU	1063 (USED IN EVENT.LUA REMAPPING)
	-- CN/TW1065 (USED IN EVENT.LUA REMAPPING)
	-- KR	1068 (USED IN EVENT.LUA REMAPPING)
	TIMEWALKING_LEGION_DUNGEON_EVENT = 1263,
	-- EU	1265 (USED IN EVENT.LUA REMAPPING)
	-- CN/TW1267 (USED IN EVENT.LUA REMAPPING)
	-- KR	1269 (USED IN EVENT.LUA REMAPPING)
	TIMEWALKING_BATTLE_FOR_AZEROTH_DUNGEON_EVENT = 1669,
	-- EU	1667 (USED IN EVENT.LUA REMAPPING)
	-- CN/TW1668 (USED IN EVENT.LUA REMAPPING)
	-- KR	1666 (USED IN EVENT.LUA REMAPPING)
	-- These aren't eventIDs, they're groups of eventIDs...
	WOW_ANNIVERSARY = 242,
};
