UPGRADETRACKS = {
	VETERAN = 972,
	CHAMPION = 973,
	HERO = 974,
	MYTH = 978,
}

UPGRADETRACK_BYDIFFICULTY = {
	[DIFFICULTY.RAID.LFR] = UPGRADETRACKS.VETERAN,
	[DIFFICULTY.RAID.NORMAL] = UPGRADETRACKS.CHAMPION,
	[DIFFICULTY.RAID.HEROIC] = UPGRADETRACKS.HERO,
	[DIFFICULTY.RAID.MYTHIC] = UPGRADETRACKS.MYTH,
}
